### ISSUE TITLE
Feature Dev - Design alert system

### ISSUE THREAD

**Issue by Abott1222** [freeCodeCamp/chapter#10]
As a user I would like to be reminded of events that I signed up to when they are coming up

User Story:
[ ] Spike research smtp or other service that we can use
[ ] Implement bot that would search through all of the current upcoming meetups and alert each member ** think of scale....
[ ] Implement unsubscribe feature in the case that a user no longer wants these emails

**Comment by QuincyLarson** [comment]
@Abott1222 Yes - I think email will be the primary way that people communicate. The world doesn't need another messaging system.

We could have a basic user settings page where people can toggle their email notifications on and off for different groups and manage all their RSVPs in one place.

**Comment by mblonyox** [comment]
Push Notification would be good too.

**Comment by mandaputtra** [comment]
I think push notifications aren't needed if we dont plan to make native apps / PWA. Email is enough, I would love this app as simple as possible.

If we plan to use PWA and make a push notifications, there are litelary just 10% people click on allow when the notifications permission confirmation pop-up

**Comment by bernhard-hofmann** [comment]
The simplest approach by far is to create iCalendar links to allow users to add events to their own calendars and control their own reminders.

https://en.m.wikipedia.org/wiki/ICalendar

**Comment by keeth** [comment]
I've had good results sending emails with embedded iCalendar too.  So you just send a single confirmation email with embedded iCal when they register for the event, and they can self-manage any reminders.

**Comment by brianrichins** [comment]
> I think push notifications aren't needed if we dont plan to make native apps / PWA. [ ... ] just 10% people click on allow when the notifications permission confirmation pop-up

Push notifications are a great way to engage users, I think it'd be a valuable feature. PWAs can support push, and they also can be smart enough to not ask for permissions until there's a reasonable expectation the user will accept. The fact that [most sites throw it in your face on the first visit](https://2018.bloomca.me) is just bad UX implementation.

**Comment by allella** [comment]
Closing this as it's already in the list on #84 

The story in the main list has been linked back to this for future reference.
