### ISSUE TITLE
As a user (authenticated or not) I can view the RSVP count for an event

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/chapter#101]
Implementation details:

- events/[id] and dashboard/events/[id] would both need to display the count
- they already have access to the list of RSVPs, so we can just count them up in JS.

**Comment by Ravichandra-C** [comment]
Hi @ojeytonwilliams , Can I pick up this issue?. Could you please let me know what needs to be done?

**Comment by allella** [comment]
@Ravichandra-C  I posted in the chat about fixing one of the Docker issues.

Oliver is away for a couple weeks and will be slower to reply. However, I did ask him about the best way to run the db:reset to properly drop, migrate, and seed the database with fake / test data like shown here.  However, I have a temporary work around for that too if we don't hear back from him soon.

![image](https://user-images.githubusercontent.com/1777776/131779590-9f3f2078-2d2a-4162-af8f-33cda9e99d96.png)

**Comment by Ravichandra-C** [comment]
@allella , Is the temporary workaround ,copying the scripts to package.json?

**Comment by allella** [comment]
@Ravichandra-C we may end up moving some of the scripts from package.json to server/package.json, but I'd like to hear from Oliver about if that makes sense.

As a workaround, see my notes in the chat at https://chat.freecodecamp.org/channel/chapter?msg=NvEq4zeCJwLM8CJCb

**Comment by Ravichandra-C** [comment]
@allella @ojeytonwilliams Can I just show the number in the Green area in the image?


![image](https://user-images.githubusercontent.com/17808008/132101105-bb0067e8-dba6-4013-9a4a-216180496475.png)



![image](https://user-images.githubusercontent.com/17808008/132101372-89a0bd74-081d-4652-bc5b-463396a29e60.png)

**Comment by allella** [comment]
@Ravichandra-C I think that would be fine to start.  If you can add a count for the "Waitlist" too, then that would be a nice addition.

We aren't focusing on the design, but we have a couple mockups to give the idea of basic layout and design ideas.

https://www.figma.com/proto/q7DikyL3N0c4CUWxHNa97i/Chapter-Prototype?node-id=140%3A30&scaling=scale-down
https://preview.uxpin.com/13c1d07f6dd731123612a8884eb4174459312ac5#/pages/138361235/simulate/sitemap
