### ISSUE TITLE
API: As an organizer I can create events and set their location, tags and capacity.

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/chapter#102]

**Comment by allella** [comment]
This should be fairly obvious, but #126 specifically wanted to make sure events can have longer descriptions, which is part of the current schema with a text field of events.description.

**Comment by joelrozen** [comment]
Is this front end or back end or both? Happy to take either way.

**Comment by vkWeb** [comment]
@joelrozen I feel it's both. The front end part will be a form to enter event details as per schema and to display it on the landing page and events page. Only admin and organizers can create events. Back end to parse that data & to store in database. 

@joelrozen You are one of the most helpful contributor out there. I would love to see you on our next meeting :) I am assigning this to you. I know you'll be able to do it ;)


@timmyichen, @Zeko369 am I correct?

**Comment by Zeko369** [comment]
@vkWeb +1, I'll review it when you have something @joelrozen

**Comment by allella** [comment]
Not sure if it needs it's own to-do, but tags are something that's sort of implied by this user story, but I added the word "tags" into the title.  If we need to break it into a separate story then feel free to undo.

**Comment by allella** [comment]
#253 is aiming to update the schema to allow for tags, instead of the one tag limitation of the initial schema.

**Comment by joelrozen** [comment]
@vkWeb @QuincyLarson Hey team, apologies on this one, been flat out and looking at my calendar leading up to Christmas, probably not going to have time to tackle this before hand.
I'm still happy to do it, but it probably won't be until the break, so if it needs doing sooner please feel free to reassign and I can pick something else up when I can :)

**Comment by QuincyLarson** [comment]
@joelrozen Thanks for your candor. No worries - I will un-assign you from this for now in case someone else wants to jump on it. 

I know it's a busy time of year. We would welcome your help after the holidays. Merry Christmas.

**Comment by Zeko369** [comment]
I was thinking about streaming building this to twitch tomorrow after the meeting, anyone interested to hop on a discord voice channel and do it with me?

**Comment by timmyichen** [comment]
> I was thinking about streaming building this to twitch tomorrow after the meeting, anyone interested to hop on a discord voice channel and do it with me?

sure, totes down
