### ISSUE TITLE
Client might not receive data after resetting db

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/chapter#1024]
### Describe the bug:
I mentioned this issue long time ago in chat, but just today I've found what's relevant for the reproducing it (I think).

1. Register as new user
1. Login as new user
1. Run `npm run db:reset`
1. `F5` in browser
1. Client doesn't get any data from server, spinners will spin infinitely
1. To make things work again - remove site data in browser

- Issue doesn't occur when logged in as seeded user (`foo@bar.com`).

### Tell us about your browser and operating system:
- Browser(s) (checked on): Firefox 99, Brave 1.37.116
- Operating System: ubuntu 20.04

**Comment by allella** [comment]
By chance, is this related to the [_JsonWebTokenError: invalid signature_ error](https://github.com/freeCodeCamp/chapter/issues/471)?

**Comment by gikf** [comment]
I haven't seen any explicit error, but it's likely that token is involved here.
