### ISSUE TITLE
As an organizer I can add an organization logo in the settings

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/chapter#103]

**Comment by QuincyLarson** [comment]
This could initially just be hotlinking by asking people to link directly to an image. Then we can add a proper image uploading functionality in a later release.

**Comment by Zeko369** [comment]
This should defiantly be a link to the image hosted somewhere else for the MVP

**Comment by QuincyLarson** [comment]
Let's leave this as a Heroku environment variable.
