### ISSUE TITLE
API: As an administrator, I can create a chapter.

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/chapter#105]

**Comment by Zeko369** [comment]
Will probably also do this
_Originally posted by @Zeko369 in https://github.com/freeCodeCamp/chapter/issues/102#issuecomment-565741374_

**Comment by allella** [comment]
Based on [today's meeting](https://github.com/freeCodeCamp/chapter/wiki/Meeting-Notes-February-9,-2020), and [earlier conversations on roles](https://github.com/freeCodeCamp/chapter/issues/296), we decided only an _administrator_ would be able to create new _chapters_.  So, I'm changing the title of this issue and #273 to reflect that decision.

**Comment by allella** [comment]
@Zeko369  re-opened this in case there is anything that needs to be changed on this issue since we're saying only the Administrator needs to create new _chapters_.

If not the please feel free to close and move to Done on the project board.

Thanks

**Comment by QuincyLarson** [comment]
I'm closing this in favor of #273
