### ISSUE TITLE
As a user / future participant when I click one of those locations, I can see the "show view" for that event's chapter, with details about the upcoming event, along with a button to RSVP.

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/chapter#111]

**Comment by allella** [comment]
@ojeytonwilliams it sounds like this is a view all events page for a Chapter.

It was likely added as a starter MVP list by Quincy [during or after the 1st meeting](https://github.com/freeCodeCamp/chapter/wiki/Meeting-Notes-October-20,-2019). It wasn't a big enough topic that it got anymore context.

**Comment by ojeytonwilliams** [comment]
Sorry Jim, this slipped under my radar.  

> Chris moved the "Filter Events" user story from issue #83 to #84, as we decided it was not part of an MVP

Was it this point?

**Comment by allella** [comment]
Seems like this issue made the post-MVP list on #84  and nobody seems to understand what it means, so I'd say we close it.
