### ISSUE TITLE
As a user / future participant I can use a search box on the landing page to input a city, state, or country name and it will autocomplete. I can click one of those locations.

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/chapter#112]

**Comment by Vitao18** [comment]
Hey
Can I help with the development of this feature?

**Comment by vkWeb** [comment]
@Vitao18 Yeah sure. I am assigning this to you. You should read [our contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/master/CONTRIBUTING.md) if you haven't already and if you need any help, you can chat with our team on [our discord server](https://discordapp.com/invite/PXqYtEh). Happy coding :)

**Comment by allella** [comment]
@Zeko369  #349 exists as an issue in the UI.  Feel free to consolidate and close if these two issues can be combined into one.

**Comment by Zeko369** [comment]
I'll close this for now and move all the convo to the #349, we can later add more granular search options
