### ISSUE TITLE
can be good to have direct link for opening gitpod at readme (like at fcc project)

### ISSUE THREAD

**Issue by shootermv** [freeCodeCamp/chapter#1128]
**Describe the bug**
I think it can be good to have a direct link for opening gitpod at readme (like at free code camp project)
link should be: https://gitpod.io/#https://github.com/freeCodeCamp/chapter

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by gikf** [comment]
Closed with #1162
