### ISSUE TITLE
Chapter Ui Components

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/chapter#1143]
With [freeCodeCamp component](https://github.com/freeCodeCamp/freeCodeCamp/issues/44668) picking pace, Chakra-ui became obsolete. To adapt for the new library, we need to push the components we're currently using into it.

For this, we use [Storybook](https://storybook.js.org/) to document, test, and isolate the component, and [tailwind CSS](https://tailwindcss.com/) to style them.

Because this Chapter is in early stage, the research and development of the component isn't as intense as freeCodeCamp. But it's still a good idea to [check the freeCodeCamp wiki](https://contribute.freecodecamp.org/#/how-to-work-on-the-component-library) to get better perspective.

Components **must** follow [the web accessibility requirements](https://www.w3.org/WAI/standards-guidelines/wcag/)

The components are:

- [ ] [Modal (content - overlay - header - button - footer)](https://chakra-ui.com/docs/components/modal/usage) MVP

----

- [PageLayout](https://github.com/freeCodeCamp/chapter/blob/cb9c741530653f506c67cf971e397dbcc77c2b78/client/src/components/PageLayout) **This pagelayout is for research, we won't change it, just the Component**
- [ ] [Box](https://chakra-ui.com/docs/components/box/usage) (BoxProps)
- [ ] [Avatar](https://chakra-ui.com/docs/components/avatar/usage)
- [ ] [Stack](https://chakra-ui.com/docs/components/stack/usage)
- [ ] [Grid (item - ItemProps)](https://chakra-ui.com/docs/components/grid/usage) **MVP**

----

- [Form](https://github.com/freeCodeCamp/chapter/blob/cb9c741530653f506c67cf971e397dbcc77c2b78/client/src/components/Form)
- [ ] [Input](https://chakra-ui.com/docs/components/input/usage)
- [ ] [Form (label - control - error)](https://chakra-ui.com/docs/components/form-control/usage) **MVP**
- [ ] [Textarea](https://chakra-ui.com/docs/components/textarea/usage)

---

- [Chapter Card](https://github.com/freeCodeCamp/chapter/blob/cb9c741530653f506c67cf971e397dbcc77c2b78/client/src/components/ChapterCard.tsx)
- [ ] [Heading](https://chakra-ui.com/docs/components/heading/usage)
- [ ] [Center](https://chakra-ui.com/docs/components/center/usage)
- [ ] [Text](https://chakra-ui.com/docs/components/text/usage)
- [ ] [Color Mode](https://chakra-ui.com/docs/styled-system/color-mode#usecolormodevalue) (useColorModeValue)

---

- [Event Card](https://github.com/freeCodeCamp/chapter/blob/cb9c741530653f506c67cf971e397dbcc77c2b78/client/src/components/EventCard.tsx)
- [ ] [Flex](https://chakra-ui.com/docs/components/flex/usage) **MVP**
- [ ] [Spacer](https://chakra-ui.com/docs/components/flex/usage#using-the-spacer)

---
 to be optimized
- [login/register](https://github.com/freeCodeCamp/chapter/blob/cb9c741530653f506c67cf971e397dbcc77c2b78/client/src/components/LoginRegisterModal.tsx)
- [ ] Tag
- [ ] useBoolean
- [ ] UseDisclosureReturn
- [ ] Spinner
- [ ] useToast
- [ ] useDisclosure
- [ ] UseDisclosureReturn
- [ ] CircularProgress
- [ ] Link
- [ ] LinkButton
- [ ] Badge
- [ ] DataTable
- [ ] RadioGroup
- [ ] Radio
- [ ] Select
- [ ] LockIcon
- [ ] useConfirm
- [ ] ChakraProvider
- [ ] ConfirmContextProvider

---

* Exist in fcc library

- [x] Image  [Fcc Image](https://github.com/freeCodeCamp/freeCodeCamp/pull/44590)
- [x] Button [Fcc button](https://github.com/freeCodeCamp/freeCodeCamp/issues/45357)

### Research
* Find component usage in the project and list all the props being used.
* Compare usage and props with Chakra documentation.
* Find out if a component has a child component and how they work in regard to the props. 
* Find out which classes are applied by default.

### Development
* Create an interface for the props.
* Convert default styles to tailwind classes.
* Assign classes based on prop.
* Avoid creating a .css file.
* Add `children` prop, if needed.

**Comment by ojeytonwilliams** [comment]
A few quick thought on priorities.

As we discussed, the most useful components are the ones common to Chapter and /learn. 

Once those are done, I think it makes sense to look at the components that are public-facing, rather than administrator-facing.  It would be nice if the dashboard followed the style-guide, but it's not crucial.

Finally, looking at that list, I see a few things we may not need to change.  The layout components, for example, are probably good enough as is.

**Comment by hisnameispum** [comment]
I came cross this typescript-based UI library called [Mantine](https://mantine.dev/) and I heard it’s really good. Let me know what your opinions are. It might be helpful since the code base is mostly typescript.

**Comment by Sboonny** [comment]
@hisnameispum I see promising features and components, but we are trying to create our own library.

For it to be of use, we need to find a way to use it in chapter, add it to chaper, create component that is similar to said usage, and then delete the Mantine component.

This will be overtaxing for some, but I did take of it and when this issue closes, I will look deeper into it 👍💚

**Comment by Sboonny** [comment]
@Johnny01232003, @hisnameispum, I have talked with @ahmadabdolsaheb, if you need anything he is happy to answer your questions in the main repo too. https://github.com/freeCodeCamp/freeCodeCamp/issues/44668

There is something, that isn't mentioned in this issue. 

Creating a library require a team that specialize in that aspect, which we aren't, but we are creating something much smaller than usual library.

It's taxing and requires communication between each other more than skill because we are building something for specific scenarios, this will offer control and flexibility in doing whatever we want, but it's a big issue that require a lot of time and research.

**Comment by ojeytonwilliams** [comment]
Hey @huyenltnguyen, it's good to hear from you. And, yes, that would be a great help!

As the number of freeCodeCamp's client applications grows, the standalone package should be more and more useful. In the long run it should save a ton of time and painful debugging sessions.

**Comment by ojeytonwilliams** [comment]
@huyenltnguyen no, no, it's all good - those sound like good priorities. I'll definitely give you a shout if things change!

**Comment by ahmadabdolsaheb** [comment]
Just to clarify, we should go ahead with the current spec mentioned here: https://github.com/freeCodeCamp/freeCodeCamp/issues/44668
Once that is released, we will add the additional components that are specifically needed for chapter on the second sprint.

**Comment by Sboonny** [comment]
I have closed this, because it's casing confusion. Will reopen when freeCodeCamp ui components issue complete
