### ISSUE TITLE
colors of 'change' & 'close' buttons at change-role modal should be opposite

### ISSUE THREAD

**Issue by shootermv** [freeCodeCamp/chapter#1148]
### Describe the bug:
Currently 'close' button has a blue and 'change' is gray
![image](https://user-images.githubusercontent.com/1336862/176834579-2edc1d98-458a-419d-9e5e-c82d44ea10b2.png)
 I think it will be better to change colors to be opposite:
'close' -grey and 'change' is blue
May be even better to have 'green' color for 'change' button... 
### Tell us about your browser and operating system:
- Browser(s) name and version: 
- Operating System:

**Comment by gikf** [comment]
That's on me for using custom button for _Change_, instead of the default green button from `Modal` component with appropriate `formButtonText`.

**Comment by shootermv** [comment]
so, you think is better not to use custom button?

**Comment by gikf** [comment]
In this case I think so. Default one seem to fulfill all the needs, so unless there will arise requirements which it won't be able to match, no reason to not use default.

**Comment by shootermv** [comment]
replaced model code with following:
```
    <Modal
      modalProps={modalProps}
      title={title}
      formButtonText="Change"
      wrapChildren={(children) => (
        <form onSubmit={handleSubmit(confirmSubmit)}>{children}</form>
      )}
    >
  ...
    </Modal>
```
