### ISSUE TITLE
DB Schema - what if we tagged Events with tags.

### ISSUE THREAD

**Issue by rakneo** [freeCodeCamp/chapter#117]
I think what if we tagged events with tags so that similar events can be grouped automatically and these tags can be grouped and used as search filters.
users can select the tags that they are interested in and view the events which are related to the selected tag.

**Comment by allella** [comment]
@rakneo we had a video chat last night and for the MVP it was suggested to simply list all chapter events within an organization in chronological order. So, this idea may best be preserved by comparing it to the existing user stories in #84 and creating a new story if we don't have a story for it. I know we moved a story to "filter events" to #84 and your suggestion could be a flexible way to offer filtering events.

**Comment by allella** [comment]
@nik-john @francocorreasosa 

We have a schema suggestion, like above, which is not part of the MVP, since we moved "filter event" to #84.

I think in some cases we have add fields to the schema even before the feature is built out. Thoughts on if/when to add fields that are likely but not immediately necessary for the MVP?

**Comment by rakneo** [comment]
A tag is connected to many events and also a tag is grouped with other tags. we can use this tag structure to create dynamic filters.

**Comment by jacobbogers** [comment]
What is a  "tag", some the same as a github "topic"?

**Comment by allella** [comment]
This would be a tag in the context of the application. Events might be tagged with specific categories or other useful keywords related to user interests.

Those tags could be used to see lists within the front end applications showing only events which have those tags.

Again, this is likely not in the MVP (minimal viable product), but we do have it in #84 so I'm closing this issue and will link to this issue from #84.

**Comment by allella** [comment]
Feel free to re-open this issue if it make sense to add the relevant database fields.
