### ISSUE TITLE
No content displayed initially at dashboard page (except 'Admin dashboard' text...)

### ISSUE THREAD

**Issue by shootermv** [freeCodeCamp/chapter#1171]
### Describe the bug:

After logging in as admin (`foo@bar.com`)
And navigate to `dashboard` page.
No content displayed except 'Admin dashboard' text...
![image](https://user-images.githubusercontent.com/1336862/177032137-1b5fc378-6c33-400b-8b2e-f1c4987f2e17.png)

my suggestion: better to have first of tabs (`chapters`) selected

### Tell us about your browser and operating system:
- Browser(s) name and version: 
- Operating System:

**Comment by gikf** [comment]
My concern for picking any specific tab to be open by default, is that not everybody might have permission to view it.

**Comment by shootermv** [comment]
> My concern for picking any specific tab to be open by default, is that not everybody might have permission to view it.

"chapters" - is there any reason for not permit access to everybody to this tab?
