### ISSUE TITLE
Unclear Icon in the Homepage

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/chapter#1243]
There is a lock icon as shown in the picture for events, this isn't descriptive for people who see it. Our approach for private event inductive should be changed 

![image](https://user-images.githubusercontent.com/88248797/179562840-6e0b29f8-2d31-4471-b97d-984f189d08cf.png)

You can add `Invite only` text next to the `<LockIcon />` in here 

https://github.com/freeCodeCamp/chapter/blob/53e35409156efb60c7a98ec1cf24ac18c4dc39d6/client/src/components/EventCard.tsx#L33-L35

---

To get set up locally, take a look at our [contribution docs](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md). And, if you'd like to discuss more, you can head on over to [Discord](https://discord.gg/QbQd7BpaaH) and say hi. Or just comment here if you prefer.

**Comment by Nitya-Pasrija** [comment]
Hey, can u assign this issue to me? I believe I can fix this :)

**Comment by Sboonny** [comment]
You can open a pull request directly, after reading our guidelines.

 If you face any issues let us here or in our [server](https://discord.gg/QbQd7BpaaH), we will help you out

**Comment by zahyaah** [comment]
Hey @Sboonny 
Is this what I'm expected to do?
<img width="736" alt="image" src="https://user-images.githubusercontent.com/72253920/183466447-232732b3-68b7-4b38-9627-ecb22d828349.png">

**Comment by Sboonny** [comment]
@zahyaah yes, although I am expecting the styles to break after adding it, and it would be awesome it was sorted but that outside of Good first timer label. 

So as long as `Invite only` is added, I will close the issue
