### ISSUE TITLE
User should see themself highlighted always

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/chapter#1246]
It should be easy for the user to find themselves in rows of info while using the app

![image](https://user-images.githubusercontent.com/88248797/179564854-eb8953e3-0199-4684-a076-a18f724e061b.png)

I will post a link of the page file and hopefully how the feature is implemented.

**Comment by Sboonny** [comment]
@ojeytonwilliams I have looked into the below code, in `/src/modules/dashboard/Users/pages/UsersPage.tsx`

https://github.com/freeCodeCamp/chapter/blob/53e35409156efb60c7a98ec1cf24ac18c4dc39d6/client/src/modules/dashboard/Users/pages/UsersPage.tsx#L79-L105

I wanted to make sure before I change the label, it should be something like? or am I not noticing something?

```
if it is currentUser create 

<Text bg="something unique" data-cy="role">{name}</Text>

else 

<Text data-cy="role">{name}</Text>
```

**Comment by ojeytonwilliams** [comment]
That logic seems sound to me, so please go ahead with what you had planned.

**Comment by Nitya-Pasrija** [comment]
Can't we just change the role of "owner" to "OWNER"? 
It can be then distinguishable and also, these role changing options are available just to the owners so it shouldn't create much problems.

**Comment by Sboonny** [comment]
@Nitya-Pasrija That could work because normal users don't have the access to that part of dashboard. 

![image](https://user-images.githubusercontent.com/88248797/187371374-ce13e4f1-f5fc-40b4-a5cf-dbc6bf841dc5.png)

What was in my mind is creating the ability to define `currentUser` in client side, because after looking at `useMeQuery`, I don't think we have ability to define the current user.

Maybe changing the role and name to higher `font-weight` and the button colorTheme to `red` would be good enough for now.

**Comment by Nitya-Pasrija** [comment]
Can I start working on this issue then?

**Comment by Sboonny** [comment]
Sure go ahead 👍

---

To get set up locally, take a look at our [contribution docs](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md). And, if you'd like to discuss more, you can head on over to [Discord](https://discord.gg/QbQd7BpaaH) and say hi, or comment here if you prefer.

**Comment by Nitya-Pasrija** [comment]
@Sboonny Can you link the css file of this page here?

**Comment by Sboonny** [comment]
There isn't one yet, all of it is chakra.
