### ISSUE TITLE
As an attendee, I can RSVP "no" for an event

### ISSUE THREAD

**Issue by paschott** [freeCodeCamp/chapter#125]
As an attendee, I should be able to indicate that I will not be attending the event as well as indicating that I will be attending.  While that doesn't affect the overall counts, it does help show the organizer that people are responding to the e-mails. It may also show that someone who had previously responded as an attendee is now not going to attend.

The ultimate count of people attending should exclude the "not attending" responses.

**Comment by allella** [comment]
Thanks. This idea has been added and linked from the list at #84.  Closing since this can always be re-opened and this is not likely to make it into the MVP build.
