### ISSUE TITLE
Events should allow for longer descriptions

### ISSUE THREAD

**Issue by paschott** [freeCodeCamp/chapter#126]
As an organizer, I should be able to add a longer description to an event. The overall "meeting" may have a general purpose, but each event could have different details specific to that event.

E.g., if I'm running a PowerShell group, the overall purpose might be "For PowerShell users to learn together".  Each event might focus on a different topic, speaker, etc. They might even have different lengths if there's a special event.

**Comment by allella** [comment]
@paschott the https://github.com/freeCodeCamp/chapter/blob/master/data/ddl.sql has an events.description, so I'm assuming this suggestion is to ensure the description is built into the organizer interface and not that there's an issue on the current schema. Correct?

**Comment by paschott** [comment]
That sounds correct. I was looking at the ERD on the front page. That's probably out of date. This can be closed (or added to the organizer/display to-do if not already there).

**Comment by allella** [comment]
Yes, we've been debating which schema tool to use on #70 and now we just need to create a new one. Probably with DBeaver.io.

I think this is close enough to #102 that we can just expand, link from, and comment on that user story.
