### ISSUE TITLE
Allow descriptions for Sponsors

### ISSUE THREAD

**Issue by paschott** [freeCodeCamp/chapter#127]
As an organizer/sponsor, Chapter should allow sponsors to have some descriptive text in addition to their name and link. This would likely encourage users to click through to the sponsor's site instead of just seeing a name and URL.  It would also allow the sponsor to say something about themselves to indicate why the user might want to check out their site for more information.

**Comment by allella** [comment]
This would require a new sponsors.description field, or similar in the database.  I've added and linked this from #84 for future reference.

Closing this, but comments are welcome for when people review the list from #84 and click down to the suggested reason and comments.
