### ISSUE TITLE
Adding Margin bottom to EditEventPage

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/chapter#1273]
In `modules/dashboard/events/EditEventPage`

![events dashboard](https://user-images.githubusercontent.com/88248797/179920804-a4365f60-b9a0-4ba6-a938-485923670aab.png)

the buttons at the bottom have no margin button, we should add margin bottom to this page and similar ones. 

you can add margin bottom to `HStack` here, it use chakira style system https://chakra-ui.com/docs/styled-system/style-props

https://github.com/freeCodeCamp/chapter/blob/53e35409156efb60c7a98ec1cf24ac18c4dc39d6/client/src/modules/dashboard/Events/components/EventForm.tsx#L364-L380

---

To get set up locally, take a look at our [contribution docs](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md). And, if you'd like to discuss more, you can head on over to [Discord](https://discord.gg/QbQd7BpaaH) and say hi. Or just comment here if you prefer.

**Comment by gikf** [comment]
Done in #1276

**Comment by Sboonny** [comment]
Thank you 💚
