### ISSUE TITLE
ui/ux idea - after pressing "save" button at 'edit event' form, loader should be displayed inside button 

### ISSUE THREAD

**Issue by shootermv** [freeCodeCamp/chapter#1317]
### Describe the bug:
ui/ux idea - after pressing save button at 'edit event' form loader should be displayed inside button until request finished
also -better to disable all the inputs until request finished

### Tell us about your browser and operating system:
- Browser(s) name and version: 
- Operating System:

**Comment by gikf** [comment]
I just want to mention to not limit potential changes to a single form, but in case of making changes, try do them for all forms.
