### ISSUE TITLE
send email to attendees modal button colors is incorrect

### ISSUE THREAD

**Issue by shootermv** [freeCodeCamp/chapter#1370]
### Describe the bug:
 currently 'close' button has 'primary' color, and 'send' is gray. i think it better if colors will be opposite

![image](https://user-images.githubusercontent.com/1336862/183871041-bf98f130-3ead-424d-93ed-8253697e0b86.png)

### Tell us about your browser and operating system:
- Browser(s) name and version: 
- Operating System:

**Comment by Sboonny** [comment]
Here is the file https://github.com/freeCodeCamp/chapter/blob/b312312e85502d9277274ea71c825e0f69c56795/client/src/modules/dashboard/Events/components/SendEmailModal.tsx

---

To get set up locally, take a look at our [contribution docs](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md). And, if you'd like to discuss more, you can head on over to [Discord](https://discord.gg/QbQd7BpaaH) and say hi, or comment here if you prefer.
