### ISSUE TITLE
CSRF protection

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/chapter#1375]
NextJS does not have CSRF protection in by default, so we should add it.

Since we have an express backend, we can make use of csurf to generate a token and have the client send it back in a CSRF-Token header.

**Comment by shashimalcse** [comment]
I am happy to help with this issue

**Comment by gikf** [comment]
I've just noticed Apollo Server has option to enable csrf protection https://www.apollographql.com/docs/apollo-server/security/cors#preventing-cross-site-request-forgery-csrf. Would that be enough here?
