### ISSUE TITLE
Font scaling for different resolution screens (laptop/desktop specifically)

### ISSUE THREAD

**Issue by SeanRParker** [freeCodeCamp/chapter#156]
Any thoughts on how we'll handle supporting different resolution screens? In my experience, using `px` everywhere can result in vastly different UX for users on various desktop reolutions.

I propose we set different `font-size: **px` in each breakpoint in an `html` selector, then use `rem` units everywhere else. Does Material UI (or any other tool in the stack) have a built in way to handle this?

Are there other recommendations?

**Comment by vkWeb** [comment]
@SeanRParker We can handle them through media queries. Just for an example: we can set up a global font-size of 18px and use `rem` everywhere. And suppose when a user is using a device of width below 500px, we can alter the global font-size to 16px. This will reflect the change in all the components. 

How does that sound?

**Comment by kognise** [comment]
It's typically not a good idea to set a base font size in `px` for accessibility reasons - impaired users (and anyone who wants to) should be able to change their browser's base font size and have it be reflected in Chapter's site. One option is to set the base font size to `1.125 rem` on larger screens and `1 rem` on smaller screen, which will respond to font size changes while still giving the effect we want.

On a side note, I've been sick and unable to do anything programming-related. I'm finally recovering and I'll start popping up again.

**Comment by vkWeb** [comment]
@kognise Yes, I think you are right. It's good to see you back. I hope you recover soon :)

**Comment by SeanRParker** [comment]
@vkWeb That's the approach I have in mind.

@kognise Good point. I didn't know that. Hope you feel better soon.

**Comment by allella** [comment]
Is there anywhere we should link this conversation?

Is this discussion resolved, or shall we keep it open?

**Comment by nik-john** [comment]
@vkWeb @SeanRParker @kognise https://material-ui.com/customization/typography/#font-size

**Comment by vkWeb** [comment]
@nik-john The responsive font-sizes looks cool to me: https://material-ui.com/customization/typography/#responsive-font-sizes

By the way, in our prototype, we are using a different set of font-sizes. We are using the below colors and font-sizes for our prototype. It can be adjusted though.

Colors:
 Primary: #0a0a23 (gray 90)
Icon color: #d0d0d5

Font-sizes:
base body text: 16px
h1: 38px
h2: 28px
h3, event card title: 22px
small: 14px

**Comment by SeanRParker** [comment]
Looks like it’s built in to Material-UI.

So I’m going to close this issue.
