### ISSUE TITLE
Recording description creation date for tags

### ISSUE THREAD

**Issue by Rafi993** [freeCodeCamp/chapter#157]
The tags table seems to have only ID and Name column. But should we also record description and creation timestamp ?

**Comment by allella** [comment]
@vkWeb are there any conversations in the MVP mockups that would dictate if tags need a description?

I suppose we could add created_at and updated_at for consistency. It would allow for sorting tags by date, though I'm not sure there's a lot of use cases for that.

**Comment by vkWeb** [comment]
@allella @Rafi993  I don't think we need description & created_at/updated_at for tags. The tag itself should be self-explanatory and we don't need to record dates when these tags were updated. 

@timmyichen what do you think about this Tim?

**Comment by timmyichen** [comment]
Agreed with @vkWeb - @Rafi993, do you have a compelling use case for having a description and timestamp for each tag?

**Comment by allella** [comment]
I don't have a use-case unless there's a dedicated page for tags, but I don't think it would an MVP issue, so was checking with @vkWeb.

I don't think the created_at and updated_at are bad, for consistency will all other tables in the schema, but I also don't have a use case for those fields.

@Rafi993 if you want to create a pull request to add created_at and updated_at then we can see what others say about adding them.
