### ISSUE TITLE
MacOS Support

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/chapter#1571]
We used to require the docker platform be linux/amd64 for compatibility with Apple Silicon Mac, but this has recently started causing problems in CI. Ref: https://github.com/freeCodeCamp/chapter/pull/1570 and https://github.com/freeCodeCamp/chapter/actions/runs/3089347523/jobs/4996858566

It would be good if we could keep CI reliable and have Chapter work on Macs.

@c-ehrlich any idea how we can keep both running?

**Comment by allella** [comment]
I don't have any insight, but here's the [earlier conversation about Mac silicon and the node-alpine image being the problem, at least at that time](https://github.com/freeCodeCamp/chapter/issues/1045#issuecomment-1126693376).

**Comment by c-ehrlich** [comment]
Do you know why this is causing problems with the CI suddenly? Maybe it can be fixed on that side.

Another option would be to see if the node-alpine:18 (which will become LTS in a few weeks) removes the need to emulate on M1.

If neither of those, I think the only solution is to choose a different Node image that works on both architectures. Back when I originally implemented the M1 support I only compared node and node-alpine, maybe there is some other choice that works and isn't as bulky as the plain node image.

**Comment by c-ehrlich** [comment]
> @c-ehrlich the failing CI is something of a mystery, to be honest. Nothing obviously relevant has changed on the action front.
> 
> We can give node-alpine:18 a try, for sure. Could you see if #1575 works on your machine?

The container starts fine using the native image, but prisma queries fail with `Unknown PRISMA_QUERY_ENGINE_LIBRARY linux-arm64-openssl-undefined`. Seems like others have this problem also.

So I guess the only options are to figure out what's going on with the CI or use a different base image (I remember the plain node image working but it's huge, maybe something like slim or buster might work?)

full sample error:
```
app_1      | [1] Failed to validate user
app_1      | [1] PrismaClientInitializationError:
app_1      | [1] Invalid `prisma_1.prisma.chapters.findMany()` invocation in
app_1      | [1] /usr/chapter/server/src/controllers/Chapter/resolver.js:24:47
app_1      | [1]
app_1      | [1]   21 const inputs_1 = require("./inputs");
app_1      | [1]   22 let ChapterResolver = class ChapterResolver {
app_1      | [1]   23     async chapters() {
app_1      | [1] → 24         return await prisma_1.prisma.chapters.findMany(
app_1      | [1] Unknown PRISMA_QUERY_ENGINE_LIBRARY linux-arm64-openssl-undefined. Possible binaryTargets: darwin, darwin-arm64, debian-openssl-1.0.x, debian-openssl-1.1.x, debian-openssl-3.0.x, rhel-openssl-1.0.x, rhel-openssl-1.1.x, rhel-openssl-3.0.x, linux-arm64-openssl-1.1.x, linux-arm64-openssl-1.0.x, linux-arm64-openssl-3.0.x, linux-arm-openssl-1.1.x, linux-arm-openssl-1.0.x, linux-arm-openssl-3.0.x, linux-musl, linux-nixos, windows, freebsd11, freebsd12, freebsd13, openbsd, netbsd, arm, native or a path to the query engine library.
app_1      | [1] You may have to run prisma generate for your changes to take effect.
app_1      | [1]     at RequestHandler.handleRequestError (/usr/chapter/node_modules/@prisma/client/runtime/index.js:29915:13)
app_1      | [1]     at /usr/chapter/node_modules/@prisma/client/runtime/index.js:30336:25
app_1      | [1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
app_1      | [1]   clientVersion: '4.3.1',
app_1      | [1]   errorCode: undefined
app_1      | [1] }
```

**Comment by ojeytonwilliams** [comment]
@c-ehrlich that makes sense. I've made a PR to use the node:16 in development, but still deploy to node:16-alpine.  All being well, that should fix this.
