### ISSUE TITLE
Add "admin" as a user type

### ISSUE THREAD

**Issue by bernhard-hofmann** [freeCodeCamp/chapter#16]
I think it's important to consider the needs and desires of the people who are going to install and maintain Chapter. I'll start with a few suggestions:

As an admin

- I want easy installation to the cloud or my own server
- I want to easily upgrade or update my instances without losing my data.
- I want to easily control which features are available to my users

**Comment by Zeko369** [comment]
What do you think about deploy to heroku button? And a docker image for others?
Maybe a DigitalOcean template server?

**Comment by Utkarshbhimte** [comment]
We can also consider render.io as an option

**Comment by QuincyLarson** [comment]
@bernhard-hofmann Thanks for creating this issue. 

This user type is absolutely something we'll want create stories for. 

This won't be part of the MVP but it will follow shortly afterward.

**Comment by bernhard-hofmann** [comment]
Even if it doesn't make it into the MVP, I wanted to raise at least the point about our customers being able to update/upgrade their instances without losing data. So we'll be aware of breaking changes and how things like schema changes need to be handled to prevent (or at least minimise) data loss for updates. No doubt people will want to update their instances regularly for bug fixes, improvements, and possibly security reasons.

It's one of the reasons I was keen make a "pointless" website and database and get it deployed before we even start making features. It would ensure we have a means of deploying a Chapter and updating it before we've even built any features. Might serve as our demo of where we're at as well?

**Comment by QuincyLarson** [comment]
@bernhard-hofmann OK - thanks for the further detail. I agree. We do want some sort of Admin role who can access the global settings for the Chapter server. And yes - this should be part of our MVP since it will be necessary for anyone who's setting up a Chapter server. So I retract my earlier statement that this shouldn't be part of MVP.

I recommend using the role name "Admin" rather than maintainer, since that's a term more people will be familiar with.

**Comment by allella** [comment]
@chrismgonzalez we have some "as an admin" stories here which I assume should go into #84 

Quincy agreed, above, these are important post-MVP.

You okay changing "I want" to "I can" and copying these over to #84 and closing. It might be nice to link back to any issues that discussed a story at length. Or, put a "#84" link after the associated story/stories in the list.

**Comment by AryanJ-NYC** [comment]
I'm a bit confused as to the scope of this story. What is expected here?

Currently the there is no concept of "user types" in our models. Is it sufficient to add user types here and then add `admin` as one "user type"?

Or, do all of:

> I want easy installation to the cloud or my own server
> I want to easily upgrade or update my instances without losing my data.
> I want to easily control which features are available to my users

need to be implemented? I imagine not but would love to confirm.

**Comment by allella** [comment]
@AryanJ-NYC I suppose the roles need to be defined somewhere, so that's a start. #296 would then be a prerequisite for the API part of the admin related user stories. I'm going to post notes about the user_role table over there to get this conversation moving.

**Comment by allella** [comment]
@AryanJ-NYC #314 aims to provide more context for people on the roles and user vocabulary.

**Comment by Zeko369** [comment]
This was done in #335
