### ISSUE TITLE
Modifying a user's roles is laborious

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/chapter#1621]
This has always been the case, but it's made more explicit by https://github.com/freeCodeCamp/chapter/pull/1620 which differentiates between the instance roles `chapter_administrator` and `member`. Previously admins just made do with `member` instance permissions.

While we only have three distinct _user roles_  `instance owner`, `chapter administrator` and `member`, those are defined by their combination of instance and chapter roles:

| User   |      Instance      |  Chapter |
|----------|:-------------:|------:|
| member |  member | member (when they join) |
| admin |    chapter_administrator   |   administrator |
| owner | owner | nothing |
    
This means that an `owner` wishing to promote a `member` to a `chapter administrator` must change the user's roles twice and those changes have to be executed on two separate pages.  Since a `chapter_administrator` that is also an instance `member` is not a real role, it should not be possible to make that happen.  Instead the api should only allow changes between the three _user roles_, and the UI should reflect that.

**Comment by gikf** [comment]
The basic, messy way I imagined so far:

As chapter administrator needs to be connected to specific (or multiple chapters) it's logical to still set it from chapter users.

Chapter roles in UI:
- member
- administrator - resolver sets also instance role to chapter_administrator

Instance roles in UI:
- member
- owner
- chapter_administrator - It probably should be visible on the list, but should not be possible to be set directly as the instance role. Changing from it to other instance roles also can be spotty.

**Comment by ojeytonwilliams** [comment]
> As chapter administrator needs to be connected to specific (or multiple chapters) it's logical to still set it from chapter users.

Agreed. I can't think of a better place.

> chapter_administrator - It probably should be visible on the list...

I'm not sure about that. We, as maintainers, know that the chapter_administrator role is a necessary evil, but do users need to know or care about it?

**Comment by gikf** [comment]
That's a good question. I'm not too set on it. Currently it's a bit easier for me to think of them as visible, rather than looking for ways to keep them hidden.

**Comment by ojeytonwilliams** [comment]
Yeah, its awkward.  I could be missing something, but if we have the logic to handle making it impossible to change to a `chapter_administrator`, we're most of the way to making them hidden, too.  Probably... I've not thought too deeply about this yet!
