### ISSUE TITLE
Using useReducer for form data

### ISSUE THREAD

**Issue by Zeko369** [freeCodeCamp/chapter#163]
Have we discussed using `useReducer` instead of `useState` with an object for this? For this specific form it's OK, but if we had more fields maybe `useReducer` hook would make it more readable, since we're just implementing our own reducer later in the `handleChange`?

_Originally posted by @Zeko369 in https://github.com/freeCodeCamp/chapter/pull/140_

**Comment by papigers** [comment]
Wouldn't it better to just use Formik? No need to reinvent the wheel

**Comment by Zeko369** [comment]
I've heard that their hooks integration isn't the best, maybe some other form library that works better with hooks?

**Comment by Zeko369** [comment]
Or just plain useState/useReducer

**Comment by papigers** [comment]
@Zeko369 I never used Formik in the React Hooks era, so I can't say much about their hooks integration.
There's also [React Hook Form](https://react-hook-form.com/) which is relatively new and claims to be a far better option, but I don't have any personal experience with it.

**Comment by Zeko369** [comment]
That seems quite nice, what do others think? @timmyichen @joelrozen @vaibhavsingh97 @nik-john

**Comment by timmyichen** [comment]
react-hook-form seems nice and small.  haven't used it before but i'm down to try.

**Comment by Sonicrida** [comment]
My thought is to go with Formik since it's battle tested + what most people may be familiar with. It also has hooks now if those are needed.

**Comment by allella** [comment]
@timmyichen @joelrozen @vaibhavsingh97 @nik-john what say ye?

**Comment by joelrozen** [comment]
We have used formik internally on a lot of projects and it's great. I actually took part of my logic for this from our internal stuff and just rewrote to use without formik

**Comment by QuincyLarson** [comment]
We had a vote during our Nov 15 conference call, and there was a consensus that we should try React-hook-form first and if we don't like it, we can switch to Formik.
