### ISSUE TITLE
Leaving and unsubscribing from chapters

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/chapter#1631]
A user needs the option to leave chapters entirely, not simply unsubscribe from notifications.

As @allella pointed out in https://github.com/freeCodeCamp/chapter/pull/1593#discussion_r983040671 it currently says has the text 'member of the chapter' next to the 'Unsubscribe' button:

![image](https://user-images.githubusercontent.com/15801806/192969770-d199133d-f696-4247-9a88-6fc0ca8ec459.png)

This makes it appear that clicking 'Unsubscribe' will cause you to leave the group, but it does not - it just stops notifications.

TODO:
- [x] Create a public `leaveChapter` mutation
- [x] Add a 'Leave Chapter' button to chapters/[id] (client/src/modules/chapters/pages/chapterPage.tsx) to trigger that mutation
- [x] Improve the clarity of the UI so it's obvious that 'Unsubscribe' stops notifications while 'Leave Chapter' also removes you from every event you're currently attending.

**Comment by Sboonny** [comment]
---

To get set up locally, take a look at our [contribution docs](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md). And, if you'd like to discuss more, you can head on over to [Discord](https://discord.gg/QbQd7BpaaH) and say hi, or comment here if you prefer.

**Comment by gikf** [comment]
Points from original issue seems to be done. I've added PR to address uneven buttons. If there's something to follow here, new issue probably would be more appropriate.
