### ISSUE TITLE
How chapter subscription affects event subscription

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/chapter#1639]
Issue to discuss and iron out the if/how changing subscription to chapter should affect subscription to events from chapter.

#### Chapter subscription
- Subscribing to chapter doesn't change event subscriptions.
- Unsubscribing from chapter unsubscribes from all events in that chapter as well.
  - > Unsubscribing from this chapter will affect subscriptions of all existing events, and new events in the chapter.
  - > Unsubscribe Options
[Attend this event, but only turn off future notifications for this event]
Or, [stop receiving all notifications by unfollowing ${event.chapter.name}]
  - User can still subscribe (again, or first time) to individual events.

- Determines if user gets emails:
  - About new events.

#### Event subscription
- When RSVPing to an event, chapter subscription is used as initial event subscription. 
- Determines if user gets emails:
  - Event reminder.
  - When event is cancelled.
  - When event changes venue.
  - (administrators) When there's new RSVP.

If I missed something, feel free to edit it.

**Comment by allella** [comment]
Post MVP, I could see unsubscribing from a _chapter_ impacting if an _organizer_ can send a general announcement to the _members_.

I'm not sure unsubscribing from a _chapter_ should impact any existing reservations / RSVP.  The _member_ should be able to easily disable those messages from their email's footer.

Just as an example, some chapters may have a larger annual event that someone wants to attend, but they may not want to get all the other event notifications.  If they RSVP to an event and then unsubscribe to stop getting new event notes, or general announcements, then they may miss important RSVP notes.

If we're going to disable event notifications for RSVP'ed members, then we'd want to remind them and perhaps even do a query and list the future RSVPs so they can see what events they are being removed from.

**Comment by gikf** [comment]
I've added part that after unsubscribing from chapter, user still is able to subscribe to individual events, again or first time.

**Comment by ojeytonwilliams** [comment]
While I think it's probably fine for the MVP, we will be sending quite a lot of notifications. Reason being, Google Calendar sends notifications independently.  These will be sent for the initial invitation as well as any updates to the event, including cancellations.

I imagine users will either want one or the other. We can experiment with their API, but I haven't had chance to see if we can control notifications at the user level or if it's set for the entire event. I don't think this has to be addressed immediately, but it's something to consider.

Anyway, back to Chapter notifications.

> I'm not sure unsubscribing from a chapter should impact any existing reservations / RSVP. The member will be able to easily disable those event / RSVP-related messages from their email's footer.

How about this: if I unsubscribe from a chapter I should stop receiving notifications _about_ new events.  However, any events that I have already subscribed to would not be affected. When I unsubscribe from a chapter I should additionally be allowed to unsubscribe from those events, but it should not be automatic. 

> If we're going to disable event notifications for RSVP'ed members, then we'd want to remind them and perhaps even do a query and list the future RSVPs so they can see what event notifications they will stop receiving when they confirm.

How about informing people of the events that they'll be unsubscribing from if we offer them that choice?

**Comment by allella** [comment]
Yes, I think the combination of not removing an existing RSVP and warning them what unfollowing a _chapter_ is going to do would be good.

**Comment by ojeytonwilliams** [comment]
> When RSVPing to an event, chapter subscription is used as initial event subscription.

Just checking, but I think we want to keep this behaviour, right?  It seems particularly relevant for the MVP since members will be getting emails from Google Calendar (unless they choose to unsubscribe via their own Google Calendar settings).

**Comment by ojeytonwilliams** [comment]
Since this has stalled a little, I'll sum up my understanding of what we want to change:

- Unsubscribing from chapter unsubscribes from all events in that chapter as well. -> Unsubscribing from chapter leaves event subscriptions unchanged
- When RSVPing to an event, chapter subscription is used as initial event subscription. -> When RSVPing to an event, users should be subscribed automatically (Discussion in https://github.com/freeCodeCamp/chapter/pull/1593#discussion_r981624773)

Further customisation to be deferred.

**Comment by allella** [comment]
I'd be fine with the previous comment and we can add notices and form fields based on feedback in the real world use.
