### ISSUE TITLE
Switch default runs every time

### ISSUE THREAD

**Issue by DavidRinSE** [freeCodeCamp/chapter#164]
### Describe the bug:

Working on Learn Redux: Handle an Action in the Store

With a switch case statement the default runs every time which is not normal javascript behavior. 

Does not pass:
`let newState = {}
  switch(action.type){
    case 'LOGIN':
      newState = {login:true}
    default:
        newState = state
  }
  return newState
`
Passes:
`let newState = state
  switch(action.type){
    case 'LOGIN':
      newState = {login:true}
  }
  return newState`
### Tell us about your browser and operating system:
- Browser(s) name and version:  Firefox 70.0.1
- Operating System: macOS 10.14.6

**Comment by Zeko369** [comment]
This isn't a freeCodeCamp Redux Tutorial repo, but nevertheless I'll explain it here :)
When you have a switch case and unlike if/else it goes through all of the cases until it hits a break or a return statement, so your example
```
let newState = {};
switch (action.type) {
  case "LOGIN":
    newState = { login: true };
  case "LOGOUT":
    newState = { login: false };
  default:
    newState = state;
}
return newState;
```
This would set `newState` to `{login: true}`, then to `{login: false}` and then to the original state object
What you want here is a break or return
```
let newState = {};
switch (action.type) {
  case "LOGIN":
    newState = { login: true };
    break
  case "LOGOUT":
    newState = { login: false };
    break
  default:
    newState = state;
}
return newState;
```
This would set `newState` to `{login: true}` and then finish with a switch statement

You could also use ES6 spread syntax and do this
```
function reducer(state, action) {
  switch (action.type) {
    case "LOGIN":
      return {...state, login: true };
    case "LOGOUT":
      return {...state, login: false };
    default:
      return state
  }
}
```

**Comment by DavidRinSE** [comment]
My bad I should have known that I was caught up in the new redux info. And I just googled freeCodeCamp issue report real quick and this came up but I see the structure now. Thanks!
