### ISSUE TITLE
Question: Is node-typescript necessary?

### ISSUE THREAD

**Issue by Sonicrida** [freeCodeCamp/chapter#165]
I was looking through the codebase and trying to run the application locally on my system. I notice that installing packages fail because the Chapter engine is set to node version 10 but one package we are using, `node-typescript` wants node version **0.8.x**. 

https://www.npmjs.com/package/node-typescript

This package seems to be 7 years old and the github repo is no longer available. Is this something that we are using? Can I remove it? I am not familiar with node + typescript but from what I can tell, I don't see it being used anywhere.

**Comment by Zeko369** [comment]
I'm pretty sure it was added by mistake and that we dont use it? That's from the express/next init PR. Pinging @timmyichen from that PR

**Comment by timmyichen** [comment]
ah yes we can probably remove it; i may have added it by accident 🙃

**Comment by Zeko369** [comment]
@Sonicrida you can go ahead and create a PR for that

**Comment by Sonicrida** [comment]
Will do! Thanks!
