### ISSUE TITLE
Members of the chapter shouldn't get notified by the creation of an event in the past

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/chapter#1661]
### Describe the feature:

As discussed in Discord, owner may want to create events for documentation purposes, but creating this events may result in notification been sent to the chapter members. 

We need some flag which stops the events, that were created before (`new Date()`), from using our notification system

**Comment by ojeytonwilliams** [comment]
Re-opening because Google calendar notifications will still be sent if the event is in the past: https://github.com/freeCodeCamp/chapter/pull/1815#discussion_r1017813615
