### ISSUE TITLE
Change Discord Link

### ISSUE THREAD

**Issue by timmyichen** [freeCodeCamp/chapter#167]
A simple PR if anyone has the time! :)

We added more structure to the Discord channels - the current invite link sends people to #general, whereas this new link sends people to newly created #welcome channel:

https://discord.gg/PXqYtEh

It would be great if we could replace all old discord links with the new one above.

**Comment by raufabr** [comment]
Hi @timmyichen can I pick this up please? Will need a bit of guidance for my first contribution in this project.

**Comment by vkWeb** [comment]
@raufabr Amazing. Feel free to work on this. I have assigned it to you. You should read [our contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/master/CONTRIBUTING.md) to get started. Thanks and welcome to Chapter :)

**Comment by raufabr** [comment]
Hi, I've created a PR for this :relaxed:
