### ISSUE TITLE
Logo for the chapter page and refactor the image_url field

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/chapter#1707]
Currently, the image_url act as banner, knowing that chapter are non-profit organizations, they may need logo as well.

This will make us change three things 

- [x] refactor image_url field in chapter to banner_url
- [x] create logo_url field 
- [ ] use logo_url to display chapter logo

----

(Optional) 

Images can be any height and any width, should we optimize them using services like Amazon s3 https://aws.amazon.com/blogs/compute/resize-images-on-the-fly-with-amazon-s3-aws-lambda-and-amazon-api-gateway/

Or limit the size the user can submit?

**Comment by ojeytonwilliams** [comment]
There's no need to host images for the MVP. It's fine to use links for now.

**Comment by Sboonny** [comment]
should the logo field be added for mvp?

**Comment by ojeytonwilliams** [comment]
Absolutely.  As long as not too much work is involved, small tweaks like this seem fine to me.
