### ISSUE TITLE
As an admin I can add a Google Analytics ID

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/chapter#171]

**Comment by allella** [comment]
#44 holds some of the earlier conversation.

**Comment by Zeko369** [comment]
Will this be done per chapter or per instance?

**Comment by allella** [comment]
It seems this would depend on the _organization_. For the MVP we may have talked about just 1 at the _organization_ level.

For post-MVP, perhaps both, where the _organization_ can track stats on every page and an individual Chapter can provide their own code to track only their own pages.

On #44  we talked about the ability to drop in a Javascript snippet.  Of course, there may be some security issues with that approach, so limiting the tracking to specific services and allowing people to drop in just their account ID at the _organization_ or _chapter_ levels might be the way to start.

**Comment by QuincyLarson** [comment]
I agree we should just do this at the organization level. The organizer can always manually add other people in Google Analytics if they need to.

**Comment by Zeko369** [comment]
To continue the note from the meeting where we said that the easiest way for people to setup the email credentials would be to just have them as a .env var.

Since the MVP will mainly be hosted on Heroku it's dead simple to set them up in Heroku, so maybe we could just have a `GOOGLE_ANALYTICS_ID` as an env variable so that could make things simpler for now

**Comment by allella** [comment]
Sounds good.

Since we're talking about post-MVP allowing for individual Chapters to track their own internal pages would we want to qualify this env variable a bit, like GOOGLE_ANALYTICS_ID_ORG ?

**Comment by Zeko369** [comment]
We could do something like

```javascript
const id = process.env[`GOOGLE_ANALYTICS_ID_${CHAPTER_ID}`] || process.env.GOOGLE_ANALYTICS_ID;

if(id) {
  render GA(id);
} 
```

**Comment by allella** [comment]
I think when we get to the point of having _chapter_-specific tracking that we'd want to execute both codes.  The organization will likely still want to see the overall stats, while the chapter would possibly have their own Analytics account that's independent of the organizations?

So, that snippet reasonable and we can figure the right way to execute / track the interior pages against two Analytics accounts when the time comes.

Thanks

**Comment by Zeko369** [comment]
Yeah we can also do that. Also if we're doing that we can add chapter admins ability to do that from the dashboard (we can easily add that to the DB).
I just think that it would be a lot easier for people setting it up to just throw everything at Heroku and have everything work from there, and not have to fiddle around our UI.

https://support.google.com/analytics/answer/1032400?hl=en

**Comment by QuincyLarson** [comment]
For our MVP, we should just use a single Google Analytics account for the entire instance, and add it as an environment variable in Heroku. We can leave this as a blank default environment variable in Heroku so people remember to configure it.
