### ISSUE TITLE
As a user, I can download my personal information from Chapter

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/chapter#1713]
Per https://gdpr-info.eu/art-15-gdpr/ a user has the right to access any of their personal information that we store.  Precisely what constitutes personal information is a bit subjective, so we should err on the side of inclusion.  

With that in mind I think we want data that is connected to their entry in the the `users` table.  Aside from the entry itself we'd want: the details of chapters they are in, their role in these chapters, the same for events, their ban status, and finally their instance_roles. I think that covers it, but let me know if I've missed something.

On the UX side, all we need is a button on their profile to download the data.  The data can be a JSON string.

TODO:
- [x] create a resolver that returns the user's data: https://github.com/freeCodeCamp/chapter/pull/1756
- [ ] create a button to fetch and download that data

**Comment by allella** [comment]
Yeah, I guess the tables with "user" in the name and the things they join to.

I could see session potentially having some partial personal info if cookies are stored there. 

Is there anything in the database we'd see as being a security risk?  Being that it's an OSS project, the schema and roles and such are no secret.  I'm just wondering if there are any tokens or session related things which could be potentially harmful and worth excluding.

**Comment by allella** [comment]
I posted an example of a popular US site's download interface at
https://github.com/freeCodeCamp/chapter/issues/263#issuecomment-1270169105

This uses a series of .csv files that are zipped up, which is likely more work than needed for MVP. I think I dumped fCC's data and it was a JSON blob that's sort of hard to read for the lay person, so I guess the format, like CSVs vs JSON, isn't decreeed?

**Comment by ojeytonwilliams** [comment]
> I'm just wondering if there are any tokens or session related things which could be potentially harmful and worth excluding.

There are a few things that we must not leak.  

- Email addresses of anyone other than the user making the request
- The session id (just to be on the safe side)
- Anything in _google_tokens_

> I think I dumped fCC's data and it was a JSON blob that's sort of hard to read for the lay person, so I guess the format, like CSVs vs JSON, isn't decreed?

I don't believe so, but if we find out otherwise we can always come up with a nice approach.
