### ISSUE TITLE
Test issue to try and add contributors

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/chapter#172]
@all-contributors please add @ceciliaconsta3 for codebase contributions

**Comment by QuincyLarson** [comment]
@all-contributors please add @ceciliaconsta3 for codebase contributions

**Comment by QuincyLarson** [comment]
@all-contributors please add @nik-john for code

**Comment by nik-john** [comment]
@all-contributors please add @ceciliaconsta3 for codebase contributions

**Comment by nik-john** [comment]
@all-contributors please add @ceciliaconsta3 for idea

**Comment by vkWeb** [comment]
@all-contributors please add @madaleneaza-design for design

**Comment by vkWeb** [comment]
@all-contributors please add @vkWeb for design
@all-contributors please add @seanrparker for design

**Comment by vkWeb** [comment]
@all-contributors please add @vkWeb for design

**Comment by vkWeb** [comment]
@all-contributors please add @SeanRParker for design

**Comment by vkWeb** [comment]
@all-contributors please add @finisher1017 for design doc

**Comment by vkWeb** [comment]
@all-contributors please add @xarielx for doc

**Comment by vkWeb** [comment]
I have added all the design-related people to the list and also resolved all the conflicting contributors. We can add more contributors as we progress. Closing this for now. 

@nik-john I think for long-term we should consider creating a separate file for contributors. But it's not in high priority right now. So we can do it anytime in the future.
