### ISSUE TITLE
Add links that let users join chapters and attend events

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/chapter#1721]
Currently, if I follow a link like http://localhost:3000/events/22?emaillink=true I will see a modal asking me to confirm that would like to join the event.

If would be helpful for administrators to be able to easily share this after creating a new event.  For example, the dashboard for that event could have a share button that shows the link and gives the user an option to copy it to their clipboard.

Similarly, if they want to invite people to join their Chapter it would be helpful to be able to do the same sort of thing from the Chapter's dashboard.

Nice to have:

Logged out users should be sent away to log in and then brought back to the shared link if they consent.

**Comment by Sboonny** [comment]
I have thought of this, but i am wondering how to address seo aspect like, I want it to be similar to how freeCodeCamp news articles are shared.🤔

Well I need to start with something to get unstuck anyway 👍
