### ISSUE TITLE
Missing event images should be handled gracefully

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/chapter#1722]
![image](https://user-images.githubusercontent.com/15801806/195888858-b747cb69-8054-41a6-b5f7-718a717b0d6c.png)

does not look great.

@Sboonny apologies if you've already addressed this in one of your open PRs!  I'll get to them soon.

**Comment by Sboonny** [comment]
I have updated the default images, but I don't think I have started on this yet.

Thank you for the reminder 👍
