### ISSUE TITLE
The last owner should not be able to demote themselves

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/chapter#1735]
### Discuss your ideas or share your views: 

This doesn't seem vital for the MVP, but it seems like it would be helpful if we made sure there was always at least one instance owner for an instance.  Otherwise the instance cannot be managed properly.

Ideally the db request should fail if it would reduce the number of instance owners to zero.

Is this overly cautious?  As long as the instance owner can access the db, they can always reinstate themselves.

**Comment by allella** [comment]
Seems reasonable fro post-MVP.

If someone has a good reason to completely delete all owners, then they could also just go directly into the database and start changing records. Though, I can't imagine why that would be needed.

**Comment by ojeytonwilliams** [comment]
Neither can I, honestly.  It seems far more likely that someone demotes themselves accidentally.
