### ISSUE TITLE
Brief flash of fallback image

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/chapter#1755]
### Describe the bug:

The fallback image (with the dog) shows while the main image is loading:

![SurpriseDog](https://user-images.githubusercontent.com/15801806/197172726-d7e445e4-ea58-440a-94d8-590457b899ff.gif)

Ideally the fallback should only show if the image fails to load.  Also, cute though the dog is, it's probably better to fallback to something boring like an empty space or something abstract.

**Comment by allella** [comment]
I'd agree to nix the default image. If an img height= and width= are specified then the browsers should allocate that space and insert the image as it loads, avoiding any rendering shuffling on the page.

**Comment by ojeytonwilliams** [comment]
Right.  I think that's all we really need.

**Comment by Sboonny** [comment]
> I'd agree to nix the default image. If an img height= and width= are specified then the browsers should allocate that space and insert the image as it loads, avoiding any rendering shuffling on the page.

Because I am slightly confused, this mean no lazy loading, right? at least for ChapterPage

what does nix image mean? what I found is this https://github.com/nix-community/nixos-generators

**Comment by allella** [comment]
"nix" is a word the means cancel / reject.

I was agreeing we don't need a preload image.  If the image height and width are set the browser will hold the space so the screen rending doesn't jump around.

Setting the image height and width should also help avoid rendering issues when lazy loading images, so I don't see that you'd have to remove any lazy loading.

Does that clear things up? Or, am I missing something that's not likely to work well?
