### ISSUE TITLE
Authenticated graqhql queries fail from Apollo studio

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/chapter#1757]
Since we authenticate via a session cookie, Apollo Studio Explorer is not able to request anything that requires the user to be logged in.  

It's possible to work around this by setting up a https reverse proxy (Caddy is reasonably easy to configure) and configuring the express server to accept secure, Same-Site: none cookies

```js
  app.set('trust proxy', true);
  app.use(cors(corsOptions));
  app.use(
    cookieSession({
      secret: process.env.SESSION_SECRET,
      domain: process.env.COOKIE_DOMAIN,
      // One week:
      maxAge: 1000 * 60 * 60 * 24 * 7,
      sameSite: 'none',
      secure: true,
    }),
  )
 ```

...and changing the NEXT_PUBLIC_SERVER_URL and CLIENT_LOCATION to point to the proxied addresses.

However, this is a pain to configure just to use the explorer.

Is there a nice way to enable developers to smoothly switch between http and https?

**Comment by Sboonny** [comment]
What is the need to set up Apollo client, and move away from none cookies?

**Comment by ojeytonwilliams** [comment]
> What is the need to set up Apollo client, and move away from none cookies?

Could you elaborate?  I don't think the client is relevant, here - I just want Apollo Studio Explorer to be able to query the Apollo Server.

**Comment by Sboonny** [comment]
> Could you elaborate?

Wanted to know what is happening, because I didn't understand the issue. We want an easy way to set this up https://www.apollographql.com/docs/graphos/explorer/connecting-authenticating#cookies

**Comment by atosh502** [comment]
Hi @ojeytonwilliams  I tried using https://github.com/freeCodeCamp/chapter/issues/1757#issue-1418500757 approach but I couldn't make it work with Apollo Studio.

However, I was able to make authenticated queries with Postman and Postman Interceptor for Chrome. This doesn't require any changes to cors or cookie settings on our API server code. 

Steps:
* [Install](https://www.postman.com/downloads/) and connect Postman to the local graphql server.
  * Follow the steps from this section: [Sending GraphQL queries in the request body](https://learning.postman.com/docs/sending-requests/graphql/graphql/#using-postmans-built-in-support-for-graphql) and use our local server url: [http://localhost:5000/graphql](http://localhost:5000/graphql) as URL endpoint. 

* [Install](https://chrome.google.com/webstore/detail/postman-interceptor/aicmkgpgakddgnaphhhpliifpcfhicfo?hl=en) Postman Interceptor for Chrome
  * Go through the section [Syncing cookies with Postman Interceptor](https://learning.postman.com/docs/sending-requests/capturing-request-data/syncing-cookies/#syncing-cookies-with-postman-interceptor) and add `localhost` as the domain.
* Next login to our frontend(in Chrome) as an owner at [http://localhost:3000](http://localhost:3000). The cookies set in the browser will be captured by Postman. 
![image](https://user-images.githubusercontent.com/19350071/217604346-3950044b-747e-4f85-b84e-46b3999a4083.png)
* Next goto Postman and run the `dashboardEvents` query (which should not be available to unauthenticated users). The data is returned in the body and the relevant cookies are sent along with the request.
![image](https://user-images.githubusercontent.com/19350071/217605283-53af3d7f-54ec-43ff-bffb-473d1cdad3af.png)
![image](https://user-images.githubusercontent.com/19350071/217606599-bb7990ab-22cd-487d-95af-6f3bc24fc299.png)

* The cookies will be automatically removed once we logout or login as a test user, and access to `dashboardEvents` query will then be denied.

Relevant links: 
* [Querying with GraphQL](https://learning.postman.com/docs/sending-requests/graphql/graphql/)
* [Capturing and syncing cookies](https://learning.postman.com/docs/sending-requests/capturing-request-data/syncing-cookies/)

**Comment by ojeytonwilliams** [comment]
Thanks for investigating this, but I feel a bit silly. We already have a dev environment where https is enabled by default: GitPod.  I really should have thought of this before. Sorry!

To get access to the explorer, all you have to change is to use

```
      sameSite: 'none',
      secure: true,
```
for the `cookieSession` config.

If we update the docs with those instructions, I think that's good enough.

What do you think?

**Comment by atosh502** [comment]
Yep, I think that's okay.

I tried the following settings in my Gitpod instance to authenticate requests: 

* Changed the `cookieSession` config as below
```diff
- sameSite: 'lax',
+ sameSite: isDev() ? 'none' : 'lax',
- secure: !isDev(),
+ secure: true,
```
* Enabled the `Include cookies` option from the `Connection Settings`. 
* In order to set make authenticated requests 
  * I added a preflight login script 
    ```ts
    await explorer.fetch('https://5000-freecodecamp-chapter-t2bsgvpsyk1.ws-us86.gitpod.io/login', {
      method: 'POST',
      headers: {
        Authorization: 'Bearer ignored'
      },
      credentials: 'include',
      body: JSON.stringify({}),
    })
    ```
  * In order to make pre-flight requests succeed, I had to add a the URL to `allowedOrigins` in `corsOptions`
    ```diff
    - const allowedOrigins = isDev() ? [clientLocation, 'https://studio.apollographql.com'] : clientLocation;
    + const allowedOrigins = isDev() ? [clientLocation, 'https://studio.apollographql.com', 'https://preflight-request.apollographql.com'] : clientLocation;
    ```
* After this the requests were successful.

Let me know if I missed any steps or if there's an easier way to do this. 

Also, please indicate where should I add these configs/settings in the docs. I was thinking it might go under the [Frequently Asked Questions](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md#frequently-asked-questions) section.

**Comment by ojeytonwilliams** [comment]
I followed basically the same steps as you, the difference being that I logged in myself to set the cookies. That seemed to be enough: I could make queries like

```
  dashboardChapters {
    creator_id
    description
  }
```
as an instance owner, but if I logged in as a member then I got the "Access denied!" messages I was expecting.

If that works and makes sense to you, please do add these instructions to the docs. And, yes, the FAQ section would be a good place for them.

**Comment by atosh502** [comment]
> the difference being that I logged in myself to set the cookies

Just to confirm you meant logging in to the Chapter frontend, right? instead of directly calling the `/login` endpoint in preflight script.

**Comment by ojeytonwilliams** [comment]
> Just to confirm you meant logging in to the Chapter frontend, right? instead of directly calling the /login endpoint in preflight script.

I did, yes.  It just seems like the easiest workflow to me.
