### ISSUE TITLE
Calendar integration - chapters, events created before authentication

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/chapter#1764]
### Discuss your ideas or share your views: 
Integration with google calendar works for chapters and events created after the authentication. Calendar is created on chapter creation and calendar events on event creation. This rises a potential question - what with chapters and events created before instance is authenticated?

- Add manual creation of calendar and calendar events, via chapter and/or event dashboard?
- Add automatic creation of calendar and calendar events for the existing chapters and events, when instance gets authenticated?

**Comment by ojeytonwilliams** [comment]
I slightly prefer the manual approach. Purely because it might be surprising to have a bunch of calendars and events appear.

As long as we make it obvious that a) the calendars are not automatically created and b) how to trigger their creation, it should be a reasonable UX.
