### ISSUE TITLE
Custom avatar not displayed on events page

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/chapter#1798]
### Describe the bug:
Custom profile picture (avatar) is not displayed on the events page `/events/{id}` on the list of _RSVPs_ or _Waitlist_. Instead is used the default avatar.

**Comment by Myrfion** [comment]
Hello, could I have it assigned on me?

**Comment by gikf** [comment]
Hey @Myrfion, we typically don't assign issues to specific person. Instead, we accept the first pull request that comprehensively solves the issue.

**Comment by og118** [comment]
Currently, the chakra UI is rendering the initials of the firstname and lastname in the avatar box. What exactly do you mean the by custom avatar? Should an external package be used for this?

**Comment by gikf** [comment]
In profile (`/profile`) user can set url to _profile picture_. It's then used, in place of the default avatar with initials, in the header.
https://github.com/freeCodeCamp/chapter/blob/51e79d03904b1b13331571b705136615a3e7c1c2/client/src/components/PageLayout/Header.tsx#L100-L105
Once that happen other places, having avatar also should use the picture instead of default chakra's avatar, currently that's list of RSVPs and Waitlist on the event page.

**Comment by og118** [comment]
I've raised a PR fixing this issue. Please review it and do let me know if any changes are required
