### ISSUE TITLE
Members should be able to see their own email address on their profile

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/chapter#1853]
Own email address should be displayed in the user profile.

**Comment by SureshKuchana** [comment]
Hi @gikf, I can see this issue is till open, can I take this up?

**Comment by SureshKuchana** [comment]
And also do we need to show as an editable field or only read-only field for email?

**Comment by gikf** [comment]
@SureshKuchana, yes, it is open.

Just email displayed as text at this time.

Don't hesitate to ask if you'd have any questions.

**Comment by SureshKuchana** [comment]
Sure @gikf

**Comment by SureshKuchana** [comment]
Hi @gikf, I have done with my changes & pushed in my local branch [fix/display-email-in-user-profile](https://github.com/SureshKuchana/chapter/tree/fix/display-email-in-user-profile).
I have included the https://github.com/freeCodeCamp/chapter/blob/main/client/graphql.schema.json file, Is it OK to include this file?

**Comment by gikf** [comment]
@SureshKuchana did you use `npm run gen`? Usually changes in `graphql.schema.json` are accompanied by changes in `client/src/generated/graphql.tsx`.

Either way, if `npm run gen` is generating files with changes, it's not only okay to include them in PR, but it's necessary.

**Comment by SureshKuchana** [comment]
Ohh OK. I will include **client/src/generated/graphql.tsx**. Thanks, @gikf

**Comment by SureshKuchana** [comment]
@gikf I have updated code, including the graphql.tsx file. Please look at the [PR](https://github.com/freeCodeCamp/chapter/pull/1890)
