### ISSUE TITLE
When you cancel your RSVP you should receive a confirmation email once that has succeeded

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/chapter#1854]
Canceling Rsvp should send confirmation email, depending on the `subscribed` status for the event.

**Comment by smiller1188** [comment]
Hi! I would like to work on this. Can I get started?

**Comment by smiller1188** [comment]
Hi! I would really like to help contribute. Is anyone working on this issue? Thanks

**Comment by gikf** [comment]
@smiller1188 it doesn't look like it. Let us know if you have any questions or encounter any troubles.

**Comment by allella** [comment]
This is probably related to https://github.com/freeCodeCamp/chapter/pull/1845

**Comment by Sboonny** [comment]
I can see this being spammy, I think it's best to add the ability to opt out from it before/with this feature.

**Comment by gikf** [comment]
How often user will be cancelling their rsvp?

**Comment by Sboonny** [comment]
Sorry for not answer the question below.

> How often user will be cancelling their rsvp?

I don't think normal user will do that often, but I can see administrator cancel RSVP Event multiple times. As they will create multiple Events but don't need to attend them

**Comment by gikf** [comment]
Ah, that makes sense. Another argument for not rsvping automatically the event creator.
