### ISSUE TITLE
Event statuses in `/dashboard/events/` are not consistent with statuses on `EventCard`

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/chapter#1881]
[EventCard](https://github.com/freeCodeCamp/chapter/blob/main/client/src/components/EventCard.tsx) is defining status of the event in slightly more precise manner than the [EventsPage](
https://github.com/freeCodeCamp/chapter/blob/main/client/src/modules/dashboard/Events/pages/EventsPage.tsx) in dashboard. Event dashboard should display the same statuses as the event card.

**Comment by Sboonny** [comment]
I took care of this issue coincidently, because I wanted to test how easy is it to DRY the code with function in it. The answer was it wasn't easy to DRY it and the code was getting too smart, so I hard coded it 😅
