### ISSUE TITLE
Welcoming the user message is cramped and need some spacing

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/chapter#1884]
### Describe the bug:

The welcoming message when someone logs in is cramped, it can use some spacing to look better. 

The current looks

![image](https://user-images.githubusercontent.com/88248797/201352290-352c650b-bad9-4d71-a3b9-b82ef360a09d.png)

The desired looks 

![image](https://user-images.githubusercontent.com/88248797/201352201-bef9a017-d13c-44f7-abb4-33a1afbed471.png)

You can change the file here

https://github.com/freeCodeCamp/chapter/blob/de6fd0842b211ce2be4b3a2d351d7d8e9f86f68f/client/src/modules/home/index.tsx

---

---

To get set up locally, take a look at our [contribution docs](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md). And, if you'd like to discuss more, you can head on over to [Discord](https://discord.gg/QbQd7BpaaH) and say hi, or comment here if you prefer.

**Comment by codeX1616** [comment]
Hello @Sboonny I would like to work on this issue. Please assign it to me. Thanks!

**Comment by Sboonny** [comment]
Feel free to open a pull request after reading the contribution guide, we don't give assignmentd

**Comment by codeX1616** [comment]
Got it, thanks!

**Comment by codeX1616** [comment]
Hello @Sboonny, Could I get the db creds for any DB remote server which I can update in .env file?

**Comment by Sboonny** [comment]
There isn't one that I am aware of, please follow the documentation of PostgreSQL, it shouldn't be hard to spin one up https://www.postgresql.org/docs/
