### ISSUE TITLE
Don't Rsvp event creator when event is created

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/chapter#1887]
### Discuss your ideas or share your views: 
There's a TODO in the events resolver to give ability to not Rsvp automatically event creator. What about simply not Rsvping event creator when event is created?

- This would be similar to how creating chapter doesn't add creator to it. 
- Marginally simplifies `createEvent`.
- There's case (it can be called bug) when instance owner can, without `chapter_user` entry, create event and gets auto Rsvped to the event. Still without `chapter_user`. Problems due to that haven't revealed themselves yet.

**Comment by Sboonny** [comment]
> What about simply not Rsvping event creator when event is created?

There are multiple good points about this idea, fewer noises for the event creator and usually the first event is created after creating venue and chapter, so they are used to a rhythm of not be included in chapter and venue, at their first experiences.

**Comment by gikf** [comment]
Addressed in #2078.

Event creator has now option to not attend when creating event.
