### ISSUE TITLE
Dates missing from event pages

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/chapter#1897]
If you go to the home page, you will see information about when the date starts:
![image](https://user-images.githubusercontent.com/15801806/201684065-eed60ce5-8de9-45c1-981f-f9a5b9b5b6a2.png)

however, there is no information on the event page itself, e.g.. http://localhost:3000/events/1, or the dashboard for that event, e.g. http://localhost:3000/dashboard/events/1

Both pages should should when the event starts and when it ends.

**Comment by Sboonny** [comment]
Do we want it similar to the card logic, or should we keep it simple and add generic 

> Start at: sometime in the future
> End at: sometime in the future
