### ISSUE TITLE
Add a contributors guide

### ISSUE THREAD

**Issue by bernhard-hofmann** [freeCodeCamp/chapter#19]
Please add guidelines and requirements for contributors.

**Comment by chrismgonzalez** [comment]
I'm happy to lead the charge on this, but we definitely need to get a 0.1.0 version of this out in the open at least in its most basic form.  I propose we take the FCC main repo guide and skim it down to feet the needs of this repo.

**Comment by allella** [comment]
Can we add this as a note to https://github.com/freeCodeCamp/chapter/issues/12 and close this, since this seems to be a bulletpoint of what's already there?

**Comment by allella** [comment]
@bernhard-hofmann You mind closing this since Chris added it to #12  ?

Thanks

**Comment by allella** [comment]
Github also shares this link at the top of the main Issues page
https://opensource.guide/
