### ISSUE TITLE
Calendar integration and auto subscribe to event on rsvp

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/chapter#1937]
When rsvping to an event, by default user is subscribed to it. When instance is authenticated to the Calendar api, this will mean user email is automatically passed to the calendar event as an attendee.

It might be worth to consider changing the default behavior and/or include explicit information that email will be used in such way.

**Comment by Sboonny** [comment]
The amount of functionality linked to RSVP is confusing 😵, should we put this information on policy and the ability to opt out of this in profile? 🤔

**Comment by ojeytonwilliams** [comment]
This sounds like it would be worth adding to the policy.  Adding the ability to opt out sounds reasonable, but that should be post MVP.
