### ISSUE TITLE
Chapter dashboard - links to events

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/chapter#1941]
When in specific chapter dashboard (`/dashboard/chapter/{id}`), there's list with events from this chapter. Links to the events are leading to public event page (`/events/{id}`).

There's no link to the event dashboard page (`/dashboard/events/{id}`). This makes navigating to certain event, found on the chapter's event list, slightly inconvenient, as it's needed to go to events dashboard (`/dashboard/events`) and find wanted event on another list.

Simplest would be replacing link to lead to the event dashboard. Better might be including both links, with visual, or otherwise, indication which link is to event dashboard and which to event page.

**Comment by dineshigdd** [comment]
Do you mean there should be a link from /events/{id} to /dashboard/event/{ id } because at the moment you need to go to the /dashboard/events to access /dashboard/events/{id}?

**Comment by gikf** [comment]
Sorry, I mean the links to the related events at the `/dashboard/chapter/{id}`. That is the `EventList` component -  https://github.com/freeCodeCamp/chapter/blob/main/client/src/modules/dashboard/shared/components/EventList.tsx

**Comment by dianachu18** [comment]
I'm working on this issue.
