### ISSUE TITLE
Should we add joined at field in events_user schema?

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/chapter#1952]
### Discuss your ideas or share your views: 
While creating download user information, I noticed that chapter_user has `joined at` field, which indicate when the user joined chapter. Should `event_users` have the same field?

**Comment by ojeytonwilliams** [comment]
We could, but it doesn't seem like a priority.  Most people will join when they get the invite, I imagine.

**Comment by Sboonny** [comment]
I am closing this as it isn't necessary yet, and it to avoid confusing

**Comment by ojeytonwilliams** [comment]
Thinking about it, it's easier to remove this after the fact than add it (since we'd have to handle null join dates).  I'd be fine with adding a default `NOW()` for this field.

**Comment by ojeytonwilliams** [comment]
Since we don't have any immediate plans to use this, a migration to include this field is all we need.
