### ISSUE TITLE
Use client permissions check to modify UI in dashboards

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/chapter#1961]
Added client side permission check for chapter and event roles, allows now to better modify UI, based on owned permissions. This will be more relevant when more granular user roles will be added.

Dashboards requiring adding UI modifications based on permission checks:
- [ ] Events
- [ ] Sponsors
- [ ] Venues
- [ ] Users

Pages in chapters dashboard have few examples of the permission checks.

Note: Client side check is not intended to replace server side permission check. It merely should hide from user actions that would be later rejected by server anyway. Server side permission check always should be there.

**Comment by Ismailtlem** [comment]
this is done ? not yet ?
