### ISSUE TITLE
disable ProfileForm's save button if the data doesn't change

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/chapter#1970]
**Describe the bug**
It is possible to activate the save button in `userProfile`, when someone focuses on `Profile Picture` section, and move away from it without changing it.

**To Reproduce**
1. Go to /profile
2. Click on Profile picture input
3. Click away from it, without changing anything
4. See save button activate

**Screenshots**

Here is the Owner profileForm
![image](https://user-images.githubusercontent.com/88248797/204120018-bfb2175d-a094-41f8-a107-2278c4907254.png)

---

This happens because profileForm can accept empty string, this is desired because if someone wants to remove their profile picture, an empty string will remove it. But we should account for when there is no profile picture `if user.profile === "" ` and the input is `""`, that the button should stay disabled

---

To get set up locally, take a look at our [contribution docs](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md). And, if you'd like to discuss more, you can head on over to [Discord](https://discord.gg/QbQd7BpaaH) and say hi, or comment here if you prefer.

**Comment by gikf** [comment]
Little context: This is because the initial default value when there's no `image_url` is `null`, but the value in form is `""`.

**Comment by Sboonny** [comment]
Thanks to @bryanleemoore report, the issue seems to be solved and I couldn't replicate it, I don't know why tho.

Here is the discord conversation for context: https://discord.com/channels/692816967895220344/1049822586344833024/1049822588857221191

**Comment by gikf** [comment]
`react-hook-form` was updated in the meantime, maybe there were some changes to that.

There's still slightly related issue:
- Freshly seeded database
- Go to profile
- Add text to the _Profile Picture_ - save button is enabled
- Remove text from the _Profile Picture - save button stays enabled

**Comment by Sboonny** [comment]
Good point, I will check React form if there is an issue for this in there, if yes I will try to fix it.

If not on the other hand, I will check if the issue should be opened for it there, and see if they have an intent on okay with it being fixed.

if not again, I will open an issue with a link to your comment here, and we can fix it here.
