### ISSUE TITLE
Events do not show if they are cancelled or not

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/chapter#1982]
It should be possible to see if an event is cancelled when you are on that event's main page.

For example on the dashboard a cancelled event looks like this
![Event on Dashboard](https://user-images.githubusercontent.com/15801806/204334021-aae7201a-ddc6-4e39-84c7-a2b45bf17131.png)

but the main page for this event has nothing indicating that it is cancelled
![Event main page](https://user-images.githubusercontent.com/15801806/204334322-ef05c56d-4949-412f-a127-b37f0c1f305a.png)

**Comment by allella** [comment]
Probably show hide the RSVP button for a cancelled event too.

**Comment by ojeytonwilliams** [comment]
Very good point.  Probably best to reject RSVP requests to cancelled events on the server, too.
