### ISSUE TITLE
Issues in eventPage RSVP functionality

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/chapter#1993]
**Describe the bug**
I found two issues while testing it #1990, they aren't related to the PR, they are in the main branch:

- session ending while hanging out for a while after press RSVP button, which is the case of this console error <s>(I have no idea how long you have to wait, but I have done it two times)</s> Edit: this is false because I have done it once, luckily in the second time I checked the console and Gitpod workspace was down which cased it to fail, so only one time that happened.

![image](https://user-images.githubusercontent.com/88248797/204565731-44da60d4-bee7-4f93-8774-bd5c331df36c.png)

- if you press RSVP you will subscribe, but if you cancel the RSVP and lose the subscription, you won't subscribe when you press RSVP the next time 

steps to test it 

- press RSVP while logged out, to RSVP and login  (you will become a member and subscribe)
- cancel RSVP and log out
- press RSVP while logged out, to RSVP and login (you will become a member, but you won't subscribe)

This isn't a real issue, but confusion of what to expect when you RSVP

**Comment by gikf** [comment]
The second one is combination of:
- Auto subscribe when RSVPing the first time (when there's no `event_user`).
- Auto unsubscribe when canceling RSVP.
- When `event_user` exists, the `subscribed` is not changed when RSVPing again.

**Comment by RaghuRaikar** [comment]
I am working on this

**Comment by Sboonny** [comment]
I have closed the issue, because the workflow for user and event subscription has changed from when the issue was opened. and it was sorted through changing the users logic.
