### ISSUE TITLE
EventDate value is always changing, which has bad side effects in email system

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/chapter#1996]
**Looking forward for reporting a security issue:**
This issue is similar to https://github.com/freeCodeCamp/chapter/issues/1970, but with slight annoyance. When someone edit `/dashboard/events/{event.id}/edit`, the field related to Date is always included when eventInfo is changed, this affect email system because the logic that require the Date to be changed is always true.

This lead to a bug while testing https://github.com/freeCodeCamp/chapter/pull/1966/commits/5f3c4c1ce247fe83952a1d5a00a1d8ca36d5106a, in which I had tried to change Venue multiple times, but Date was always included without Date value changing

**Comment by Sboonny** [comment]
For context, I have opened this issue for documentation and to give context for my 2nd PR that will carry fix for this.

**Comment by Sboonny** [comment]
The side effect isn't real, and I was overthinking it. the side effect caused by the Date comparison is false, even when both dates are the same https://github.com/freeCodeCamp/chapter/pull/1966/commits/fe1bc45d77f173b3dc19c6672e42b7579904853a

Checking if the data is bigger or smaller removed the side effect, https://github.com/freeCodeCamp/chapter/pull/1966/commits/ce2e95047c81fd11ba776f34a5491a4c0298f332

----

The issue with the focusing over the Date fields in `/dashboard/events/1/edit` and activate the save the data button still there, but with no side effects, so I am opening this for contribution.

---



To get set up locally, take a look at our [contribution docs](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md). And, if you'd like to discuss more, you can head on over to [Discord](https://discord.gg/QbQd7BpaaH) and say hi, or comment here if you prefer.

**Comment by ojeytonwilliams** [comment]
Hey @Sboonny, since this is open for contributions, could you spell out the requirements more explicitly?

**Comment by Sboonny** [comment]
Thanks to https://github.com/bryanleemoore report, the issue seems to be solved and I couldn't replicate it, I don't know why tho.

Here is the discord conversation for context: https://discord.com/channels/692816967895220344/1049822586344833024/1049822588857221191
