### ISSUE TITLE
Ability to ban members from instances in User dashboard sections

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/chapter#2049]
### Discuss your ideas or share your views: 
I think this is Oliver idea, as he mentioned to me before that banning user from chapter isn't really necessary and we can ban them from the instances instead, but I am not sure as this based on old memory. 

So if the account is a bot like allella mentioned here https://github.com/freeCodeCamp/chapter/issues/1767#issuecomment-1295073173, the instances owner may find it annoying to keep banning the bots whenever they create a chapter and may want to ban them from the instances instead. This will be quality of life for instances owner, because they won't have to deal with bots account forever

I think this will resolve allella comment here https://github.com/freeCodeCamp/chapter/issues/1767#issuecomment-1295073173, as ban user from chapter will be different from ban user from instances, so there will be no need to create email for it.

**Comment by allella** [comment]
Not sure if this is a good idea, but if we stuck with the _[user_bans](https://opensource.freecodecamp.org/chapter/tables/user_bans.html)_ schema, then setting a ban for a _user_ with _chapter_id_ = -1 could be an implied "all" chapters (full instance) ban.

In the context of it being a bot, perhaps the organizer, admin, owner are given an interface to ban for a specific Chapter, or else  the whole instance.  Then, an option to toggle notifications to the user of any cancelled RSVPs related to the ban.
