### ISSUE TITLE
Chapter links in user profile extends to the page width

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/chapter#2055]
In user `/profile` links to the admined chapters have width almost the same as page width. Which means they can be activated and clicked when mouse cursor is nowhere near the link text.

![image](https://user-images.githubusercontent.com/60067306/206097288-49422f6b-6625-4c72-ab42-17f17f02a4cc.png)

**Comment by dineshigdd** [comment]
can you please assign me this issue?
