### ISSUE TITLE
Test for the ability to cancel RSVP through emails

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/chapter#2097]
**Describe the bug**
In #2084, the functionality changed which lead to the deletion of a test. <S>The test is about the ability to cancel RSVP through email.</s> edit: please check the comment below 

 Here is the old test for references https://github.com/freeCodeCamp/chapter/pull/2084/files#diff-bfa943094ad576c0b782ea47413089b56c8a37f71dd048d5038e99a0c2597f72

To fix this issue, add a test for the ability to cancel RSVP.

---

To get set up locally, take a look at our [contribution docs](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md). And, if you'd like to discuss more, you can head on over to [Discord](https://discord.gg/QbQd7BpaaH) and say hi, or comment here if you prefer.

**Comment by gikf** [comment]
It was supposed to be test using link for the initially logged out user. There's no canceling via link in mail anymore.
