### ISSUE TITLE
Internationalize the Chapter Application

### ISSUE THREAD

**Issue by komputarist** [freeCodeCamp/chapter#21]
This will involve localizing the components of the applicatoin be translation Ready and have support for many international languages. Recommended library for this is React-intl.
For more, see [here](https://github.com/formatjs/react-intl)

**Comment by espipj** [comment]
I can help with Spanish localization/intl

**Comment by mmiszy** [comment]
It's also officially supported by Next.js so it looks like a great choice: https://github.com/zeit/next.js/tree/canary/examples/with-react-intl

**Comment by aloisdg** [comment]
I can help with the fr-fr translation.

**Comment by AugustusZ** [comment]
I can help with the `zh-CN` translation

**Comment by maludecks** [comment]
I can help with the `pt-BR` translation 😸

**Comment by MustafaAnasKH99** [comment]
I can help with `ar-SY` translation  :alien:

**Comment by QuincyLarson** [comment]
We will probably use something like https://github.com/zeit/next.js/tree/canary/examples/with-react-intl that @mmiszy mentioned.

For now, our MVP will be English. We can revisit this once our MVP is out. For now I've added this to our roadmap and I will close this issue.
