### ISSUE TITLE
Don't show the confirm modal when a user has already RSVP'd

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/chapter#2108]
### Discuss your ideas or share your views: 

When a user visits the page /events/[id]?confirm_rsvp=true of an event they have already RSVP'd to, the confirmation modal pops up.  This should not happen, since all that the user can do is Cancel (which does nothing) or Confirm (which just triggers the Already RSVPed toast).

It should be sufficient to skip this and just show the toast.

**Comment by bryanleemoore** [comment]
Hi @ojeytonwilliams, I'm having trouble replicating this.

When I navigate to /events/[id]?confirm_rsvp=true of an event I've already RSVP'd, I do not see the modal nor do I see the "Already RSVPed" toast. 

Here are the steps I am doing to attempt to reproduce this issue, let me know if I am doing something wrong:
1. Navigated to /events/9
2. Clicked the blue RSVP button, confirmed my RSVP on the modal, and saw the "You successfully RSVPed to this event" toast.
3. Navigated to /events/9?confirm_rsvp=true

I do not see a modal or toast when navigating to that page, am I doing the steps right?

**Comment by gikf** [comment]
@bryanleemoore that's strange, as I can confirm the modal appears when following these steps. Try making sure that you are running code with latest changes.

**Comment by ojeytonwilliams** [comment]
That's likely it, we've recently changed the query param so older versions will not work.
