### ISSUE TITLE
ChapterCard - add indication when event is invite only

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/chapter#2189]
Chapter card is displaying up to `3` events, with name and if it's running or upcoming event. Indication whether that event is also invite only seem to be important enough to include it in card.

Other than making change to the `ChapterCard.tsx` file, approaching this issue will additionally require adding `invite_only` field in two `queries.ts` files and running `npm run gen` to generate updated hooks.

**Comment by dineshigdd** [comment]
there are two `invite_only` in queries.ts

**Comment by Ravichandra-C** [comment]
@gikf Can I pick this up?

**Comment by gikf** [comment]
Hey @Ravichandra-C 

as usual the issues are rarely assigned to specific person, but feel free to tackle it.

**Comment by Ravichandra-C** [comment]
@gikf , Did you mean showing invite only on /chapters page?

![image](https://user-images.githubusercontent.com/17808008/215832224-b82c5fa4-0ce9-4343-b0d5-82dff6a2294c.png)
