### ISSUE TITLE
Add mention of chapter to dashboard pages

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/chapter#2209]
Chapter is not present on the individual dashboard pages of event and venue in any way (name, link, etc). This makes navigating to chapter inconvenient, as the appropriate chapter needs to be found in a more manual manner.

- [ ] `/events/{id}` https://github.com/freeCodeCamp/chapter/blob/main/client/src/modules/dashboard/Events/pages/EventPage.tsx
- [ ] `/venues/{id]` https://github.com/freeCodeCamp/chapter/blob/main/client/src/modules/dashboard/Venues/pages/VenuePage.tsx

**Comment by atosh502** [comment]
Hi @gikf, I would like to work on this task.
