### ISSUE TITLE
Unsubscribing via email links can fail with an unhelpful message

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/chapter#2215]
When a new event is created, Chapter emails the subscribers to let them know about it.  These emails contain two unsubscribe links; one for the chapter (to stop these kinds of emails) and one for the event (to stop notifications about that event specifically).  However, until the user RSVPs the event unsubscribe link is both unnecessary and buggy. The user is shown "Error: No event_users found" and nothing happens.

We should

- [ ] Only send links for things the user has subscribed to (in this case the Chapter that the event belongs to)
- [ ] Handle the case where a unsubscribes more than once (e.g. by following the link twice or unsubscribing via the chapter/event page and then following the link)

**Comment by gikf** [comment]
I believe second task is already covered. Both using the link more than once, or doing it after unsubscribing on the page.

Additionally I think it might be worth to decide on some specific way of handling the _Error: No event_users found_ error. Maybe just catch the error and follow the rest of happy patch? Technically the _Unsubscribed_ information would be true.
