### ISSUE TITLE
Move add new button from Events and Venues pages

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/chapter#2222]
## Describe the bug:

While working https://github.com/freeCodeCamp/chapter/pull/2121, I noticed that "add new" button experiences isn't optimal because instances owner can interact with it, before they have chapter or venues.

[Event-add-new-issue.webm](https://user-images.githubusercontent.com/88248797/212538312-0db1f718-3c6c-4b4c-ab29-fadf037b739e.webm)

Here is my suggestion, we delete the "add new" buttons except for chapter's.

And change the layout to be something like this:

## Chapter_1 Venue 1  

- Add new Event button

| eventName | data | actions|
|---------|-----------|---------|
|Hello event one| event one data | edit|
|Hello event two| event two data | edit|
|Hello event three| event three data | edit|

## Chapter_1 Venue 2
  
- Add new Event button

| eventName | data | actions|
|---------|-----------|---------|
|Hello event one| event one data | edit|
|Hello event two| event two data | edit|
|Hello event three| event three data | edit|

## Chapter_2 Venue 1
  
- Add new Event button

| eventName | data | actions|
|---------|-----------|---------|
|Hello event one| event one data | edit|
|Hello event two| event two data | edit|
|Hello event three| event three data | edit|

## Chapter_2 Venue 2
  
- Add new Event button

| eventName | data | actions|
|---------|-----------|---------|
|Hello event one| event one data | edit|
|Hello event two| event two data | edit|
|Hello event three| event three data | edit|

-----------------------

With this the add new button won't show unless there is chapter and venue present, and we can drop the pick chapter and pick venue fields, because the user will be picking chapter and venue, when they click on "add new Event".

Edit: or keep the chapter and venue field, but prepick them for the users 🤔 

----

The same concept can be applied to Venues but it will be simpler because it doesn't have to account for Events.

**Comment by gikf** [comment]
Couldn't this still be handled with `user.admined_chapters`? Optionally with specifically checking if user has permissions for adding event, in any of the admined chapters.

Regarding venues - not always chapter might have them or need them. Ie. if chapter makes online-only events. Additionally, as deleting venue will be added, I think that will open the need for creating/editing event, with in-person venue type, but without specific venue selected yet. Kind of default _Undecided_/_TBD_ option, which doesn't link to any existing venue.

**Comment by Sboonny** [comment]
> Couldn't this still be handled with `user.admined_chapters`? Optionally with specifically checking if user has permissions for adding event, in any of the admined chapters.

I should have checked the gif, but it doesn't show the dropdown in the gif. 

The current experience happened for the owner without the existence of Chapters, so here is the issue:

- they can try to skip creating chapters, move to events to create a quick one,
- see the add new button, and click it.
- add the required data, but can't create the event.

---

We can have if statement that go likes `if chapters.length === 0 { please visit chapter page to create events/venues } `.

---

> Regarding venues - not always chapter might have them or need them. Ie. if chapter makes online-only events. Additionally, as deleting venue will be added, I think that will open the need for creating/editing event, with in-person venue type, but without specific venue selected yet. Kind of default Undecided/TBD option, which doesn't link to any existing venue.

True, 🤔 good point, should I open new issue or we solve both in this issue.

**Comment by Sboonny** [comment]
I noticed that we are using chapter.id to find if someone has permission to edit Events, we can't have the same option for chapters.

**Comment by gikf** [comment]
> The current experience happened for the owner without the existence of Chapters, so here is the issue:
> 
> * they can try to skip creating chapters, move to events to create a quick one,
> * see the add new button, and click it.
> * add the required data, but can't create the event.

It isn't displayed on the `main` if there's no chapters:
https://github.com/freeCodeCamp/chapter/blob/698ec4a03e65e29dce80e312aa5efb50bf6ed8f8/client/src/modules/dashboard/Events/pages/EventsPage.tsx#L67-L78


`admined_chapters` are technically displaying chapters with the `EventEdit` permission, to make sure user has `EventCreate`, at least on one of the chapters, that could be changed to:
```typescript
  const hasPermissionToCreateEvent = user?.admined_chapters.some(({ id }) =>
    checkPermission(user, Permission.EventCreate, { chapterId: id }),
  );

(...)
        {!!user?.admined_chapters.length && hasPermissionToCreateEvent && (
```
---

Manually opening `/dashboard/events/new` does display form that cannot be used, if it's concern some check could be added to that page.

---

Yeah, allowing to not have chapter when creating event would need multiple changes.

**Comment by Sboonny** [comment]
I haven't checked the main branch, I thought after my last merge and fixing the conflict, that I am in the same state as the main branch. Should have checked, there were too many hints 😥.

Yeah, that's the exact fix, there is no issue.

```ts
 {!!user?.admined_chapters.length && ( 
   <LinkButton 
     data-cy="new-event" 
     href="/dashboard/events/new" 
     colorScheme={'blue'} 
   > 
     Add new 
     <Text srOnly as="span"> 
       Event 
     </Text> 
   </LinkButton> 
 )} 
 ```
 
 ---
 
 > Manually opening `/dashboard/events/new` does display form that cannot be used, if it's concern some check could be added to that page.
 
 Not a real concern to me, if someone tries to skip something and doesn't get a good experiences because of it, it isn't our fault because they have gone out of their way to do something abnormal.
 
 --- 

> Kind of default Undecided/TBD option, which doesn't link to any existing venue.

I like that idea tho, let's keep the issue open, and try to add this. 👍

What about adding a 3rd checkbox with text "To be decided", and if user select it they will have an empty stream_url.

Then if stream_url is empty, we don't show it 🤔

**Comment by gikf** [comment]
I'm gonna make PR to add _Undecided/TBD_ tomorrow, the changes needed seem to be relatively isolated. As `stream_url` can be submitted blank, we can display it similarly as _Undecided/TBD_.
