### ISSUE TITLE
Venue data not available to attendees

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/chapter#2229]
### Discuss your ideas or share your views: 
I remember some discussion about it, but I'm unable to find it right now.

Venue data (physical venue, streaming url) is not really available to attendees. Outside of the (admin) dashboard, the only moment when attendee is informed about venue data is when it's changed.

It is not included in RSVP confirmation email, or on event page available to attendees. It is however in invite email send to chapter members.

If invite email contains it, then I think there's no reason to not include it in the confirmation email. On the event page, venue data could be displayed only after RSVPing.

**Comment by 1217Brent** [comment]
I'm working on this!
