### ISSUE TITLE
loadingUser doesn't change on error

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/chapter#2259]
### Describe the bug:
When `useMeQuery` in `client/src/modules/auth/user.tsx` errors, the `loadingUser` is not changed.

This makes possible to be stuck in loading when there's some error during the query.

I'm not entirely sure what's the appropriate action in such case. The _simple_ thing that comes to mind is just adding error case to the useEffect:
```
    if (error) {
      setData({ loadingUser: false, isLoggedIn: false });
    }
```

**Comment by ojeytonwilliams** [comment]
That should do it, though we should handle the error on the client.  I'd like to get https://github.com/freeCodeCamp/chapter/pull/2263/ in first, though. Also, I'm interested to see how this interacts with the retry link.
