### ISSUE TITLE
Replace RSVP with clearer terminology

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/chapter#2272]
When I introduce people to Chapter I often have to explain what RSVP means.  While it does, technically, make sense if a user has been invited (they are RSVPing and that's what the RSVP button does), it's not immediately obvious.

A simple change to use Attend Event as the button text should be enough to mitigate some of the confusion.  Also, I think Attendee is a fine substitution when we need to refer to the people that are going to an event.

Since rsvp is everywhere in the codebase, it would be best to split this into 3 jobs

- [x] UI closed by https://github.com/freeCodeCamp/chapter/pull/2284
- [x] Database closed by https://github.com/freeCodeCamp/chapter/pull/2337 and https://github.com/freeCodeCamp/chapter/pull/2341
- [x] Server closed by https://github.com/freeCodeCamp/chapter/pull/2341

prioritized in that order so we improve things for users first, then split the pain of refactoring the api into two.

The only downside I see to this is that it's the same word that Google uses for people going to Calendar Events. I think that's probably fine, though, since it's the obvious word to use and context + TypeScript should make it clear enough.

**Comment by allella** [comment]
I guess if you're changing the backend terminology then would it be _attendees_ . "attendance" popped in my mind first, but everything else in the schema is a noun, so I guess that's for a reason and gives _attendees_ the edge.

We use "RSVP" in the README too would make sense with some minor rewording in the few places it's used.

**Comment by ojeytonwilliams** [comment]
Thanks for all the careful fixes @gikf. This will definitely help new users figure out what they need to do.
