### ISSUE TITLE
Opt in to Chapter notifications when attending first event

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/chapter#2273]
The first time a user tries to attend an event in a new chapter, they're given the following warning

> Join this event?
> Note: joining this event will make you a member of the event's chapter.

New users do not necessarily know what a chapter is or membership of a chapter comes with a subscription.  That means it is unclear exactly what this warning is about.

Since the relevant thing they're opting into is notifications of subsequent events, we should make that explicit.  Also, it should actually be opt in.  Since https://github.com/freeCodeCamp/chapter/pull/2103 `auto_subscribe` is true, which I think is fine for Chapter pages, since the user immediately sees the Unsubscribe button. However, this is different since it's unreasonable to expect someone to intuit what joining a chapter means and we don't offer an obvious way to unsubscribe. 

### Possible fix

- Replace the warning with unchecked checkbox "Subscribe to subsequent events" and only subscribe them to the Chapter if they check it.

### Downsides

- This makes it more likely that people accidentally opt out of something they would want
- It's an additional annoyance to users who don't forget - they have to click the box or go to the chapter to subscribe
- auto_subscribe's function becomes more specialised and less obvious

Perhaps we can revert https://github.com/freeCodeCamp/chapter/pull/2103 (again) simply not show the checkbox if they set auto_subscribe to true.

In addition, if we put "You're unsubscribed" warnings on the chapter page and it's event pages, then people who are unsubscribed should realise and, if they want to, can easily change their mind.

Finally, alongside the warning, we should put a subscribe to chapter button on the event page.

**Comment by ojeytonwilliams** [comment]
@allella @gikf sorry to bring this up yet again.  It's tricky to balance the desire to keep people informed with the need to avoid spam.  I hope the ideas I've outlined move us in the right direction, but, as ever, any input you have is greatly appreciated.

**Comment by gikf** [comment]
Couple related ideas:
- Send email after user joins chapter, whether that's automatically as a part of event RSVP, or manual join.
- Page(s) with common used terms explained - chapter, instance, event subscription, chapter subscription. Plus linking to these specific explanations from various places.

**Comment by ojeytonwilliams** [comment]
> Send email after user joins chapter, whether that's automatically as a part of event RSVP, or manual join.

I.e. an onboarding email that's triggered the first time they join a chapter?  That could be helpful.

> Page(s) with common used terms explained - chapter, instance, event subscription, chapter subscription. Plus linking to these specific explanations from various places.

Something like that may be necessary, but as much as possible I'd like explanations to be attached to the potentially confusing thing. Mouseover text (as long as we make it accessible) is really good for this.

**Comment by allella** [comment]
The checkbox, or rather a [slider may be the correct form element](https://uxplanet.org/checkbox-vs-toggle-switch-7fc6e83f10b8), based on [earlier conversation](https://github.com/freeCodeCamp/chapter/issues/274#issuecomment-562442271) may be fine.

This may be a UX anti-pattern, but I guess you could also have two buttons, perhaps still with text explaining that joining a chapter is subscribing to updates.

[Attend Event]    [Attend Event & Join this Chapter]

Also, per https://github.com/freeCodeCamp/chapter/issues/2272, I do agree "Attend" is better than "RSVP" for the user, since RSVP may not be universally used across the world, but attend seems like it makes sense to anybody speaking english. 

Also, the word "Join" should probably be reserved for _chapters_. Joining an _event_ sounds weird to me, but joining a _chapter_ does not.

**Comment by allella** [comment]
Actually, a slider / toggle may not be appropriate since it's intended for select + execution at the same time and since there's a button, [a checkbox would be the suggested option](https://uxplanet.org/checkbox-vs-toggle-switch-7fc6e83f10b8#122b).  

That is, if the two button approach, with no checkbox, isn't a good idea.

**Comment by ojeytonwilliams** [comment]
The issue is that there's a distinction we need to make between Joining and Subscribing. Joining is unavoidable because a user needs to be a chapter member before they can attend events. Subscribing is optional, though.

I don't think this UI needs to go into that distinction, though, simply because there isn't a choice about Joining.

> since there's a button, [a checkbox would be the suggested option](https://uxplanet.org/checkbox-vs-toggle-switch-7fc6e83f10b8#122b).

That makes sense to me. It can be as simple as "Send me notifications about new events" like Case 2 from the linked article. Also, we'd only need to show if they're not currently subscribed to the chapter.

**Comment by allella** [comment]
@ojeytonwilliams the point with "Join an Event" is that I think we're mixing verbs.  I feel "Join" should be reserved for _chapters_ and other verbs as below.

- **Join** a Chapter
- **Attend** an Event  (previously RSVP to an Event)
- **Subscribe** to Updates / Emails

**Comment by allella** [comment]
We have discussed using "Follow" as a verb, as an alternative to "Join", in the context of _chapters_, but I'm happy with "Join" for chapters if others prefer it.

**Comment by ojeytonwilliams** [comment]
>  I feel "Join" should be reserved for chapters and other verbs as below.
>
> - Join a Chapter
> - Attend an Event (previously RSVP to an Event)
> - Subscribe to Updates / Emails

That makes perfect sense to me. Join seems more suited to Chapters than Events and we should be consistent.

I prefer "Join" over "Follow", too. To me "follow" implies you're interested, but not taking part.

So, to sum up, I think we want 

```
Attend this event?

Send me notifications about new events <checkbox>
Cancel Confirm
```

and I think we can reuse the checkbox + logic for joining a new chapter.
