### ISSUE TITLE
Give users feedback about calendar event attendance

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/chapter#2274]
Since users have to manually confirm their attendance at events, a small UI indicator showing that they have (or have not) done this would be nice.  Something similar to 

![dashboard event form](https://user-images.githubusercontent.com/15801806/214366808-7dbc12b1-0f0a-482d-86c0-edc551ec40ce.png)

 from dashboard/events/[id] should be fine.

This is certainly not a high priority, but forgetting to confirm could result in users missing events or being unable to join meetings until they realise their mistake.

**Comment by atosh502** [comment]
Hi @ojeytonwilliams I'll take a look at this

**Comment by ojeytonwilliams** [comment]
Thanks, @atosh502. Feel free to ping me if you need any clarification.

**Comment by Ismailtlem** [comment]
For which type of users do we want to have this ?
For admin, owners, is it not already done ?
Can a normal user of some event see dashboard/events/[id] ?

**Comment by atosh502** [comment]
Hi @Ismailtlem,
I believe the requested change is about adding the UI indicator to `/events/{id}`, after confirming attendance at a calendar event(I might be wrong about this). I haven't looked into calendar integration in Chapter and I see you've already started poking around the calendar API, feel free to take this on.

**Comment by ojeytonwilliams** [comment]
Sorry, @atosh502, @Ismailtlem I've belated realized that it's unlikely we can achieve this without running into usage limits for the calendar API.

Once we've got a clearer idea of how real usage of Chapter translates to usage of the calendar API, it might worth revisiting this. However, it's not worth working on until we have that data.
