### ISSUE TITLE
Individual chapter dashboards should link to the dashboards for their events

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/chapter#2297]
If I `npm run change-user:owner`, login and go to http://localhost:3000/dashboard/chapters/1 I see links to event pages rather than dashboards. For example, if event 1 is in chapter 1, I will see a link to 

http://localhost:3000/events/1
but I should see
http://localhost:3000/dashboard/events/1

**Comment by dineshigdd** [comment]
little confused. What is the user story or flow of events here? I assumed it as follows
1.) user logged in
2.) select Chapters from the drop-down menu
3.) select an event added to the chapter

is this would be the flow of events?

and the URL that appears right now is `http://localhost:3000/events/1`.
But, it should be `http://localhost:3000/dashboard/events/1`
