### ISSUE TITLE
Putting chapter.name on event cards is not necessary on the chapter's page

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/chapter#2299]
While it's useful to have the chapter in event cards on the home page, it's redundant on the chapter's page. For example:
![chapter name repeated in event list](https://user-images.githubusercontent.com/15801806/215137950-e72d1953-377b-463d-b495-d5f76c0a454b.png)

@Sboonny do you think this is a candidate for a Good First Issue label? If so, could you add it?

**Comment by Sboonny** [comment]
I have added to because the card being a `Link` wasn't accessible, I am happy with it removed. 

As long as the Card isn't a link, I am happy. later on I will try to add pseudo-element, that will make the Card act as Link but screen reader won't read 

> Link:element:innerText:element::innerText:element:innerText::element:innerText:LinkTex
