### ISSUE TITLE
Monitoring, logging, alerting, ci/cd, automation of the creation of resources

### ISSUE THREAD

**Issue by jeremiahlukus** [freeCodeCamp/chapter#23]
These are a few things that I haven’t seen talked about yet. Have these things been considered? 

If we can go to a paid option new relic will take care of most of these things if we use a free option There are several good options. We can use terraform to create policies and alerts, as well as the creation of resources (ie: pg clusters, elastic) 
If these things have already been hammered out that is great, else I’m more than happy to go into more detail and map out what I think needs to be done as far as infrastructure.

**Comment by jeremiahlukus** [comment]
Also for elastic what is the scope of usage? will there be a need for multiple indexes?

**Comment by Zeko369** [comment]
Prometheus for monitoring?

**Comment by bernhard-hofmann** [comment]
@jeremiahlukus Please do go into a little more detail for us non-devops peeps. I'm not familiar with some of the names you mentioned there. Would be good trip know what reach one does and why you'd use it.

**Comment by uncompiled** [comment]
All of this makes sense if you're providing a managed service, but I was just reading through the readme and it seems like the output of this project (for now) will be a Docker container that you can run on your own infrastructure.

If the goal is to have one-click deployment, I would think that the short term goals would be to create deployment scripts/templates that can deploy this to AWS, Google Cloud, Microsoft Azure, Heroku, Linode, etc.

As an community organizer, two things that are important to me are:
- Ease of use (i.e. easy to run and maintain)
- Low cost to operate

While it's not an issue for me to run a docker container on a virtual server somewhere, something like Google's [Cloud Run](https://cloud.google.com/run/) or AWS's [ability to launch CloudFormation templates](https://aws.amazon.com/blogs/devops/construct-your-own-launch-stack-url/) would probably make it easier for users to deploy the software with fewer steps.

**Comment by viniciustodesco** [comment]
Why not VSTS ? we can make practically everything there CI/CD ...
https://azure.microsoft.com/pt-br/services/devops/

**Comment by Abott1222** [comment]
I vote elastic stack for reporting and monitering

**Comment by allella** [comment]
If someone is looking to attract more of the CI folks with the related skills for this feature then we've been logging the various skills from people in the Discord channel.  Also, folks are posting directly on the Github thread.

So, see the list of volunteers and skills at search for "circleci" and related terms. The page is long so you may need to un-collapse some parts of the thread.

https://github.com/freeCodeCamp/chapter/issues/11#issuecomment-542309409
and try to connect with them as needed.

**Comment by ScottBrenner** [comment]
+1 for GitHub Actions, use it for a few things and it's great!

**Comment by shirakaba** [comment]
> I vote elastic stack for reporting and monitering

Note that the official alerting functionality, and all but basic monitoring features for the Elastic stack are platinum (paid-for) feature, so we should look for other solutions. The free tier of the Elastic stack is still great for logging.

Alongside the free tier of the Elastic stack, I use Grafana for certain types of alerts like thresholds (and in preference to Kibana for creating most of my graphs), and Yelp's [ElastAlert](https://github.com/Yelp/elastalert) for any types of alerting that Grafana doesn't support.

**Comment by Abott1222** [comment]
@shirakaba Also keep in mind splunk also has a free option:


Splunk® Free
One User
Scale up to 500 MB data per day
Collect and index any machine data
Real-time search and analysis

One problem is that we only get 1 user but if we set it up correctly as an admin account we might be able to make it work in our distributed system

**Comment by QuincyLarson** [comment]
We will consider adding some tools like this once we have shipped our MVP. For now I'm closing this stale issue.
