### ISSUE TITLE
Remove GraphQL Playground broken link

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/chapter#2377]
### Describe the bug:
[GraphQL Playground](https://chapter-server.herokuapp.com/graphql) link in the `CONTRIBUTING.md` leads to broken Heroku page. The free-tier of Heroku was phased out, so that's likely the main reason why link doesn't work. Another question is whether there's still need for having it externally.

**Comment by ojeytonwilliams** [comment]
I forget the reason for hosting in the first place, but I don't think we need to. Not now we know how to use GitPod to make authenticated queries.

All we need to do is update the docs, removing that bullet point and linking to the FAQ for the authenticated queries.
