### ISSUE TITLE
Can't zoom when the layout isn't desktop

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/chapter#2403]
WCAG [SC 1.4.10](https://www.w3.org/WAI/WCAG21/Understanding/reflow.html) requires that the user be able to zoom up to 400% on a 1280x1024 viewport and still be able to use the page "without loss of information or functionality". The image below shows a Step zoomed in 400% on a 1280x1024 viewport.

[rec-screen (1).webm](https://user-images.githubusercontent.com/88248797/220432483-1b8074b6-ea0e-4905-8e46-ae690f39a98e.webm)

But chapter doesn't allow change of font-size when zooming in, my guess is chakra when the screen width is lower "lg" (desktop) size, it starts using `vw` and `vh` to set font-size, which doesn't change with scroll behavior. 

This is record of the issue, until we know if it's actually chakra or something weird, we are doing

**Comment by gikf** [comment]
Isn't the responsive view already adjusted appropriately to the device size? I looked at few pages, including the bbc.com/earth/world and none of them were zooming when viewing in the responsive/device mode.

**Comment by Sboonny** [comment]
You can't zoom in devtools. 🤦 

when your message indicated a different concept, i have tested it again in the devtools, then I tested github with devtools and they didn't work.

I opened a new tab and resize it manually instead of dev tools and the zoom function works 🤦
