### ISSUE TITLE
Add warning when canceling the events about the waitlist

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/chapter#2407]
### Discuss your ideas or share your views: 
When a user leaves an event which has a waiting list, someone else will join the event in their stead, I don't think this is an issue, just warning about it happening should be enough, if there is a waitlist.

https://user-images.githubusercontent.com/88248797/220564704-57d3d355-0e8f-4bd9-9551-76e401f626b5.webm

Including a body, if there is a waitlist in the section below, should do the trick.

https://github.com/freeCodeCamp/chapter/blob/45be96dc812617511c7c0cd33feef0068b872cea/client/src/modules/events/pages/eventPage.tsx#L137-L139

---

To get set up locally, take a look at our [contribution docs](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md). And, if you'd like to discuss more, you can head on over to [Discord](https://discord.gg/QbQd7BpaaH) and say hi, or comment here if you prefer.

**Comment by Sboonny** [comment]
We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by dineshigdd** [comment]
At the moment, I see that when you confirm, you will be put on the waiting list. And this is informed to the user with an alert

**Comment by Sboonny** [comment]
Yeab, if there are people in waitlist, they should be notified that their place can be taken by other attendence as well.

**Comment by hound77** [comment]
@Sboonny I want to work on this issue

**Comment by Sboonny** [comment]
You can open a PR directly 👍, we don't assign issues.
