### ISSUE TITLE
Space between event image and header

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/chapter#2497]
### Describe the bug:
On event page - `events/{id}` there's no space between image and header:
![image](https://user-images.githubusercontent.com/60067306/226710055-6ae53a64-b19c-421c-80e5-4bd80ed57120.png)
Some space should be added to separate the two. Also maybe separating margin might be set on the `PageLayout`, instead of individual pages.

**Comment by randychilau** [comment]
Hello, I am a newcomer to open source and would like to work on this.

Using the information provided above, it seems to be configurable in the following file:
client/src/modules/events/pages/eventPage.tsx

Here is what is looks like setting the top margin spacing to 1rem:

![image](https://user-images.githubusercontent.com/90356410/226772977-ccdcce3f-a470-499e-9582-ee28761f0d07.png)

Please assign me this issue if possible.

Cheers,
Randy

**Comment by gikf** [comment]
Hey @randychilau,

that looks good. We typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue. So feel free to create PR.
