### ISSUE TITLE
Potential Feature for V1 or V2

### ISSUE THREAD

**Issue by PrestonElliott** [freeCodeCamp/chapter#25]
I think it would be beneficial to add a tag id column to the events table and add tags table, so we can add filters for specific tags. For example, if I'm interested in attending meetups for JavaScript, eSports, and hiking, I want to be able to filter all events for these specific tags and return those results.

**Comment by allella** [comment]
@PrestonElliott Would you mind posting this on https://github.com/freeCodeCamp/chapter/issues/1

and closing this issue? That should keep the conversation on v2 features more consolidated.

**Comment by PrestonElliott** [comment]
@allella absolutely, I'll close it out now!
