### ISSUE TITLE
Should API routes be revolving around chapters

### ISSUE THREAD

**Issue by Zeko369** [freeCodeCamp/chapter#251]
@timmyichen, @Zeko369, @nik-john, @allella I was looking at the api routes and I realized that the routes are revolving around `chapters`. What if an organization doesn't have a chapter? 
Just, for example, assume we have `Coders.org` as an organization and they don't want any chapters under them, they host events under the organization's name. In that case, our routes will return 404, right? I think we should include /events, /events/eventId and so on as routes. What do you all think?

_Originally posted by @vkWeb in https://github.com/freeCodeCamp/chapter/pull/162#issuecomment-554988089_

**Comment by Zeko369** [comment]
I mean we could have separate `/events`, and `/events/:eventID` routes, but why not just make it simple and have `/chapters/1/events/:eventID`, and then on setup just create a default chapter that you for example cant delete if it's the only one.

**Comment by vkWeb** [comment]
@Zeko369 You mean the organization will be treated as a chapter if there's no chapter under them?

**Comment by Zeko369** [comment]
Let me just see if you understand what you're saying. Organization would be a person/organization hosting a chapter docker container?
If so, my idea was that we tie everything to a chapter, so when you set it up the first time you create one chapter, and if there's only it's treated as the organization.
example: `foobar rails meetup` would create a chapter instance running on `foobar.rails.org` and have one `chapter` in the database called eg. `foobar rails`. Later they could add more like `barfoo rails`, running on the same host.
Correct me if I'm wrong?

**Comment by vkWeb** [comment]
@Zeko369 You are correct. That's what I was confirming.

**Comment by allella** [comment]
This is a good question, though I would agree with still making everything run through the Chapter-based schema, even if there's only 1 chapter in an organization.

I feel it's easier to hide or tweak things in the UI, for example hiding the "Chapters" menu link if there's only 1 Chapter, then it is to have a secondary pattern / API to support 1 Chapter organizations.

**Comment by vkWeb** [comment]
@allella Yes, that would be better instead of tweaking the whole API structure.
