### ISSUE TITLE
Sequelize vs Typeorm

### ISSUE THREAD

**Issue by Zeko369** [freeCodeCamp/chapter#252]
@Zeko369 I'm down to use TypeORM but we should loop @QuincyLarson into this conversation as I believe it was he who initially proposed sequelize.

_Originally posted by @timmyichen in https://github.com/freeCodeCamp/chapter/pull/162#issuecomment-555104877_

Since using TS for migrations and seeds with sequelize is a really janky experience I think that we should consider using TypeORM. If anyone has any experience using Typeorm or why we should stick with Sequelize feel free to comment here.
One great thing that we cant do with sequelize since we're using sequelize-ts for models is migrations, TypeORM can be used to automaticly generate migrations (they can sometimes be wrong, this aint Rails' ActiveRecord) but would greatly help.

**Comment by Zeko369** [comment]
Or maybe something like this https://github.com/Vincit/objection.js/issues/1069#issue-359237930

**Comment by Zeko369** [comment]
`Copied from discord`
The only difference that I found so far (I'm using it for a differenet project) is that you cant do this 
```
User.create({
    username: 'janedoe',
    birthday: new Date(1980, 6, 20)
  }))
```
And have to do
```
const user = new User();
user.username = 'asd';
user.birthday = new Date();
user.save();
```
But we could do this https://github.com/typeorm/typeorm/issues/3903, and fix that problem

**Comment by timmyichen** [comment]
Since we're writing code that closely resembles TypeORM already, I think we can just move to that and use the linked issue above for keeping the same style.

**Comment by Zeko369** [comment]
@nik-john @timmyichen @Zeko369 @ceciliaconsta3 @allella @QuincyLarson

**Comment by allella** [comment]
I'm fine with whatever you folks find will work. Though, I agree it would be good for Quincy and others to stamp this one.

Given the trouble Sequelize + Typescript has  already caused it seems wise to consider a tool that plays well.

Sequelize was suggested Quincy well before the technical conversations started, presumably to set a reasonable default tech stack and avoid an endless conversation about the stack. 

Also, Sequelize was suggested before TypeScript was introduced.

**Comment by QuincyLarson** [comment]
I will defer to the people building the app itself.

@Zeko369 If you think TypeORM is a better fit and you're the main person working on this at the moment, I say go ahead and get started with it.

If anyone has other opinions on this you can share those here.

**Comment by Zeko369** [comment]
@freeCodeCamp/chapter-moderators Any other thoughts?

**Comment by allella** [comment]
@nik-john @ceciliaconsta3 you were both referenced here and are welcome to chime in. I think everybody else on the thread has stated their opinion or deferred (Quincy and I).

@iansltx listed both TS and Sequelize in #11 and @oyewoas @hamidnoei @imccausl listed Sequelize experience, so if there's any final words on not using TypeORM, instead of Sequelize, they please comment now.

**Comment by Zeko369** [comment]
Tnx @allella for finding and pinging them :+1:

**Comment by ceciliaconsta3** [comment]
**$0.02:** As Quincy mentioned earlier, whoever is planning to perform the bulk of work on this should decide. Though if only a few are comfortable using said technology and if they get busy, it may be better to use something others are more familiar with to share the load. My experience using Sequelize is limited and non-existent in TypeORM. 

If we just need a final decision on this going forward, I say let's use Sequelize. I created a makeshipt poll in Discord if we're still uneasy picking one of the two (keyboard vs movie camera emoji)

**Comment by Zeko369** [comment]
We'll be using TypeORM
