### ISSUE TITLE
Auth: As an administrator, I can create a chapter

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/chapter#273]
Depends on https://github.com/freeCodeCamp/chapter/pull/814

Once that is done, we should lock this down to the approved roles and confirm via Cypress tests

- [x] As an owner I can successfully create a Chapter
- [x] As any other role, I cannot create a Chapter

The main thing to check is that requests from unauthorised users fail, but it's also helpful to confirm that the UI reflects their role.

**Comment by Zeko369** [comment]
Hey @madaleneaza-design, I also commented on the #270, we'll probably also add this tomorrow

**Comment by allella** [comment]
@Zeko369 most of the UI conversations have been on the _user_ side, like RSVP #278 and toggling on / off notifications #274 but if you want to start with _organizer_ UIs then @madaleneaza-design was about to work on new mockups.

**Comment by Zeko369** [comment]
I was looking at it from the API side, where we should first build a way to create chapters and events and then a way for users to join them. We'll work on that next week possibly also on twitch :wink:

**Comment by allella** [comment]
@Zeko369 we can start wherever makes sense. I was pushing on the _user_ side mainly because other issues assigned to me are related to the _user_.

**Comment by Zeko369** [comment]
We can do both asynchronously because we first need to build out an API and with that I was thinking about building really simple skeletons for testing it, and later adding design elements

**Comment by allella** [comment]
@Zeko369 however, from the conversation in #107 we did come up with [necessary schema changes to allow for subscribing to a _chapter_ vs an _event_](https://github.com/freeCodeCamp/chapter/issues/107#issuecomment-562432174), which is probably just adding a couple new fields to two tables.

Is that going to disturb the API work if we add those fields later vs now.

I can do a PR for those fields, but also wanted to #253 merged in to avoid merge conflicts.

**Comment by Zeko369** [comment]
No, it shouldn't we can add that later

**Comment by madaleneaza-design** [comment]
Hey @Zeko369, in response to your message on #270, unfortunately, there has not been any progress made on both this issue and #270.  As I have explained to @allella that I will create mockups that will meet the requirement of the UI issues. If I can, I will try to create a rough layout (even it just a wireframing), but it is enough to give you guys on the API side some ideas. However, I have zero experience (and probably 0l.1% understanding) of APIs, so once I upload my mockups on here, your feedback would be much appreciated if there is any concerns relative to API :)

**Comment by Zeko369** [comment]
Then we'll create the api routes and a bare bones skeleton on the frontend, and later add your designs

**Comment by allella** [comment]
Based on [today's meeting](https://github.com/freeCodeCamp/chapter/wiki/Meeting-Notes-February-9,-2020), and [earlier conversations on roles](https://github.com/freeCodeCamp/chapter/issues/296), we decided only an _administrator_ would be able to create new _chapters_.  So, I'm changing the title of this issue to reflect that decision.

**Comment by QuincyLarson** [comment]
Per our discussion on February 9, we are not going to let organizers create chapters in our MVP, so I am closing this issue.

**Comment by allella** [comment]
@QuincyLarson this was renamed to "As an admin" so it's probably still a valid MVP issue for the admin role.

**Comment by QuincyLarson** [comment]
@allella Thanks for confirming this. I've reopened the issue.

**Comment by Zeko369** [comment]
while(1) {
  issue.open = !issue.open;
}

**Comment by allella** [comment]
We[ just proposed having an additional _owner_ role to allow for certain things](https://github.com/freeCodeCamp/chapter/issues/296#issuecomment-585347150), like an owner would be the only one allowed to create other administrators.

Though, I suspect an _owner_ would additionally have the role of _administrator_ in the new `user_instance_role` table, so we likely don't need to do anything different on this issue on the account of an _owner_ creating a new _chapter_.

**Comment by allella** [comment]
@Zeko369  @timmyichen  you agree with the last comment?

**Comment by Zeko369** [comment]
Yes

**Comment by QuincyLarson** [comment]
@allella That's fine with me. We could say whoever creates the instance and signs in for the first time would be the owner, though in later versions, we'd want to be able to transfer this role to other people.

**Comment by allella** [comment]
@QuincyLarson, yes the owner is suggested to be a role in the database. So, user #1 isn't going to be baked in as the owner based on the current conversations.  We talked about a boolean on the `user` table as well, but using `user_instance_role` gives a lot more flexibility and would accomplish your use case of changing the owner, or even having multiple owners.

**Comment by allella** [comment]
The most recent conversation on [tables for roles](https://github.com/freeCodeCamp/chapter/pull/735#issuecomment-944167783) and a more [recent PR will likely inspire more about role tables](https://github.com/freeCodeCamp/chapter/pull/898#issuecomment-1027021196).

**Comment by ojeytonwilliams** [comment]
The role based auth is my next big focus, so I hope to get that done soon.  However, it's definitely feasible to implement this without the auth in place since it should be easy enough to restrict access to resolvers after the auth system is done.

**Comment by allella** [comment]
I know Oliver has a good handle on the auth and roles, but there are notable earlier links in the comments on this thread and also on https://github.com/freeCodeCamp/chapter/issues/743#issuecomment-946336061

Cross-linking things so those previous conversations are easier to find.
