### ISSUE TITLE
Wiki Fix: Add link to empty hyperlink for Meeting Notes on November 15, 2019

### ISSUE THREAD

**Issue by clarkngo** [freeCodeCamp/chapter#289]
Thanks, @allella for your guidance. As per our discussion and following on one of your suggestions:

> The "solution" is to basically clone the Chapter wiki repo so you have a full copy of the existing wiki files, then you make changes and push to your own fork copy, then submit an issue and someone with write access on Chapter would need to manually merge any accepted changes into the Chapter Wiki.  There's no support for pull requests on Wiki pages.

Let me know if this is a preferred way to contribute to the Wiki or the option of adding me with write/collaborator permissions, which @QuincyLarson can grant, is better.

The hyperlink as highlighted below redirects to the same wiki page.
![image](https://user-images.githubusercontent.com/30854108/70399123-4c2dff00-19d6-11ea-8a02-bc4f57c23491.png)

You can reference my cloned wiki's compare revision:
https://github.com/clarkngo/chapter/wiki/Meeting-Notes-November-15,-2019/_compare/e37f3b99a59b548895901e97289d3f4a51fb3c49

![image](https://user-images.githubusercontent.com/30854108/70399171-8c8d7d00-19d6-11ea-90a5-7794394ed2cb.png)

**Comment by allella** [comment]
Thanks. That link has been updated in the Wiki.

**Comment by allella** [comment]
https://github.com/freeCodeCamp/chapter/wiki/Meeting-Notes-November-15,-2019
