### ISSUE TITLE
Add html rendering for emails

### ISSUE THREAD

**Issue by Zeko369** [freeCodeCamp/chapter#290]
We should add a simple ejs renderer for sending emails so that we can do something like this
```typescript
async render(variables: IMailerParams, template: string) {
  const html: string = await ejs.renderFile(
    `src/services/mail/templates/${template}.html.ejs`,
    variables
  );

  return html;
}
```
and then have something like this in the template
```ejs
<html>
  <body>
    <h1>Welcome <%= username %></h1>
  </body>
</html>
```

**Comment by Zeko369** [comment]
Or use something like https://github.com/forwardemail/email-templates

**Comment by allella** [comment]
#274 will need this functionality to insert placeholders for opt-out links, among other thing.

**Comment by Zeko369** [comment]
Ok we'll discuss this during the meeting today

**Comment by QuincyLarson** [comment]
I propose we discuss this after we ship the MVP. In my humble opinion this is not MVP.

The moment we introduce HTML, organizations will start asking for ways they can customize it.

Plain text has higher deliverability/open/click-through than HTML.
