### ISSUE TITLE
Add an API route in swagger.json for fetching all the events of an organization

### ISSUE THREAD

**Issue by vkWeb** [freeCodeCamp/chapter#297]
Create a route in swagger.json file: GET /events to fetch all the events of an organization. 

More routes can be added as we develop and find needs for them.

**Comment by AryanJ-NYC** [comment]
We should be explicit in the title that this is `swagger` specific.

**Comment by vkWeb** [comment]
@AryanJ-NYC agreed. I have updated the title.

**Comment by jakesweb** [comment]
I'll pick this one up if still needed.

**Comment by allella** [comment]
@jakesweb  @nik-john can likely answer questions on Swagger if/as needed.

**Comment by jakesweb** [comment]
It looks like there is already a route for this. Line 387 of the swagger.json file has a route for `/chapters/{chapterId}/events`

**Comment by vkWeb** [comment]
@jakesweb `/chapters/{chapterId}/events` is to fetch a chapter's events. 

We'll have an organization consisting of chapters under it. 

In our homepage and events page, we will show all the upcoming events of an organization for which we will need a route I believe.

**Comment by jakesweb** [comment]
That makes sense. I'll start looking into getting that setup.

**Comment by vkWeb** [comment]
@jakesweb Any updates on this?

**Comment by xarrijorge** [comment]
Is this still open?

**Comment by Zeko369** [comment]
We're going to refactor this because we agreed on a simpler setup in discord for the MVP, so closing for now
