### ISSUE TITLE
Integrating Storybook for Figma Mockups

### ISSUE THREAD

**Issue by Shub1427** [freeCodeCamp/chapter#301]
## Suggestions
As we are maintaining our own UI Designs, it is best to have a UI documentation for our Development. __I am not sure if this has to be a part of MVP__, but it is very good to have UI documentation for UI components, so as to make them re-usable and separate data specific and view specific components.

[Storybook](https://storybook.js.org/) is a very good tool to document UI components, that can be re-used across our project. There are other tools like [docz](https://www.docz.site/), based on [mdx](https://mdxjs.com)(NextJS supports it as plugins), as well, but they are more centric towards interactive presentation of UI Components and other advance documentation.

I am suggesting something like:

- https://airbnb.io/react-dates
- https://zeit.co/design (This is an overkill for our MVP, but still things can be progressively improved, later on)

## Benefits

This way of development promotes Component Driven Development, which IMO is better than TDD, specifically for UI Development. Also, this way it would be more easier to showcase our Designs interactively and determine what particular components should be used throughout our project, not modifying the css styles (unless really necessary).

This also helps to parallely work on UI, even if APIs are not ready, but designs are. If APIs are not ready, we can still work parallely using some mock-servers, but that's a totally different concern.

> If people support this way of development, I would happily step up to set it up and help others (if needed) to develop UI components.

**Comment by AryanJ-NYC** [comment]
This may be overkill for a small project like this. However, I'm also not a designer so take this with a grain of salt.

How does Storybook help designers? Can Figma integrate directly with Storybook? Will that accelerate the progress of this project?

**Comment by Shub1427** [comment]
It won't speed up the project progress, but it will help maintaining and managing the UI designs easier in code.

If designers know coding or vice-versa, it's a great tool. AFAIK, many people in our team, who are designers, know coding as well.


https://github.com/hharnisc/storybook-addon-figma

Above link is not exactly a tool to get auto-generated React components out of Figma designs, but a tool to help create React Components faster keeping Figma ref side-by-side.


Since, it's integration doesn't affect our development process, I thought of suggesting it to everybody else here.

**Comment by allella** [comment]
@Shub1427 if you're willing to create a PR with a real world example of the benefits then that might help bring more folks on board.

**Comment by vkWeb** [comment]
#312 was closed so we should close this issue as well. A big shout out to @Shub1427 for taking the time to introduce all of us to Storybook.
