### ISSUE TITLE
[WIP] Refactor swagger

### ISSUE THREAD

**Issue by Zeko369** [freeCodeCamp/chapter#304]
- GET `/chapters` to list all chaptes is missing
- remove `id` from POST `/chaptes`

Separate events from chapters

**Comment by vkWeb** [comment]
@Zeko369 #296 is being worked upon by @jakesweb which is swagger specific. 

The above changes you suggested can be made too if @jakesweb is ready to deal with all this. 

What do you say @jakesweb?

**Comment by jakesweb** [comment]
Yes. I can pick this up once I have #297 completed.

**Comment by QuincyLarson** [comment]
We will create a new GitHub issue and PR to reflect the big changes in how our API works. I'm closing this for now.

**Comment by Zeko369** [comment]
We moved to GQL
