### ISSUE TITLE
As a user I can log in or register via Google OAuth 2.0 authentication.

### ISSUE THREAD

**Issue by allella** [freeCodeCamp/chapter#306]
[The consensus was to split the authentication piece out](https://github.com/freeCodeCamp/chapter/issues/110#issuecomment-566281560) authenication from the RSVP issues(#110 and #278) 

The API / code issue was split to #305.

**Comment by QuincyLarson** [comment]
I recommend we just put this button in the navigation bar and when people click it, they are immediately taken to Google to give permissions, then redirected back to our root (/) route.

![sign in with Google button](https://user-images.githubusercontent.com/5500716/57735626-940ed100-76e8-11e9-8444-1a7ae461e92a.png)

**Comment by megajon** [comment]
Am I able to assign this issue to myself since it's part of the prototype I'm working on?

**Comment by allella** [comment]
Thanks @megajon  

@vaibhavsingh97  and #305  are related to this on the code / backend / API side so I suspect he can assist with the technical considerations.

**Comment by vkWeb** [comment]
@megajon Great - we will love to see your work on this :) Please keep us posted with screenshots.

**Comment by allella** [comment]
@vaibhavsingh97  @megajon for #353 Quincy wanted us to document the initial setup steps for the _owner_ of each **Chapter** _instance_. 

We'd previously linked to the [Google Sign-In for Websites documentation](https://developers.google.com/identity/sign-in/web/sign-in).  Is that the best starting point for this group to use, or is there a better resource?

**Comment by allella** [comment]
Also, Quincy closed #305  and I'm copying over comments from it so they don't get missed.

https://github.com/freeCodeCamp/chapter/issues/305#issuecomment-570073590
> yes, We don't want SSO/SAML, we just need OAuth to authorize the user on our platform. Here, we will use google as OAuth
> 
> For those who are wondering what is the difference between OAuth and SSO?
> OAuth is an authorization protocol that allows users to selectively pick permissions to authorize services to use their data. For example, Gitlab uses Github to authorize the user on their platform, once you try to signup using Github, you will be redirected to GitHub to authorize Gitlab to use your personal details and authorize.
> 
> Whereas SSO is not a protocol, you can assume it as a flow for authentication /authorization so that you can use the same credentials to authenticate various services. For example, you can use Google Auth, to authenticate a user to Microsft Office, Github, or other apps. The benefit of using SSO is that they have to remember only a single account username and password, which helps them to authorize in multiple accounts. Basically, SSO also help the organization to manage users in their org

https://github.com/freeCodeCamp/chapter/issues/305#issuecomment-569795505
> I don't think we actually want SSO, we probably just want to use google oauth - easy to use with passport: https://github.com/jaredhanson/passport-google-oauth2

**Comment by AryanJ-NYC** [comment]
How are we doing with Google OAuth keys? I think we need to register this application to get some, eh?

**Comment by Zeko369** [comment]
I think that it would be best if everyone got their own keys for this.
We don't have google auth setup yet, but if you're interested in working with @timmyichen on setting up passport.js and google auth you're free to help

**Comment by AryanJ-NYC** [comment]
Ah, d'oh. I didn't know this was in progress.

**Comment by pdotsani** [comment]
@QuincyLarson @allella @Zeko369 So I did a little research and it looks like developers are leveraging the chrome api to get the google auth popup to show. The api seems fairly straightforward and I'll start digging into it, but it looks like we'll need the traditional auth pattern as a backup. Should I make a pr with the traditional auth then iterate with another pr to the chrome api auth? Or should we do it all at once?

**Comment by allella** [comment]
I don't have an opinion.  If you don't hear from  Fran or Quincy by tomorrow, then feel free to do what you think makes sense.

**Comment by ankorGH** [comment]
hey @allella @pdotsani what's the status of this issue. I will like to work on it.

**Comment by pdotsani** [comment]
@ankorGH I have a working branch for the feature [here](https://github.com/pdotsani/chapter/tree/feature/passport-google-auth0). I have the passport library with google and oath2 working. Currently working on getting the one tap authentication method to communicate with the backend (authenticatie the token, serialize user etc.). I can give you more details if you wanna dm me on discord.

**Comment by ankorGH** [comment]
@pdotsani I will look into taking another issue unless you need help with it.

**Comment by allella** [comment]
@vkWeb was asking about Passport, so pinging him on this issue.

**Comment by vkWeb** [comment]
@allella I was reading the FAQs on wiki,

```
Are there any dependencies or 3rd party services involved?

Authentication: Auth0 will be used an will only support Google logins / authentication for the 
                early releases of Chapter.
``` 

There it was mentioned that we will be using Auth0 for authentication but I was of the opinion that we would be going ahead with passport that's why I confirmed on Discord whether we are using passport or Auth0.

I looked at @pdotsani's branch, he has done some good work on the authentication side using passport and Google's OAuth API. We will soon see a PR I hope :)

@allella we should update the FAQ. I think we are not going to use any third party for authentication.

**Comment by allella** [comment]
@vkWeb  thanks. The FAQ was written months ago and I agree it can/should be updated.  If you or @pdotsani want to write up a sentence about the Passport dependency, then I can update the FAQ.  I'm assuming this is Passport or Passport.js with OAuth, but I'm sure you two would be able to provide a better description since I'm not familiar with the package.

**Comment by vkWeb** [comment]
@allella Yeap, I'll update the FAQ.

**Comment by allella** [comment]
Closing since the direction changed to using email-based authentication on #437.
