### ISSUE TITLE
Migrate from Speccy to SwaggerUI

### ISSUE THREAD

**Issue by Zeko369** [freeCodeCamp/chapter#325]
Speccy has some vulnerabilities that bug us every time we run `npm install`, also it could be organised better like Swagger for example.

So back in [December](https://github.com/freeCodeCamp/chapter/wiki/Meeting-Notes-December-15,-2019) we decided to us SwaggerUI.

We could probably use something like [SwaggerUIExpress](https://www.npmjs.com/package/swagger-ui-express)

**Comment by estebanborai** [comment]
Hey @Zeko369 ! Im interested in helping out with this!

**Comment by Zeko369** [comment]
Go ahead @estebanborai, if you have any questions feel free to ask them here or in the discord

**Comment by Zeko369** [comment]
Hey @estebanborai, @AshNaz87 started work on this. Have you done something, could you guys collaborate on this if you had done something?

**Comment by estebanborai** [comment]
Hey!

Sorry I wasn't able to work on this because of time issues.

Please assign @AshNaz87 this issue. I will be collaborating when I find
some spare time!

Thanks for your time guys!

**Comment by estebanborai** [comment]
Assign @Zeko369 in my place!
Thanks!

**Comment by ceciliaconsta3** [comment]
@Zeko369 have you started working on this? I'd like to take this beginner-friendly issue
