### ISSUE TITLE
High Level Architecture Diagram 

### ISSUE THREAD

**Issue by 3piecechickendinnerTB** [freeCodeCamp/chapter#328]
Creating an issue to discuss the current High Level Architecture Diagram document that I have created. 
[Chapter High Level Architecture .pdf](https://github.com/freeCodeCamp/chapter/files/4183831/Chapter.High.Level.Architecture.pdf)

**Comment by MihirSomani** [comment]
Could you provide more details on why you chose Port 8000 and Port 8001 in the "Web Application Container"? And, what does the term "Web Application Container" mean? Do you mean the container serving the front-end?
Also it's definitely a good idea to have public facing traffic running on HTTPS (Port 443).

**Comment by Zeko369** [comment]
`Web Application Container` refers to the docker container hosting our app, that would be a next.js app (if you're not familiar with next, it's ssr implementation for react, think express+react), which also has all of our api routes
The port it 8000 for dev purposes.

Also @3piecechickendinnerTB we removed speccy from there so no need to have a service with 8001 any more

**Comment by 3piecechickendinnerTB** [comment]
Noted, I will remove the reference to speccy

Best,
Saritta
Chief Executive Officer
TrustaBit - Digital Vouchers. Simplified
Mobile: 949.205.3790
Saritta@trustabit.io
www.trustabit.io<http://www.trustabit.io>


Please do not rely on emails sent to or received from this office detailing bank account or other payment details without direct verbal confirmation from ourselves.

________________________________

**Comment by QuincyLarson** [comment]
For now we are just hosting a node service and a database on our MVP so we don't need to include an architectural diagram like this.
