### ISSUE TITLE
Frontend libs

### ISSUE THREAD

**Issue by bhoomij** [freeCodeCamp/chapter#34]
As per finalised tech stack frontend will be "React using JavaScript (not TypeScript) and CSS (not Sass)"

Would like to discuss on which packages/libraries are best suited with react echo system ?

Will use any boilerplate ?
1. create-react-app
2. https://github.com/react-boilerplate/react-boilerplate

These two almost provides readymade support for transpiring and bundling and makes app production ready from day one.

Other useful packages I would like to add:
1. Reselect  : Provides memoization and avoids wasted renders. [More](https://github.com/reduxjs/reselect)
2. Redux: App state management
3. Redux-saga : For asynchronous call, uses generators and provides some good features like take_latest. Check [Redux-saga](https://redux-saga.js.org) and [redux-thunk-vs-redux-saga](https://medium.com/@shoshanarosenfield/redux-thunk-vs-redux-saga-93fe82878b2d)  
4. React-intl: Refer https://github.com/freeCodeCamp/chapter/issues/21

Would like to hear community thoughts and experience with this and any other useful packages, we can include in frontend tech stack

**Comment by Utkarshbhimte** [comment]
Given the requirement, I think a server side rendered app would be more beneficial for SEO

**Comment by Zeko369** [comment]
@Utkarshbhimte We already said that Next will be used, so create next app?

**Comment by Zeko369** [comment]
Also IMO if we use Redux we should use ReduxThunk because it's easier to get into for people who havent working with it in the past, and is generally more widely used lib

**Comment by pabloHoc** [comment]
Are we going to use some UI library? If so, I'd like to propose [Chakra-UI](https://chakra-ui.com/), it's a really simple and composable component library crafted  with accesibility in mind and uses [emotion](https://emotion.sh/docs/introduction) and [Styled System](https://styled-system.com). It's also OS.

**Comment by aeganaden** [comment]
For UI Library, i would like to suggest [React Ant Design](https://ant.design/). It has a rich set of components ready to be used, and unlike other component library its UI is sorta new to other users.

**Comment by isubasinghe** [comment]
I think redux is a must for any non trivial application with state. It just makes doing React state management much much easier.

**Comment by mohanwer** [comment]
Thoughts on using formik & yup for form validation? Both are well documented / supported libraries that go well on creating forms for providing clean user input.

**Comment by MirzaChilman** [comment]
We already agreed to use next.js you can see the discuss [here](https://github.com/freeCodeCamp/chapter/issues/17) 

@isubasinghe as for state management, we still haven't figured it out whether to use it or not, as we are still blind here

**Comment by sinharaksh1t** [comment]
If we do consider using Redux for application state management, then it's worth giving [redux-query](https://github.com/amplitude/redux-query) a read. It's a seamless way to manage the network state into your Redux store.
Also, any API calls made through `redux-query` goes into your Redux state along with the network state of the call. Rendering it pretty useful when showing different UI feedbacks if the API call were to fail, is in-flight or succeed with delay.

**Comment by MirzaChilman** [comment]
Never heard of redux-query, anyway probably we should list what kind of libs that we are going to use, at least we can discuss the pros and cons of each libs

**Comment by Wizyma** [comment]
Redux-saga is really hard to grasp, specially for people not that experienced in JavaScript... 
There is others tools to use.
In my company we use it for our main app, it works well no doubt, but only few can really maintain it and **understand** it. 
When it comes to async calls, it is way overkill to use redux saga if it isnt for critical reasons.

**Comment by Wizyma** [comment]
@bhoomij  for i18n there is [i18next](https://react.i18next.com/) too.
It is mature, a lot of support and a gold documentation.

**Comment by keeth** [comment]
I've had a lot of success with [Material UI](https://material-ui.com/), however that would mean ditching CSS for JSS.

**Comment by Wizyma** [comment]
and for others libs: 
[styled-components](https://www.styled-components.com/) for styling
[react-redux](https://redux.js.org/) for global state management no doubt
[material-ui](https://material-ui.com/) as an UI lib ? customizable and quite powerfull
[testing-lib](https://testing-library.com/) for testing components
[ramda](https://ramdajs.com) for utils and FP

**Comment by keeth** [comment]
If Redux is used carefully and appropriately it can be good but it can also get messy, I've seen large project turn into spaghetti by relying too much on Redux, especially around keeping the DB/server state in sync with the client state.  GraphQL solved this for me but I know we're not doing that for v1 of Chapter.  Worth looking at all the alternatives.  Hooks, Context, [unstated](https://github.com/jamiebuilds/unstated), URL state, etc.

+1 for Ramda, it's so great.

**Comment by keeth** [comment]
I assume most people use Moment for date/time calculations.  I've recently started using [date-fns](https://date-fns.org/) and quite like it.

**Comment by mquadrant** [comment]
> I assume most people use Moment for date/time calculations. I've recently started using [date-fns](https://date-fns.org/) and quite like it.

date-fns is referable, personally. You could imagine the space moment import eats up.

**Comment by nsharma1396** [comment]
We can consider using [Immer.js](https://immerjs.github.io/immer/docs/introduction). It can help to work with immutable states in a very clean and easy way. Helps a lot to avoid *accidental state mutations* and makes the app more predictable I believe. It's quite good for managing complex state objects or redux state and is very easy to learn and use.

**Comment by H-Plus-Time** [comment]
[linaria](https://github.com/callstack/linaria) is a drop-in replacement for styled-components, it tends to produce lighter JS bundles (in exchange for statically generated css) and more performant instances (setting CSS variables is exceedingly fast).

**Comment by pabloHoc** [comment]
I think Ramda is too much for the moment, since introduces a complexity for those that are not used to FP. The idea is to keep this as simple as posible.
The stack decided was CSS for styling, so that leaves out styled-components and most UI libraries (including Chackra UI, my bad).

**Comment by viniarruda** [comment]
> and for others libs:
> [styled-components](https://www.styled-components.com/) for styling
> [react-redux](https://redux.js.org/) for global state management no doubt
> [material-ui](https://material-ui.com/) as an UI lib ? customizable and quite powerfull
> [testing-lib](https://testing-library.com/) for testing components
> [ramda](https://ramdajs.com) for utils and FP

I use the Material Ui in a large scale software and I had a lot problem to customize the components, I prefer the ant design for use here

**Comment by MirzaChilman** [comment]
@corlaez I strongly agree with him, because if we structure our app properly then actually we don't need redux, I've seen project using redux and confusing for new comer, and slow down development, as new comer spend more time understanding the redux instead developing the features

**Comment by mquadrant** [comment]
In as much we would be writing the CSS without any library. Styled component is a very good plugin that would help writing the style of any component in Js. Every reusable component should have its styles embedded in the Jsx file not an external file , this will ensure that we don't bother too much on maintaining extra style sheets especially when the project is becoming large.

**Comment by Danex2** [comment]
@mohanwer I just found [React Hook Form](https://react-hook-form.com/) recently and I think it would be a lot easier to work with than formik. It has its own validation out of the box or you can use yup.

**Comment by SandipNirmal** [comment]
What about using [Semantic-UI](https://react.semantic-ui.com/) with Styled component. Or we can also use ionic which has recently added React components. https://ionicframework.com/blog/announcing-ionic-react/

**Comment by kognise** [comment]
All of these are great suggestions, but I feel like we shouldn't try to solve problems we don't already have - if we need a library we can find it.

**Comment by PrestonElliott** [comment]
I think for MVP we should stick to React, React-Bootstrap, and CSS. We can add additional libraries and functionality for future releases, but MVP should be achievable in the near future!

We could implement container components to create event cards, add test users, and be able to demo the app.

After MVP, it'd be beneficial to refactor into React-Redux as the app scales.

**Comment by francocorreasosa** [comment]
TBH I think this can be easily solved with [Next.js](https://nextjs.org) (no extra state management, SSR) and [Bootstrap](https://getbootstrap.com) or [Chakra UI](https://chakra-ui.com).

**Comment by Wizyma** [comment]
Everyone talking about bootstrap, but nobody talks about design système , the rebass lib ? 

And i saw some comment saying they had bad experience with material-ui please share why ! 
Just saying no "i didnt like it" makes no sense! 

I'll Start: i am using material ui since V1 in my company wich is one of the biggest french company, with more than 800 software engineer. 

In the begining material ui was not friendly at all, v1 and v2 had a lot of issues, but now the community and the core members did a lot of work to make things more maintenable, 
V3 was a huge step forward, with an api who was more clear, and they stayed in the same track with v4 who is killing it. 

But still i am not a huge a fan of the lib **JSS** they are using but except for that, perfs are now good, the Doc is gold, they implemented design system, the community is huge and reactive!  

When we talks about libs to use in this kind of project, i think we have to ask ourselfs the impacts and why it would make life of everyone easier.

Personnaly seeing react-boostrap feels like seeing people asking for JQuery :scream:
But thats my personnal opinion 😬 !

But for the rest share your experiences with some pro and cons, that will make the debate more open to discuss about it. 

Thanks !

**Comment by MirzaChilman** [comment]
I hope this helps, but I'm gonna list out every libs here that already been mentioned above, and we can decide it later which one will be used, as for this moment we are still blind

Design System 
- [Material ui](https://material-ui.com/)
- [Reactstrap](https://reactstrap.github.io/)
- [Ant design](https://ant.design/docs/react/introduce)
- [Chakra ui](https://chakra-ui.com/)
_please be mind that we are just gonna using CSS, which some of UI libraries above should not meet any requirements, but we're gonna talk about this later_

State Managements:
- [Redux](https://redux.js.org/) (Redux-thunk, Redux-query)
- [Mobx](https://mobx.js.org/)
- [Immer.js](https://github.com/immerjs/immer)

Translation
- [React i18n](https://github.com/i18next/react-i18next)

Date:
- [Date-fns](https://date-fns.org/)
- [DayJs](https://github.com/iamkun/dayjs)

Forms:
- [Formik](https://jaredpalmer.com/formik/)

Again we are pretty much blind here, so thinking of what libs should be used, isn't the priority right now, if someone can come up with a mock up based on the existing [schema](https://github.com/freeCodeCamp/chapter#schema) and [routes](https://github.com/freeCodeCamp/chapter/pull/46/files), I think it will be much helpful to think what kind of libs we are going to use

**Comment by QuincyLarson** [comment]
> All of these are great suggestions, but I feel like we shouldn't try to solve problems we don't already have - if we need a library we can find it.

100%. But we need to keep maintainability in mind. How hard is it for a potential contributor to get up-to-speed and able to update the codebase?

freeCodeCamp started out using a lot of tools, and over the years, we've stripped most of them out because they made it harder for people to contribute to the codebase.

Also, some of the tools listed on this thread are likely to become deprecated in the coming years. This is hard to predict. But it can lead to a lot of additional maintenance work.

This is a long-term project that organizations will use for decades to come.

The initial time spent building this project may only be 20% of the total work. The rest will be spent doing maintenance, so we should be sure to optimize for that.

**Comment by wuilliam321** [comment]
Agreed, from zero to hero. xD from simlpe to complex. We don't need a big stack at the begining.

**Comment by vkWeb** [comment]
@QuincyLarson Yes. Perfect! That's what I was thinking. 

I would recommend starting with a basic stack as already mentioned on README and then we can always add more tools in the future. Let's kick off this project asap instead of getting confused with stack & design. :)

**Comment by abidRahim** [comment]
> For UI Library, i would like to suggest [React Ant Design](https://ant.design/). It has a rich set of components ready to be used, and unlike other component library its UI is sorta new to other users.

If it's just for MVP then it'd be a good choice.
However, React Ant Design will have issues with i18n (Internationalization)  and localization for future prospects. I've had hard time figuring things out with it, if anybody has a way around it, I would like to hear it.

**Comment by keeth** [comment]
yes, everyone loves sharing their fav stack and tools, and their horror stories ha ha (me included)

i defer to the coding education experts on this! :)

excited to break ground. go team!

**Comment by allella** [comment]
https://github.com/freeCodeCamp/chapter/issues/76 is asking about testing.  Should that conversation remain independent of this one, or shall we merge them?

**Comment by vkWeb** [comment]
@allella Let it be a different issue.

**Comment by Lobarr** [comment]
I think it should be a different issue as testing applies to the backend too.

**Comment by keeth** [comment]
@shirakaba I love this idea.  I'm taking a similar approach with one of my projects at work and I think it makes a lot of sense. One codebase to rule them all! :)

**Comment by QuincyLarson** [comment]
@shirakaba We can consider mobile UI options once we've built the web version for our MVP. I think React makes the most sense here so I'm going to go ahead and close this issue.

**Comment by allella** [comment]
RE: UI frameworks

#114 (part of the roadmap) holds some of the UI framework conversation, along with #121 and this issue.

Also, [Quincy's vote was for using a UI framework to start](https://github.com/freeCodeCamp/chapter/issues/114#issuecomment-546661502) and not custom-building from the start.
> we can just grab a framework off the shelf and use it for our MVP, then write our own custom, more-optimized UI code later.

**Comment by shirakaba** [comment]
@Quincy 

> We can consider mobile UI options once we've built the web version for our MVP. I think React makes the most sense here so I'm going to go ahead and close this issue.

React Native Web and React DOM are both “React”; just that the former transpiles to React DOM while the latter *is* React DOM. For clarification, are you talking about going ahead with direct use of React DOM?
