### ISSUE TITLE
Swagger.json validation

### ISSUE THREAD

**Issue by NorthDecoder** [freeCodeCamp/chapter#347]
Requesting guidance for testing the Swagger file.

api/swagger.json [:link:](https://github.com/freeCodeCamp/chapter/blob/master/api/swagger.json)
Paste (or import URL) the above [raw](https://raw.githubusercontent.com/freeCodeCamp/chapter/master/api/swagger.json) `swagger.json` file into Swagger [editor](https://editor.swagger.io/) to see the errors listed.

What is the project/repository standard for testing the validation of the swagger.json file?  Maybe file docs/api/[APIv1.md](https://github.com/freeCodeCamp/chapter/blob/master/docs/api/APIv1.md) could have comments discussing the test.

**Comment by Zeko369** [comment]
I'm on my phone, could you please paste a screenshot of the error?

**Comment by Zeko369** [comment]
Nevermind I got it working on my phone

**Comment by Zeko369** [comment]
I know that #348 doesn't really answer your question, but it fixes the bug described. I haven't heard of any swagger.json testing utils that would tell us if we had a swagger syntax problem

**Comment by vkWeb** [comment]
I also haven't heard of any testing lib for swagger files. I believe we won't be changing the swagger file too much. So it's not much of a concern. 

@NorthDecoder If you are aware of any testing lib for swagger and interested in helping us integrate it then we'll love to see a PR. Btw, thanks for reporting this 😄 

Closing as resolved with #348.
