### ISSUE TITLE
Howdy folks!

### ISSUE THREAD

**Issue by shivaprabhu** [freeCodeCamp/chapter#35]
Fullstack dev. from Bangalore, India. Work on React, Postgres, Node, dangling a bit with Docker, K8s, Monitoring lately. Hope to contribute and learn. Godspeed!

**Comment by allella** [comment]
If you can post this on #11 then that's the best place for this info so it doesn't get lost.

**Comment by shivaprabhu** [comment]
> If you can post this on #11 then that's the best place for this info so it doesn't get lost.

I did as soon as i realised this wasn't the place :)
