### ISSUE TITLE
Documentation Describing How to Create a Google API Key for Auth

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/chapter#353]
We need to create documentation - with screenshots - for how to create a Google API Key for authentication. We will store this in our .env file.

When admins do their initial install of Chapter, they will configure this as part of the onboarding.

**Comment by allella** [comment]
This question has been stubbed out and added to the [Owner FAQ](https://github.com/freeCodeCamp/chapter/wiki/Owner-FAQs).

I'll confirm if https://developers.google.com/identity/sign-in/web/sign-in is the correct documentation for use to use to create our own docs.

**Comment by allella** [comment]
@QuincyLarson do you want me to leave this open, or is the [stub in the Wiki](https://github.com/freeCodeCamp/chapter/wiki/Owner-FAQs) good enough to remind us to do it when we fill in the docs?

**Comment by QuincyLarson** [comment]
@allella Thanks. That note on the documentation will suffice. I'm closing this this issue.
