### ISSUE TITLE
As an owner, I will receive feedback if the 3rd-party transactional email service hasn't been configured

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/chapter#354]
As an owner, when sending the first email through whatever email service I've enabled, I should see a message that says "If you didn't receive an email (check your spam folder, too), read this documentation" that links to the email setup documentation.

**Comment by allella** [comment]
Updated this to reference "owner"

**Comment by allella** [comment]
Closing since this has been tagged "Roadmap" for post-MVP implementation.
