### ISSUE TITLE
As an owner, if a Heroku environment variable is missing, I should see a page with a warning and link to documentation

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/chapter#355]

**Comment by allella** [comment]
Changing this to "As an owner", since I don't know that the administrator(s) will have access to the Heroku settings.

The "owner" term was just merged in on #352

**Comment by allella** [comment]
@bappyasif @ojeytonwilliams may have more guidance on where in the code we could check for missing .env variables.

I believe the intention is for the front-end UI to show a warning.   There are already some warnings on the command line, but I think the assumption is that Heroku users may be trying to avoid the command line.

In previous conversations, we intend to use Heroku as an MVP, but I'm not sure this issue needs to be specific to only Heroku.  We should probably show a warning message for any undefined variables and we can link to the [.env section of our documentation](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md#env-configuration-file) and perhaps that section of the docs could link off to the Heroku specifics.

**Comment by ojeytonwilliams** [comment]
> Heroku users may be trying to avoid the command line.

I'm not 100% sure what a typical user expects when deploying to heroku.  However, if I just follow their instructions I'd clone the repo and then

```
git push heroku main
```

At this point Heroku will output a bunch of logs straight to your terminal.  Right now it says (amongst other things)

```
remote: -----> Build succeeded!
```

Then, when I open the app, I see a boilerplate page telling me there is an application error.

So, I think we want three things to happen. 

- the build itself should fail without the environment variables, if the install process throws an error the build will stop
- the console should tell the owner which environment variables are missing or invalid
- the console should link to the .env section, as Jim mentioned

By invalid, I mean that it's obviously wrong.  For example, using the `JWT_SECRET` from the `.env.example` should immediately fail the build.

In principle we *could* create a warning page, but I think it would be better to prevent obviously broken deploys, if possible. What do you reckon, @allella?

I agree that this shouldn't be tied too closely to Heroku, but a step in the build that throws an error should stop most pipelines.

**Comment by allella** [comment]
I think @Zeko369 inspired this issue, so perhaps he has comments on where to show an error for the Heroku _owner_ of an instance.

**Comment by allella** [comment]
Closing since this has been tagged "Roadmap" for post-MVP implementation.
