### ISSUE TITLE
Sync package.json and docs

### ISSUE THREAD

**Issue by AryanJ-NYC** [freeCodeCamp/chapter#357]
### Describe the bug:

`package.json` has as config:
```json
"engines": {
  "node": "13.x",
  "npm": ">= 6.0.0"
}
```

`README.md` explains: _ Ensure you are installing Node 10 or greater and npm 6 or greater_.

These two are out of sync.

Should `package.json` or `README.md` be updated?

**Comment by Zeko369** [comment]
README.md should be updated, but there is a lot of docs/setup changes in the readme. I'm working on them locally will push it up in a couple of days.

But till then you can go ahead and fix this if you'd like to.
