### ISSUE TITLE
Feature Dev - RSS feeds

### ISSUE THREAD

**Issue by mrrcollins** [freeCodeCamp/chapter#36]
RSS feeds would be invaluable, especially if they could be constructed from tags or categories. So I could subscribe to all of the events, or just events tagged with php. This could also be used to feed other Chapter sites.

**Comment by iPwnPancakes** [comment]
This might aid in what was asked in #33

**Comment by allella** [comment]
There's bee a good deal of "federation" conversation, concerns and questions on Github.  While it may not be a v1 feature, it's probably something that impacts v2. Should/could we expand this Issue to cover short and long term ideas for sharing data, users, and such between instances so we have a place to send the frequent questions?

**Comment by allella** [comment]
@JacksonBates  posted this along those lines.

> One idea I had was an ActivityPub implementation to allow the alternative to live in the fediverse (like Mastodon, peer tube etc). This would allow easy and cheap self hosting, with the benefits of federation

**Comment by iPwnPancakes** [comment]
@allella We could set up webhooks early on for events, though this leads to questions such as:
- What if a user would not like their information to be included in a webhook's response?
- How should we handle rate limiting?

With webhooks, we could aggregate these responses into a single resource.

**Comment by allella** [comment]
@iPwnPancakes I suspect most Collectives would only care about some small number of others based on a common factor: location, industry, technology, etc, so if each Collective has an option to expose some bits of info to all others then that may limit the traffic.

I suspect in other cases some sites might want to aggregate a larger set of info from multiple collectives. 

For instance, I could see having a Collective for the tech community in Greenville, SC and then perhaps there are other Greenville, SC oriented Collectives for different context.  But, someone in Greenville might like to have a "Calendar of All the Things".  Or, if each major city in South Carolina had it's own Collective(s) then someone could create an app to pull in "chapter" and "event" info from the ones they care about and publish that info as an index for their area of concern.

That wouldn't really impact the individual collectives besides they might decide to share their data or not, and the rate-limiting DDOS concerns you mentioned.

**Comment by allella** [comment]
Then, you might have something like Free Code Camp that wants to advertise or build a site to index and promote all their "chapters".  In that case, they'd have the option to either to have all FCC Chapters on their own Collective.  Or, you might have FCC camps to be part of another Collective, perhaps a local community. In that case the local community would probably want access to Collective data for their local FCC Chapter.

It's going to happen both directions so I guess the trick would be to have public APIs, webhooks, RSS, [WebSub](https://w3c.github.io/websub/), or alike.

**Comment by allella** [comment]
[An example of this is how we're currently pulling Meetup.com and Eventbrite.com event data from their APIs and then normalizing and syndicating that data](https://github.com/codeforgreenville/upstate_tech_cal_service) to allow others to build apps using near real-time data.   Then, we have a number of apps, like [Hackgreenville.com](https://github.com/codeforgreenville/upstate_tech_cal_service), which promote the data that lives in APIs across the web.

**Comment by QuincyLarson** [comment]
I've added this feature to our roadmap and am closing this issue for now until we ship our MVP.
