### ISSUE TITLE
Documentation: Consolidate Technical Documentation

### ISSUE THREAD

**Issue by allella** [freeCodeCamp/chapter#360]
Quincy suggested all [technical docs go into CONTRIBUTING.md on the Jan 25 2020 meeting](https://github.com/freeCodeCamp/chapter/wiki/Meeting-Notes-January-25,-2020#re-orientation-and-design-overview).

- [x] 1. Move https://github.com/freeCodeCamp/chapter/tree/master/server/docs to CONTRIBUTING.md
- [x] 2. (edited) Move https://github.com/freeCodeCamp/chapter/blob/master/docs/how-to-open-a-pull-request.md into an collapsed / expandable section within [Step 4 of the CONTRIBUTING.md](https://github.com/freeCodeCamp/chapter/blob/master/CONTRIBUTING.md#step-4-proposing-a-pull-request-pr) 
- [x] 3. We can delete /docs/ directories, except /images since it's only general stubbed out stuff from really early on.
- [x] 4. Is there a better place to store CONTRIBUTING.md screenshots than in /docs/images?  If not, then do we want to rename it.
- [x] 5. As with the "Step 4" note above, we can / should use expandable sections in CONTRIBUTING.md to make certain sections not take up as much space until someone clicks to expand.
- [x] 6. @Narutuffy was looking to get involved and I thought it could be an easy first contribution 
- [x] 7. has Docker setup and is more familiar with the stack than I am, so he may be able to add other tips or improvements to CONTRIBUTING.md on the technical side. - Closed via #396 
- [x] 8. This also begs the question of if some of the README.md technical documentation is better in CONTRIBUTING.md. These sections of the README may be better in CONTRIBUTING.md: [Schema](https://github.com/freeCodeCamp/chapter/blob/master/README.md#schema), [API Specs](https://github.com/freeCodeCamp/chapter/blob/master/README.md#api-specification
), [Testing](https://github.com/freeCodeCamp/chapter/blob/master/README.md#testing) - Closed via #397

**Comment by allella** [comment]
The /docs/images and docs/how-to-open-a-pull-request.md are used or linked to from within the CONTRIBUTING.md, so we don't want to delete them without consolidating.

Quincy had suggesting making one long technical document and using the Wiki for user docs.

I figure we can use the collapsed sections in CONTRIBUTING.md to make it more usable despite the length.

**Comment by allella** [comment]
This also begs the question of if some of the README.md technical documentation is better in CONTRIBUTING.md.

These sections of the README may be better in CONTRIBUTING.md

- [Schema](https://github.com/freeCodeCamp/chapter/blob/master/README.md#schema)
- [AP Specs](https://github.com/freeCodeCamp/chapter/blob/master/README.md#api-specification
)
- [Testing](https://github.com/freeCodeCamp/chapter/blob/master/README.md#testing)

@Zeko369 @timmyichen would you agree on moving these sections and/or any others?

**Comment by Zeko369** [comment]
@allella Thank for openinig this PR and bringing this up. And sorry for the late replay I had a lot of stuff to do yesturday.

1. I was working on something but don't have a PR open, I'll do it with @Narutuffy.
2. Agreed, but we should also add how to pull other peoples branches, and maybe how to push to them (this can only be done by people with maintainter or higher level access to this repo, but seems important non the less)
3. Agreed
4. I'd keep it in `docs/images` or maybe rename it to `docs/assets`
5. Yes, that would be quite neat
6/7. I think that @Narutuffy should rewrite parts of the docs, or at least just do this migration

Regarding your other comment.

We should move that to the CONTRIBUTING.md, but there are some things about them that need to be changed, for example the Schema image generation #54, API (swagger.json) docs need to be heavily refactored.

**Comment by allella** [comment]
Regarding 4, how about we create an
/assets
directory and move everything out of the /docs directory.

@Zeko369 I assume there will be other assets for the front end.  Is there a pattern from another project we'd like to use to store web app assets, including the limited number of docs images?

**Comment by Zeko369** [comment]
@allella For the next.js all the assets are in the `/public` folder, and I don't really think we should put docs images there, I'd keep it in docs/assets so we can differentiate them from the app assets.

**Comment by allella** [comment]
Alright, @Narutuffy, are you still available to help with this issue?  Many of the steps are mentioned above, but I can assist and confirm.

**Comment by Narutuffy** [comment]
Yeah definitely, I will ping you and confirm for overall clarity @allella

**Comment by allella** [comment]
@Narutuffy  I've updated this issue with a checklist and you knocked out 2-6.  If you can help with 1,7,8, then I suspect these tasks and conversations should lead to other ways you can contribute on the more technical aspects.

8) is related to #54 because the issue was re-opened to talk about automatically generating a schema E-R Diagram image so the documentation is always updated when the schema changes.  @Zeko369 worked with   I just [commented that it looks like Github Pages would allow us to host the /docs directory](https://github.com/freeCodeCamp/chapter/issues/54#issuecomment-598480273), which could potentially allow us to [host the interactive SchemaSpy files](https://schemaspy.now.sh/) at a URL like https://freecodecamp.github.io/chapter/schema

**Comment by allella** [comment]
@Narutuffy this is simple, but the following images can be deleted. They were part of an issue and I moved the screenshots into that issue.

- docs/assets/GoogleGeneratedSnippet.png
- docs/assets/MeetupGroupEventSERBreadcrumbs.png
- docs/assets/RegularSER.png

**Comment by allella** [comment]
@Zeko369 @nik-john I seem to recall the Swagger documentation was hosted on a custom HTTP port.  I don't know if this is a good idea, or even possible, but could we export Swagger HTML file to docs/api automatically so they can be viewed through the GitHub pages?  Or, is it best to leave it as-is and expect developers to visit the custom HTTP port to see those docs?

**Comment by allella** [comment]
@Narutuffy @Zeko369 for task 8) on this issue, I think as a first step we should consolidate all the remaining sections we want into CONTRIBUTING.md and then talk about refactoring them.

I think if we wait until everything has been refactored, then we'll delay and complicate an otherwise easy copy / paste and reformat. 

Does everyone agree to move the following sections into CONTRIBUTING.md in their current state? Or, would we like to keep any of the README.md sections below in the README?

- [Development Setup](https://github.com/freeCodeCamp/chapter/blob/master/README.md#development-setup)
- [server/docs/README.md ](https://github.com/freeCodeCamp/chapter/tree/master/server/docs)
- [Testing](https://github.com/freeCodeCamp/chapter/blob/master/README.md#testing)
- [API Specification](https://github.com/freeCodeCamp/chapter/blob/master/README.md#api-specification)
- [Schema](https://github.com/freeCodeCamp/chapter/blob/master/README.md#schema)

**Comment by allella** [comment]
@Narutuffy I hope things are safe and stable in your life and community.

I'm going to have time to contribute more on the documentation.  I can continue with the remaining steps, but if you have time to continue, then please let me know to avoid duplicating efforts.

Thanks

**Comment by allella** [comment]
I'm going to continue this issue and consolidate the existing technical documents (1 and 8 above) into CONTRIBUTING.md and we can continue updating the Docker section and others once it's all in one place.

Quincy shared [the freeCodeCamp contributing domain / page](https://contribute.freecodecamp.org/#/index) as an example of having things in one place.  This is a first step in that direction.

**Comment by allella** [comment]
#1 from the list above is targeted by https://github.com/freeCodeCamp/chapter/pull/397
