### ISSUE TITLE
Adding Webmention support (especially RSVP)

### ISSUE THREAD

**Issue by Ryuno-Ki** [freeCodeCamp/chapter#377]
### Discuss your ideas or share your views: 

Since this project is based on open principles, I was wondering, whether it could implement some IndieWeb APIs such as [rsvp](https://indieweb.org/rsvp).

I'd volunteer to implement it.

Right now, #110 is considering email only from what I got. IndieWeb would work with Domains-of-your-own.

**Comment by allella** [comment]
@Ryuno-Ki we have a Roadmap label which Quincy has used to keep tabs on closed non-MVP features / issues?

This sounds interesting and worth implementing, but it's new to me and probably many people have no idea how they'd even use it at this point.

Shall we put this on the Roadmap, or is there already broad adoption where it's worth considering for MVP?

**Comment by Ryuno-Ki** [comment]
Sure, the IndieWeb isn't that known (yet?). I mean, just next week, there is going to be IndieWebCamp East] and [some people already announced their attendance](https://2020.indieweb.org/east#register).

But as long as you announce that a possible PR would be accepted, it's okay to let volunteers work on it, I think.
To me, it's important to offer alternatives to large (mainly Western) corporates. IndieWeb offers some means to give people back control. I want to support that whenever I can.

**Comment by allella** [comment]
I'll close this and add the Roadmap label, which has been Quincy's preferred way to keep the issue queue from having non-MVP conversations, but still curating features and conversations to come back to post-MVP.
