### ISSUE TITLE
Schema: Add field(s) for video conference URL / Online Events

### ISSUE THREAD

**Issue by allella** [freeCodeCamp/chapter#378]
@Zeko369 @timmyichen @QuincyLarson @tomiiide 

One of actionable [next steps](https://github.com/freeCodeCamp/chapter/wiki/Meeting-Notes-July-18,-2020#next-steps) was to update the schema, models, and API to handle online / virtual events.

The [schema ER diagram](https://github.com/freeCodeCamp/chapter/blob/master/data/schema.png) may be a bit out of date, but I think it's current enough for this conversation.

### Rough Ideas to Seed the Conversation
- add an optional _events.video_url_ field specifically for a video conference / live stream URL.
- add a _events.url_ field specifically for a general event website / URL. In the application's logic, this could default to the _event_'s public _Chapter_ URL.  An _organizer_ could set / override this URL to point somewhere else. For instance, if the _chapter_ is hosting a hack-a-thon / large _event_, then they may prefer to direct API traffic to a more general outside_events.url_ landing page. 
- add the following fields to _venues_ (street_address, city / locality, postal_code, region, country, latitude, longitude). Otherwise, _events_ would be advertising to meet at a physical _venue_ but the _user_ may have no idea where to go.
- we'll want a way to filter between physical and online _events_. The easiest way to do this would be to have an _events.venue_type_ field with enumerated options {"physical", "online", "physical-and-online"}. It's possible we could infer whether an _event_ is physical, online, or both without this field, but it would be more complex and subject to errors.  Quincy mentioned a toggle in the UI for "Physical" vs "Online", but "Both" is just as likely to happen. We might as well ask the _organizer_ to specify when an _event_ is created and the UI could show/hide elements for a physical venue and/or online/video and we avoid the guesswork.
- remove postal_code from _locations_.  A _chapter_ like freeCodeCamp Greenville doesn't really have a "postal code". _chapters_ and non-profits typically serve a broader locality or region so a physical zip code for a chapter is probably not of much value to a _user_.  If we later develop a zip code radius search feature, then we could decide to add a postal code back, but I suspect we'd use a _venue_'s postal code and not that of a _chapter_. (edit: I proposed we [remove _locations_ in a comment below](https://github.com/freeCodeCamp/chapter/issues/378#issuecomment-665950015))

### Caveats

- As an alternative approach, I was considering that an _event_ could have one or more venue records and these could house physical and/or online _venue_ details. However, the fields used for physical and online _venues_ would be potentially mutually exclusive and I felt we'd be cramming two concepts into one table. This may be a viable alternative with some better thinking.
- This doesn't exactly adhere to schema.org for [Events](https://schema.org/Event) and [VirtualLocations](https://schema.org/VirtualLocation) but I did try to anchor the field names and rough idea to those schema.

**Comment by pdotsani** [comment]
If we're going with auth0, I think it might be helpful to save some parts of the user profile auth0 provides. This is what a successful auth0 request returns after login:
```
{
  "clientID": <id_here>,
  "created_at": "2020-07-21T03:15:58.770Z",
  "email": <email_here>,
  "email_verified": true,
  "family_name": <last_name>,
  "given_name": <first_name>
  "identities": [
    {
      "provider": "google-oauth2",
      "user_id": "<id_here>,
      "connection": "google-oauth2",
      "isSocial": true
    }
  ],
  "locale": "en",
  "name": "<first_name>,
  "nickname": <nickname_here>,
  "picture": <url_here>,
  "updated_at": "2020-07-21T03:15:58.770Z",
  "user_id": <id_here>,
  "sub": <id_here>
}
```
Another benefit of using auth0 is that we wouldn't have to save passwords anymore.

**Comment by allella** [comment]
@pdotsani I don't think the [schema](https://github.com/freeCodeCamp/chapter/blob/master/data/schema.png) has been given much consideration for the auth fields, so it's rather likely we need more work on that side. In fact, if the _social_provider_ and _social_provider_users_ tables don't make sense in the context of using only Google Auth, then we can trim down the schema there too.

Since this issue is primarily focused with the virtual events vs physical events, could you create a new issue or PR and share thoughts on schema updates for required _users_ fields?

**Comment by allella** [comment]
@timmyichen @Zeko369 thoughts on the proposed adds / changes to the schema for handling online meetings?

**Comment by Zeko369** [comment]
Yeah, we're definitely going to be removing social_providers for now and only keeping the google auth.

I'll open up small issues so more people can work on this stuff.

> add an optional events.video_url field specifically for a video conference / live stream URL. #380 
👍 

The URL thing is a great idea. #381
Chapter -> URL
Event URL -> if missing use ChapterURL

> add the following fields to venues (street_address, city / locality, postal_code, region, country, latitude, longitude). Otherwise, events would be advertising to meet at a physical venue but the user may have no idea where to go.
Shouldn't this just be a link between `locations` and `events`? @allella what do you think?

Enums for online/offline events #382

Remove `postal_codes` #383

**Comment by allella** [comment]
@Zeko369 I don't think I was involved in the initial _locations_ or _venues_ to know the reasoning.

It looks like _locations_ was created to allow for a city / region / country search like was [mocked up for the main Chapter instance landing page](https://www.figma.com/proto/q7DikyL3N0c4CUWxHNa97i/Chapter-Prototype?node-id=1%3A2&scaling=scale-down).

However, the schema also shows relationship between _venues_ and _locations_, which would only make sense if _locations_ had a street address, lat, long, and zip code as well.

I don't think we need both tables.  If we move city, region, country to the _chapters_ table, then it allows for something like `SELECT * FROM venue GROUP BY city, region, country` to easily populate the values for a city, region, country search.

Then, _venues_ could have their own _street_address, city / locality, postal_code, region, country, latitude, longitude_ as described earlier, and we don't need _locations_.

Does that make sense?  Mixing a physical venue address and a generic location is what we had. It's two different use cases and we can accomplish both use cases with only _chapters_ and _venues_.

**Comment by allella** [comment]
As further support to remove the locations table, here's more ways it would be confusing.

Physical venues need a street address, latitude, longitude, and zip code. In the current form, this would require us to add street address, latitude, longitude, and zip code to _locations_.

_chapters_ typically do not have a physical street address because they are often just meetup groups and not physical organizations.   _chapters_  often change venues or meet at different venues, so it could further confuse a member / attendee if a chapter showed a physical address, but the event was at a different physical address.

So, it's rather confusing to have both _chapters_ and _venues_ with a relationship to a table with a street address, latitude, longitude, and zip code.

**Comment by Zeko369** [comment]
@allella Since most self hosted chapter instances will only have one chapter I completely agree with you that we should remove location aspects of chapter entities in the db. Since we'll only have locations in one place (venues) and since most of the time venues won't share locations, we can move the columns needed for location to venues and remove locations all together

**Comment by allella** [comment]
I think we can still have a city, region, country on the _chapters_ table because groups like freeCodeCamp are likely going to have many _chapters_ and having those fields connected directly to each chapter's record will allow for any easy front-end query by city + region + country, as in the [Figma mockup](https://www.figma.com/proto/q7DikyL3N0c4CUWxHNa97i/Chapter-Prototype?node-id=1%3A2&scaling=scale-down)

**Comment by Zeko369** [comment]
Agreed, let's do it that way then @allella

**Comment by allella** [comment]
@Zeko369 I'm closing this discussion since you created issues for the tasks and since #383 handled the largest part of the changes.  Thanks

**Comment by allella** [comment]
All the pieces of this issue should now be covered thanks to @katien
