### ISSUE TITLE
Merge locations into venues table, remove locations - chapters relation

### ISSUE THREAD

**Issue by Zeko369** [freeCodeCamp/chapter#383]
Since we don't really need to share locations between multiple venues, we can move all the data into venues themselves (so address, city, ... can all live as columns in the venues table)

-> Merge locations into venues tables, remove locations-chapters relation.
-> [Read a comment below](https://github.com/freeCodeCamp/chapter/issues/383#issuecomment-666704467)

For more info check #378 (specifically [this comment](https://github.com/freeCodeCamp/chapter/issues/378#issuecomment-665956981))

**Comment by allella** [comment]
I just [proposed we consider getting rid of this table entirely](https://github.com/freeCodeCamp/chapter/issues/378#issuecomment-665950015) and moving the fields to _chapters_ and _venues_.

**Comment by Zeko369** [comment]
@allella what do you think?

**Comment by allella** [comment]
@Zeko369 in summary, I'd suggest

- Add to venues:  _street_address, city / locality, postal_code, region, country, latitude, longitude_
- Add to chapters: _city / locality, region_
- Remove: _locations_ table

These address fields may look like duplicate fields, but they serve two distinct purposes.

**Comment by Zeko369** [comment]
Let's go with this

> @Zeko369 in summary, I'd suggest
> 
> * Add to venues:  _street_address, city / locality, postal_code, region, country, latitude, longitude_
> * Add to chapters: _city / locality, region, country_
> * Remove: _locations_ table
> 
> These address fields may look like duplicate fields, but they serve two distinct purposes.

**Comment by Zeko369** [comment]
Added in #393
