### ISSUE TITLE
Setup Development Environment with Gitpod, Github Codespaces, or Similar

### ISSUE THREAD

**Issue by Zeko369** [freeCodeCamp/chapter#384]
@QuincyLarson since our dev setup isn't really the easiest, what do you think about trying to enrol this project in the beta and we setup a simple codespaces template so people would be 2 clicks away from contributing compared to a docker, VScode, other stuff steps away

**Comment by QuincyLarson** [comment]
@Zeko369 I am in favor of this. It should dramatically reduce barriers to entry for new contributors.

**Comment by vkWeb** [comment]
@Zeko369 @QuincyLarson Any thoughts on gitpod, it's on the same lines...? We use that on fCC main repo and it's nice.

**Comment by Zeko369** [comment]
That's also nice, the main reason I wanted to use GH Codespaces is because of the integration, they'll come out of beta in a month and I think the integration will be a lot better than with GP.

I don't know if GP sets up SSH keys and stuff like that but Codespaces should

**Comment by QuincyLarson** [comment]
If Codespaces isn't available yet. It's supposed to become publicly available in mid-September. We can revisit this then, and if Codespaces gets delayed or its featureset gets changed, we can consider using GitPod then.

**Comment by Ryuno-Ki** [comment]
We've got mid-October by now. Any updates?

**Comment by allella** [comment]
Gitpod's free tier and Github Codespaces [were discussed during the Nov 7th, 2020 meeting](https://github.com/freeCodeCamp/chapter/wiki/Meeting-Notes-November-7,-2020#development-environment).

> - Fran mentioned Github Codespaces as a potential tool to spin up a Linux Virtual Machine (VM) with VS Code as a one-click tool. However, it may cost money to the contributor.
> - Quincy said Gitpod is another similar tool that's been used by freeCodeCamp. Gitpod has a free 50 hour tier. He's prefer to work with a familiar tool. Oliver will look into this action item.
> 

It was suggested @ojeytonwilliams would look into the possibilities, particularly with Gitpod.
