### ISSUE TITLE
Add logging library

### ISSUE THREAD

**Issue by Ryuno-Ki** [freeCodeCamp/chapter#412]
This came up during review of #411.
It is somewhat related to #23.

For debugging purposes, it is helpful to have logging statements (or using breakpoints).
However, those shouldn't be shipped to production.
Thus, a logging library should be configurable via environment variable to only output values above a certain level.

Since right now, this repo ships client and server code, the chosen logging library must support both environments.
It might be helpful to pick a library, which allows to send logs to a dedicated endpoint (logging server). This way, it might help to monitor the service.

Personally, I tend to use [loglevel](https://www.npmjs.com/package/loglevel) for it.
Other popular libraries are [winston](https://www.npmjs.com/package/winston), [bunyan](https://www.npmjs.com/package/bunyan) or [pino](https://www.npmjs.com/package/pino).

I haven't looked into React wrapper for those, yet.

**Comment by timmyichen** [comment]
I'm not sure I see the purpose if it's just for debugging, and even then, it's much too noisy to be useful for debugging a particular problem.

The only useful thing I can see from using a logger here would be for http requests.

**Comment by Ryuno-Ki** [comment]
You can log warnings and errors for example.
Say, a AJAX request did not succeed.
Or an unhandled error is thrown.
Those are worth logging.

**Comment by timmyichen** [comment]
We shouldn't have any real need for frontend ajax request logging if we are using Apollo (the network tab also does this)

Unhandled exceptions are already logged to the console in every environment.

Just speaking from personal experience, I would turn this off 100% of the time because it's just either noise or it's inferior to existing debugging tools.

**Comment by Ryuno-Ki** [comment]
Fair enough :-)

**Comment by timmyichen** [comment]
That being said, I'm curious what other peoples' thoughts are here - I may be in the minority.
