### ISSUE TITLE
Handle CORS / Network problems

### ISSUE THREAD

**Issue by Ryuno-Ki** [freeCodeCamp/chapter#415]
### Describe the bug:

During work on #413 I observed CORS issues (localhost:3000 couldn't reach localhost:5000/graphql).
From what I can see, error cases on the network level are not properly handled in the UI.
#413 is showing a technical error message. However, a proper UI/UX spec should be defined what to do if data can't be loaded.

### Tell us about your browser and operating system:
- Browser(s) name and version: Firefox 78
- Operating System: Sabayon Linux

**Comment by vkWeb** [comment]
@Ryuno-Ki As far as UI is concerned, if a client can't reach the backend then I think we should display a flash error message...?

**Comment by Ryuno-Ki** [comment]
Hi @vkWeb,

there is no design spec for it (we can use issue to flash out one).
„Flash error message” is something like a [snackbar](https://material-ui.com/components/snackbars/#snackbar)?

Keep in mind [WCAG Success Criterion 2.2.1: Timing Adjustable (Level A)](https://www.w3.org/WAI/WCAG21/Understanding/timing-adjustable.html).

If you want to read more about accessibility: https://adrianroselli.com/2020/01/defining-toast-messages.html and https://www.scottohara.me/blog/2019/07/08/a-toast-to-a11y-toasts.html are good starts.
Material UI will take care of some aspects, so we can focus on the UX here.

**Comment by vkWeb** [comment]
@Ryuno-Ki I personally like how GitHub brings up flash message just below the navigation. It stays till dismissed by user. Snackbar might provide that functionality so let's go with it.

**Comment by Ryuno-Ki** [comment]
I think, GitHub's approach is closer to [Alert](https://material-ui.com/components/alert/)s.

**Comment by vkWeb** [comment]
@Ryuno-Ki Perfect. Full-width and sticky just below navigation. What do you say?

**Comment by Ryuno-Ki** [comment]
I'd like to have #413 merged first :-)

I need to think about how to trigger the Alert component. Ideally, that should be possible from different components (i.e. everywhere we use a GraphQL query for starters).

**Comment by vkWeb** [comment]
@Ryuno-Ki we should not merge without Tim's review. Let us wait, he'll check the PR after work. 

Can we create an errorHandler sort of thing. That puts up an alert whenever an API request fails...?

**Comment by Ryuno-Ki** [comment]
Sure thing. I'm not in a hurry.

From my experience with React, I can imagine several approaches.
If there were a state management like Redux or MobX, the Alert would be shown once a respective property is set in the state tree.
Another approach would be to use a [Context](https://reactjs.org/docs/context.html) for that, but I will need to research, how well that would integrate with the current setup.
The third option I can imagine is to pass callbacks down the tree via prop. I'd like to avoid this one if possible.
Custom Events aren't [listed under the supported events](https://reactjs.org/docs/events.html).
