### ISSUE TITLE
Demo and screenshots

### ISSUE THREAD

**Issue by a0m0rajab** [freeCodeCamp/chapter#442]
### Discuss your ideas or share your views: 
Make sure to tell how your idea will benefit this project.

I have scrolled over the project and read some of the information about it, yet I could not find a screenshots or even a demo for the project, I think those kind of things can help the project and add value to it. 

we can embed few screenshots in the MD file as well to help, and add the demo link in the description. 

How it can benefits the project: 
it will let the user have a faster and easier way to decide to use the tool based on the demo, know what to expect and how to handle it.

**Comment by allella** [comment]
Thanks for the idea.

This project is still under development are we are a good way from having an MVP so we have nothing notable to share right now for the eventual end user.

For developers, [the README has links to prototypes of some of the primary interfaces](https://github.com/freeCodeCamp/chapter#ui--ux--design-references) as a visual reference.

Also, @tomnoland and others are working to make it easier for developers to deploy the project in a Docker container, plus having an example running on Heroku.

Please [join the conversation on Discord](https://discord.com/channels/633401573002969128/633826607617933353) and help implement some of these ideas.

**Comment by a0m0rajab** [comment]
That's great to know, I will keep my eyes on the project and see what can I do :)
