### ISSUE TITLE
Update Chat Links

### ISSUE THREAD

**Issue by allella** [freeCodeCamp/chapter#443]
As @dtwilliams10 mentioned on Discored, we'll need to update the README and a few other links.

@QuincyLarson has the new channel been created?

**Comment by allella** [comment]
@pdotsani I'm reviewing and tweaking the README.

Is this still a proper description of the auth tool, or is there a better description?

> [passport.js](http://www.passportjs.org/) for auth

**Comment by pdotsani** [comment]
> @pdotsani I'm reviewing and tweaking the README.
> 
> Is this still a proper description of the auth tool, or is there a better description?
> 
> > [passport.js](http://www.passportjs.org/) for auth

@allella the name of the auth package is [passport-magic-link](https://www.npmjs.com/package/passport-magic-link). Maybe we could just use the description for the npm package: "Magic Link authentication for Passport JS".

**Comment by allella** [comment]
Thanks @pdotsani.
