### ISSUE TITLE
As a user (authenticated or not), I can view a list of upcoming events on the homepage

### ISSUE THREAD

**Issue by allella** [freeCodeCamp/chapter#444]
- [x] API call to get the next 5 upcoming events 
- [x] Material UI card layout for rendering a single event
- [x] Render initial view of events
- [x] Logic to render additional events via lazy-load / infinite scroll

Example from the mock-up
https://www.figma.com/proto/q7DikyL3N0c4CUWxHNa97i/Chapter-Prototype?node-id=332%3A355&scaling=scale-down

**Comment by allella** [comment]
@dtwilliams10 we decide if we're going to implement the "filter" shown in the mockup.

For MVP, I'm thinking the filter may not be necessary since / if the location of an event is likely the primary decision for a _user_.

**Comment by allella** [comment]
@paizle perhaps you and @dtwilliams10 can move along this homepage and related search bar #349.

**Comment by allella** [comment]
Actually, I see the MVP [homepage mock-up](https://www.figma.com/proto/q7DikyL3N0c4CUWxHNa97i/Chapter-Prototype?node-id=1%3A2&scaling=scale-down) doesn't include the filters and that seems reasonable since there will be a search bar and "Events" page that may offer more features.

**Comment by dtwilliams10** [comment]
I was thinking to load eager load 5 events (need to figure out how to determine those 5) at page load into individual cards and then lazy load the rest in a paginated format.  Thoughts, ideas, suggestions?

**Comment by allella** [comment]
I'd assume the homepage would be ordered upcoming event date.

Loading +/-5 and lazy loading the rest sounds like a fine start to me.

**Comment by allella** [comment]
@dtwilliams10  if you have ideas on more specific "tasks" for the top of this issue.

We've learned that many contributors appreciate viewing the issue as pieces, while others like to maintain the user story approach.  

As a middle-ground, we're going to add a smaller task-based list at the top of the user story issues and we can link off to smaller task-based issues as needed.

This will keep the user story issues for a broader view of the [MVP project](https://github.com/freeCodeCamp/chapter/projects/1#card-56434681).

Do you have thoughts on additional tasks for this issue?

Thanks

**Comment by paizle** [comment]
@dtwilliams10 It sounds like you've got a good idea to handle this so maybe I can just help support you by taking care of time consuming tasks while I get more familiar with everything.

**Comment by allella** [comment]
@dtwilliams10  @paizle the merged in button in #413 created a few issues mentioned on #450

Those are creating an issue with the front-end.

Once that's corrected it would be great to get this homepage list roughed in.

**Comment by dtwilliams10** [comment]
@allella Looking at the home page after merging in the approved PRs it looks like some home page listing work was already done (see the attached screenshot). I have had to delay some of this work because of IRL things coming up. I'm hoping to get work done tonight and provide an update. 

<img width="1440" alt="Screen Shot 2021-03-15 at 12 17 23 PM" src="https://user-images.githubusercontent.com/20099292/111185800-c0b3fe00-8588-11eb-829f-706a49bfb36c.png">

**Comment by allella** [comment]
Sounds good.  #450 has been corrected, so the build should no longer fail.

**Comment by Zeko369** [comment]
Hmm Github auto-close thingy didn't work :( so closing this because #607 finished this
