### ISSUE TITLE
Add `npm run postinstall` to contributing.md

### ISSUE THREAD

**Issue by NorthDecoder** [freeCodeCamp/chapter#462]
### Describe the bug:

The _.env_ file is mandatory for the project to build, however it is intentionally not provided as part of the project as it will contain the project secrets. The Chapter developer/installer is required to issue the proper commands to create and edit the _.env_ file.

A script has been provided to copy defaults values from the _.env.example_ into the _.env_ .

Put the following sentence into the CONTRIBUTING.md file around line 310 in
the section run the app step 1.

> Run `npm run postinstall` to copy the file _.env.example_ into the file _.env_.
> If the _.env_ file exists it will not be overwritten.

### Tell us about your browser and operating system:
- Browser(s) name and version:  __terminal__
- Operating System: 
uname -ior
5.3.7-301.fc31.x86_64 x86_64 GNU/Linux

**Comment by allella** [comment]
Added notes on PR #463 to test if this is necessary since running the mandatory _npx recursive-install_ step should run the postInstall hook in package.json, which is tasked with creating .env if it doesn't exist.

**Comment by allella** [comment]
Posting images for reference

![image](https://user-images.githubusercontent.com/1777776/112644424-c7116800-8e1b-11eb-8544-6201859973b1.png)


![image](https://user-images.githubusercontent.com/1777776/112644388-bc56d300-8e1b-11eb-9c85-5454ca0525bc.png)

**Comment by NorthDecoder** [comment]
I have removed project and started fresh again and found that the postinstall script was indeed run and the default _.env_ file was created as expected.  Therefore this issue and the associated pull request #463 can be closed, with understanding to continue review of wording in the contributing.md file.
