### ISSUE TITLE
Lint eslint/interface-name-prefix

### ISSUE THREAD

**Issue by NorthDecoder** [freeCodeCamp/chapter#468]
### Describe the bug:

On the command line __`npm run lint`__ causes some errors.

The first error is
>  Interface name must be prefixed with "I"  @typescript-eslint/interface-name-prefix

Researching further results in finding that the current recommendation by the Typescipt team is to change the rule so that the interface names do __NOT__ begin with 'I'.

* [typescript-eslint/issues/374](https://github.com/typescript-eslint/typescript-eslint/issues/374)

* The code for [do-not-begin-with-an-i](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/naming-convention.md#enforce-that-interface-names-do-not-begin-with-an-i)

* SO
  * [62915344](https://stackoverflow.com/questions/62915344/eslint-erro-when-adding-rule-typescript-eslint-interface-name-prefix)

Looking into `.eslintrc.json` to see the rule for discussion.

```json
"@typescript-eslint/interface-name-prefix": [
      2,
      { "prefixWithI": "always" }
    ]
```

We either need to fix the rule or fix the code :)

### Tell us about your browser and operating system:
- Browser(s) name and version: __terminal__
- Operating System: __5.3.7-301.fc31.x86_64 GNU/Linux__

**Comment by allella** [comment]
@NorthDecoder I have not technical experience or opinion, but I scanned the comments and the final comment says they

> We will _not_ be removing interface-name-prefix from the recommended set

If that's the case, does that mean _"prefixWithI": "always"_ is still the default? If so, it sounds like "I" prefixes are still the official direction, yes / no?

**Comment by allella** [comment]
Well, I see the other links suggest this may have been changed to _no I_, as you suggested.  If that's the official suggestion, then feel free to share a PR to fix it.

**Comment by NorthDecoder** [comment]
My understanding is that they left the option available for those who want it one way or the other.  As you saw there was a long discussion by both sides of the opinion and that was the compromise.

I will change the setting to __'no I'__ to match the current status of the Chapter code.

**Comment by ojeytonwilliams** [comment]
@NorthDecoder could we just drop the rule since it's deprecated?  I think it will default to **'no I'** if we do that.

**Comment by NorthDecoder** [comment]
@timmyichen , in the blame for the file it looks like you added this rule. Do you have a strong preference for the 'I' before the interface names?
