### ISSUE TITLE
Test: TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by NorthDecoder** [freeCodeCamp/chapter#469]
### Describe the bug:

From the command line __`npm run test`__ results in the error:

>TypeError: Cannot convert undefined or null to object
>   at Function.keys (<anonymous>)
>    at exports.pathsToModuleNameMapper (/home/northdecoder/workspace/chapter/node_modules/ts-jest/dist/config/paths-to-module-name-mapper.js:25:39)
>    at Object.<anonymous> (/home/northdecoder/workspace/chapter/jest.config.js:13:21)
> ...

### Tell us about your browser and operating system:
- Browser(s) name and version: __terminal__
- Operating System: __5.3.7-301.fc31.x86_64 GNU/Linux__

**Comment by allella** [comment]
The note 

> "If you started the application using the Manual Mode (without Docker), then tests are run using npm run test OR if you want to use the "watch" mode run npm run test:watch"

 is from an early iteration of the docs, so it may be temporarily broken.

I vaguely recall like Fran may have broken tests when converting to GraphQL, so let's not spend much time on this at the moment.

**Comment by allella** [comment]
Oliver's PR to fix / workaround this has been merged in.
