### ISSUE TITLE
Docs: Add Troubleshooting for CONTRIBUTING.md Steps

### ISSUE THREAD

**Issue by allella** [freeCodeCamp/chapter#471]
## Application Errors
- [ ] Problem: JsonWebTokenError: invalid signature -- Solution: Clear the browser cookies for the _localhost_ domain, or use an incognito browser window to open the site.
- [ ] Problem: Where do application registration and other emails go? -- Solution: All email are captured and saved by Mailhog. Simply open http://localhost:8025/ to see captured emails. For account registration, the email validation link can be opened in the browser to complete the registration process.
- [ ]  The application shows _"Something went wrong relation "chapters" does not exist"_ - Solution:  The [database needs to be initialized](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md#initializing-the-database).
- [ ] The applications shows "_The table `public.chapters` does not exist in the current database."_ or _"Invalid 'prisma_1.prisma.chapters.findMany()"_ -- Solution: The database hasn't been created. Run `npm run db:reset` to clear and re-create the database tables.
 
## Linux Docker Troubleshooting
- [ ] `docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))`
- [ ] Run `sudo docker-compose up` or add non-privileged user to the docker group as described in https://docs.docker.com/engine/install/linux-postinstall/ If Docker was run as sudo before adding your user to the docker group
- [ ] "WARNING: Error loading config file: /home/user/.docker/config.json " see https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user

## Node / NPM
- [ ] **Problem:** notsup Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}) - **Solution:** Upgrade to npm version 7 or 8, like `npm install -g npm@latest` or by getting the latest version of NodeJS from your Linux package manager. Or, install [nvm](https://github.com/nvm-sh/nvm).
- [ ] **Problem:** Running _npm i_ gives the error "Module not found: Can't resolve 'framer-motion'" - **Solution:** Upgrade to npm version 7 or 8, like `npm install -g npm@latest` or by getting the latest version of NodeJS from your Linux package manager. Or, install [nvm](https://github.com/nvm-sh/nvm).
- [ ] **Problem:**
```npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, rename '/usr/lib/node_modules/npm'
 or 
Error: EACCES: permission denied, rename '/usr/bin/npm'
```
**Solution:** https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally or else https://stackoverflow.com/a/51024493
- [ ] If using Windows / WSL + Ubuntu Terminal, "npx /bin/sh^M bad interpreter: No such file or directory" likely happens when Node.js is already installed on Windows, but it also needs to be [installed within the Linux subsystem / terminal](https://nodejs.org/en/download/package-manager/), such as [installing it with _apt_ on in Ubuntu](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions).

## ElephantSQL
- _Error during schema drop: QueryFailedError: must be owner of view pg_stat_statements_ while running _npm run db:reset_ - Solution: the free tier of ElephantSQL doesn't allow concurrent connections, so it's necessary to run database commands one-at-a-time, like _npm run db:drop_ then _npm run db:sync_ and then _npm run db:seed_. Alternatively, a paid plan on ElephantSQL would avoid this issue. - via https://github.com/freeCodeCamp/chapter/issues/762

## General Docker Troubleshooting
- [Linux](https://docs.docker.com/engine/install/linux-postinstall/)
- [Windows](https://docs.docker.com/docker-for-windows/troubleshoot/)
- [Mac](https://docs.docker.com/docker-for-mac/troubleshoot/)
- [ ] Make sure Docker isn't already running and bound to port 54320 - ERROR: for chapter-npx-test_db_1  Cannot start service db: driver failed programming external connectivity on endpoint chapter-npx-test_db_1 (....): Bind for 0.0.0.0:54320 failed: port is already allocated. ERROR: for db  Cannot start service db: driver failed programming external connectivity on endpoint chapter-npx-test_db_1
- [ ] To shut down Docker on Linux, press Ctrl + C in the terminal where it was started.
- [ ] To purge old images, which can sometimes be the source of errors, run `docker-compose rm && docker image prune -a`

### WSL
- [ ] [General WSL troubleshooting](https://docs.microsoft.com/en-us/windows/wsl/install-win10#troubleshooting-installation)
- [ ] "WSL2 Installation is Incomplete" - Follow the steps to install the missing component
- [ ] WslRegisterDistribution failed with error: 0x80070057 - this is common on older CPUs which does not support Virtulization, HyperV or SLAT - Solution: Open Powershell and change back to WSL 1 using ``wsl --set-default-version 1``

### Windows Docker Troubleshooting
- [ ] "Docker Desktop requires Windows 10 Pro/Enterprise (######+) or Windows 10 Home (#####.####+)" - Windows 10 is running an old / unsupported version and needs to be updated before Docker will install.
- [ ] "Failed to execute script docker-composer"  - Solution: Start Docker Desktop via the Windows Start Menu and restart Git Bash
- [ ] Docker / WSL2 consumes all your system's RAM and is very slow - [Limit resources](https://medium.com/@lewwybogus/how-to-stop-wsl2-from-hogging-all-your-ram-with-docker-d7846b9c5b37)
- [ ] "Windows Defender Firewall has blocked some features of this app"  - Allow Access

**Comment by allella** [comment]
Related to the ideas @northdecoder's shared in chat about [_The Documentation System_](https://documentation.divio.com/),  I had started a list of Troubleshooting issues I've encountered while running through the CONTRIBUTING.md on less common setups, like _Windows_, _Windows_ + _WSL_ + _Ubuntu_, and _Git Bash_.

I've started a list here.

A couple options off the top of mind about where to put such a document include:
* TROUBLESHOOTING.md
* Page in the Wiki

**Comment by Ravichandra-C** [comment]
Issues I faced while running the chapter with Windows + Git bash using docker.
1. 
Issue: chapter app docker container was not starting when I run docker compose up
Solution : Removed `./wait-for db:5432 -- ` from Command in app Service in docker-compose.override.yml file

2. Problem : I'm unable to run npm run eslint
3. Problem : I'm unable to run npm run cypress:run , However I was able to run the npm run cyress:open , So I was able to run tests locally.

**Comment by Ravichandra-C** [comment]
Issues face while developing with WSL2
Configuration: WSL2 Ubuntu 2004 with windows 10

1. Unable to run the cypress tests locally.

**Comment by joeriddles** [comment]
I ran into the issue mentioned [here](https://stackoverflow.com/questions/67938486/after-installing-npm-on-wsl-ubuntu-20-04-i-get-the-message-usr-bin-env-bash) when I ran `npm i` from ubuntu in WSL.

I followed the instructions in the answer and created `/etc/wsl.conf` in ubuntu with:
```
[interop]
appendWindowsPath = false
```

After restarting WSL, `npm i` worked, but then I couldn't run docker commands from WSL. So then I removed `wsl.conf`, restarted WSL, and had to mess around with Docker for Desktop a little before I could run docker commands in WSL.

**Comment by ojeytonwilliams** [comment]
@joeriddles did you manage to find a config that meant both `npm i` and Docker worked?

**Comment by Sboonny** [comment]
I am wondering if it's decided where to put the documentation, and if I can help with creating it.

**Comment by allella** [comment]
@Sboonny one other option is to add the troubleshooting as a collapsed section at the end of the CONTRIBUTING.md.

I mention that because the troubleshooting list above is relevant for developers.  Whenever the app goes live we may find a use for a similar, less technical, "Help" document for the end user and most our other end-user docs are in the Wiki.

What do you think about adding the more technical troubleshooting to the existing https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md#troubleshooting section, as a collapsed Question and Answer style and then planning to have an end-user _Help_ in the Wiki?

**Comment by Sboonny** [comment]
> add the troubleshooting as a collapsed section

I do see the point, and I do like the idea👌, I will start implementing it. I will create every section with its PR because it easy for me to make silly mistakes.

**Comment by allella** [comment]
Thanks to @Sboonny for moving this over to the CONTRIBUTING.md.  See the [Troubleshooting section](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md#troubleshooting) and expand the appropriate topic areas for help with common technical errors and their solutions.
