### ISSUE TITLE
docs(contributing) Add run lint wording and guideline

### ISSUE THREAD

**Issue by NorthDecoder** [freeCodeCamp/chapter#524]
### Describe the bug:

Consider:
1. adding wording to CONTRIBUTING that suggests linting and testing prior to running the application.
2. adding a guideline regarding the merging of pull requests that must pass linting and tests.

Reference pull request #525
### Tell us about your browser and operating system:
- Browser(s) name and version: n/a
- Operating System: n/a

**Comment by allella** [comment]
@NorthDecoder I merged in #594 since it wouldn't let me set you as a reviewer and because it's simple enough to tweak in another PR if the new `npm run lint-and-test` doesn't work as expected.
