### ISSUE TITLE
Remove swagger-ui-express from package.json

### ISSUE THREAD

**Issue by NorthDecoder** [freeCodeCamp/chapter#529]
### Describe the bug:

It looks like the project is adopting graphql and dropping swagger as an API.

Searching the issues I see no mention of the change.  Perhaps it was discussed on Discord, but no issue created on Github.

In _package.json_ `swagger-ui-express": "^4.1.3"` is required as a dependency.  Reading the docs I see that "This module allows you to serve auto-generated swagger-ui generated API docs from express, based on a swagger.json file."

Running `find ~/workspace/chapter -name "swagger.json"` the file is not found in any of the subdirectories.

Can we remove the dependency `swagger-ui-express": "^4.1.3"` from _package.json_?

### Tell us about your browser and operating system:
- Browser(s) name and version: n/a 
- Operating System:  n/a

**Comment by ojeytonwilliams** [comment]
I think so, yes.  I came to the same conclusion when I was checking for unused dependencies: https://github.com/freeCodeCamp/chapter/pull/526

**Comment by allella** [comment]
Agreed. Fran switched to GraphQL and we have the playground and someone else mentioned Swagger was no longer valid.
