### ISSUE TITLE
typescript compile error in MailerService.ts

### ISSUE THREAD

**Issue by NorthDecoder** [freeCodeCamp/chapter#530]
### Describe the bug:

**EDITED: 04/09/21 16:54** REARRANGED IMAGE, ADDED SOME NOTES WITH BENEFIT OF HINDSIGHT
At commit 7266654 `docker-compose up` appears to be failing with typescript compile error:

> app_1     | Compilation error in /usr/chapter/server/services/MailerService.ts

![typscript-compile-error](https://user-images.githubusercontent.com/9598008/114170682-22495d00-98e8-11eb-9c55-e451e1fefcde.PNG)

----

* `npm run lint` does not find the problem (  but it seems like lint should find a lint compile error as shown in previous image! )

* `npm run test`  correctly shows a warning message, which IS part of the tests **passing**
``` bash

 console.warn
    Email, Username, password, and/or email service are missing in Mailer.ts

      47 |
      48 |     if (!validateOurCredentials) {
    > 49 |       console.warn(
         |               ^
      50 |         'Email, Username, password, and/or email service are missing in Mailer.ts',
      51 |       );
      52 |     }

      at MailerService.createTransporter (server/services/MailerService.ts:49:15)
      at new MailerService (server/services/MailerService.ts:37:10)
      at EmailResolver.sendEmail (server/controllers/Messages/resolver.ts:9:19)
      at node_modules/type-graphql/dist/resolvers/create.js:31:98
      at Object.<anonymous> (server/controllers/Messages/resolver.test.ts:118:19)

  console.log
    Email failed to send.  Error: connect ECONNREFUSED 127.0.0.1:1025
        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
      errno: -111,
      code: 'ESOCKET',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 1025,
      command: 'CONN'
    }

      at MailerService.sendEmail (server/services/MailerService.ts:75:15)

```
----
* app_1 never finishes and the result is that the graphql playground is not served.

### Tell us about your browser and operating system:
- Browser(s) name and version: **terminal**
- Operating System: **5.3.7-301.fc31.x86_64 GNU/Linux**

**Comment by allella** [comment]
@NorthDecoder @megajon I believe this is related to the [email service needing to be documented](https://github.com/freeCodeCamp/chapter/pull/428#issuecomment-815311990).

If, so how about we change this issue's title to something like Docs: Email Service Configuration and then get a PR showing how to setup the service.

I suspect it's largely updating the .env file with a valid user, pass, and smtp host, but @megajon will need to help out since #428 was largely his work and it was just merged in yesterday.

**Comment by allella** [comment]
Also, for setting up a test SMTP configuration, we'd previously talked about services like [Ethereal](https://ethereal.email/) and [MailTrap](https://mailtrap.io/pricing).

I'd assume the setup of those "fake" email servers would be the same as any other SMTP configuration. It would be good to document both situations.  Perhaps the CONTRIBUTING.md documents the "fake" services and then in the [Wiki](https://github.com/freeCodeCamp/chapter/wiki), or wherever we put the _Owner_ and _Administrator_ documentation, we'll document examples of a production SMTP configuration.

**Comment by ojeytonwilliams** [comment]
@megajon's PR's not the root cause.  It's really my fault, since I messed with the TypeScript config while that was still being worked on.  

https://github.com/freeCodeCamp/chapter/pull/472 should fix it, but I'm just making sure it's doing what I wanted.

**Comment by NorthDecoder** [comment]
With the benefit of hindsight, I re-arranged the screen snip image and made some additional comments in the original post, so the presentation would not look like a MailService failure, but would rather highlight the typescript failure.

Looking at the CI workflow tests that **were** performed at the time of two of the previous commits pull requests and merge and I saw no similar failures.  Somehow I am running a different manual test than the CI workflow!

You have heard me say this before, maybe if I completely blow away my development environment and start with a fresh clone of my fork the error will go away.

**Comment by ojeytonwilliams** [comment]
@NorthDecoder it looks like a gap in the CI workflow - it should run `tsc` for the client and server. Let me sort that out and then we'll have a better idea if your local environment is okay.

**Comment by NorthDecoder** [comment]
Recent changes leading to commit 683cc3f, have resolved this issue🎇 Good work!

**Comment by ojeytonwilliams** [comment]
Ooops, I should have auto-closed this.  Thanks for catching that @NorthDecoder.
