### ISSUE TITLE
Lint errors

### ISSUE THREAD

**Issue by NorthDecoder** [freeCodeCamp/chapter#578]
### Describe the bug:

On a virtual machine in the cloud, my-versions:
```bash
Linux 5.3.7-301.fc31.x86_64

nvm: 0.35.1
node: v14.16.1
npm: 6.14.12

Docker version 19.03.5, build 633a0ea838
docker-compose version 1.24.1, build 4667896
```
----

At 2 parents 79bf34c + 364d9c6 commit 0459bf86930409d411dc3be90b05af14153ced69
![git_log](https://user-images.githubusercontent.com/9598008/115948162-4462e380-a481-11eb-8481-b07771ecf004.PNG)

----

I ran
```bash
sudo rm -rf node_modules/
sudo rm -rf client/node_modules
npx recursive-install
npm run lint
```
and found several linting errors

![npm-run-lint](https://user-images.githubusercontent.com/9598008/115948202-9572d780-a481-11eb-8975-c6f4651a92fe.PNG)

----

Strangely however, the ci-workflow passes ...
https://github.com/NorthDecoder/chapter/runs/2425175990?check_suite_focus=true

----
Then with `docker-compose up` visited the client to see:
![client_snip](https://user-images.githubusercontent.com/9598008/115948212-a7ed1100-a481-11eb-839d-c6c5c071236d.PNG)

### Tell us about your browser and operating system:
- Browser(s) name and version:  Firefox  88.0 (64bit)
- Operating System:  Windows 10

**Comment by ojeytonwilliams** [comment]
Hi @NorthDecoder you could try 
```
npx recursive-install
npm run lint
```

since https://github.com/freeCodeCamp/chapter/pull/538 changed the arrow function style rule.

Regarding the CORS errors, just to confirm: was this running on VM or was that Windows 10 on your local machine?

**Comment by NorthDecoder** [comment]
The OP has been updated to include the virtual machine information and the exact sequence of commands run to achieve the results.  Your changes in the noted pull request will be tested.

It could be the underlying question is "how is it that there is a discrepancy between the manual test run and that run on ci-workflow, where ci-workflow passes and manual testing fails?"  I will compare future results to see if there continues to be a difference.

**Comment by NorthDecoder** [comment]
Testing at 2 parents 99648a3 + b6f2a3b commit c0f73f00bef3545a6b56c5f5f6ebfa4313d06e20
the lint errors have gone away. However, on the client side the CORS error remains, which I am guessing should be its own separate issue?

**Comment by NorthDecoder** [comment]
Removed the image in the OP of the CORS errors and added the image to issue #585 .
