### ISSUE TITLE
Terminology

### ISSUE THREAD

**Issue by kognise** [freeCodeCamp/chapter#58]
I think to better communicate and more easily build an API and UI, we need to come up with a uniform set of terminology. Below is my (very much changable) suggestion based on what I've heard the community say the most:

- A ~~"chapter"~~ "collective" is one singular instance/deployment of Chapter
  *For example, Women who Code at the domain chapter.womenwhocode.com*
- A "user" is a person who authed to the chapter
  *For example, Kognise*
- A ~~"group"~~ "chapter" is a container for events, with a description and subscribers, and one or more "admins" who can manage it
  *For example, Women who Code NYC*
- A "event" is a single meetup that users can RSVP to, has a specific location and time, and has "organizers" 
  *For example, Women who Code NYC April Meetup*

(All the examples here are fictional and meaningless and probably super inaccurate)

What do you guys think of these - could they made more clear? Am I missing anything?

**Comment by cameronsr** [comment]
As someone who fits the admin/organizer description - I currently run a group of ~1200 - accurate enough for me.

Recommend we may want a term for several affiliated Chapter instances in different geographic locations.

Maybe Chapter Organization or Group?

Example - Operation Code (group I volunteer for) has ~18 separate chapters in different cities. Each effectively would run a separate instance of Chapter, but would all be affiliated under the same Chapter Org or Group.

**Comment by allella** [comment]
Maybe "organization" instead of group, but I'm saying that with little context to the schema.

**Comment by allella** [comment]
Also, it seems likely that on one instance you'd have multiple different organizations and possibly only 1 chapter.  Or, you might have an instance that hosts multiple orgs and multiple chapters, or 1 org and 1 chapter, or just 1 chapter.

**Comment by kognise** [comment]
@cameronsr the idea is that your organization would have a chapter, and within the chapter would be groups for different locations - maybe I made that too confusing 😛

**Comment by lkreimann** [comment]
@kognise I found that pretty clear. There are probably more possible organizational structures though :thinking: would guess the MVP would be good with the terminology on top. 

I've used Meetup etc. very rarely though, might not be the best reference.

**Comment by cameronsr** [comment]
Nope, makes sense now. I just haven't had my coffee yet. *shrug*

**Comment by kognise** [comment]
Maybe switching "groups" with "organizations" could make the terminology clearer?

**Comment by allella** [comment]
Actually, I see that "chapter" is one deployed instance.  That wasn't my initial feeling of it.

May be better to call it an deployment or some such and use "chapter" to represent the hosting/organizer of meetup events.

**Comment by allella** [comment]
I say that because my feeling is that one deployed instance could host numerous local meetup chapters.  We have 30+ in Greenville, SC and I don't see every group hosting their own deployed instance.

**Comment by kognise** [comment]
@allella hmmm, that's one of my concerns - but I think some deployments won't be focused on certain organizations and might be more general purpose,.and "chapter" is super generic.

**Comment by allella** [comment]
Yeah, but "chapter" has context in things like Women Who Code would have multiple chapters around the country/world.  So, using a physical world concept that's pretty well used in organized, chapter-based groups and mixing it with a technical usage already managed to confuse me.

**Comment by allella** [comment]
I'm wondering if reserving "chapter" for it's more typically used context is a better idea and then use a more technical word, like deployment, or instance, or container, or host system, to describe a single running server.

**Comment by kognise** [comment]
> Yeah, but "chapter" has context in things like Women Who Code would have multiple chapters around the country/world. So, using a physical world concept that's pretty well used in organized, chapter-based groups and mixing it with a technical usage already managed to confuse me.

Okay. So then could something like this be better?

- A _____ is one singular instance/deployment of Chapter
- A "user" is a person who authed to the chapter
- A "chapter" is a container for events, with a description and subscribers, and one or more "admins" who can manage it
- A "event" is a single meetup that users can RSVP to, has a specific location and time, and has "organizers"

**Comment by allella** [comment]
I like using "chapter" there instead of group, so that looks better to me.

For ______  maybe server, deployment, container, instance, host (don't really like using host though since is has a human use in the same context)

**Comment by kognise** [comment]
I feel like server, deployment, container, and even instance are all too technical for the average user. Instance is the best-sounding to me - this is gonna be tricky.

Maybe something like collection or site?

**Comment by allella** [comment]
Funny enough, there is a lot of overlap between the event context and the technical context here, so that's why we should probably use real-world words for real-word things and technical words for technical things. Plus, avoid words that mean two different things in those two context, like "host"

**Comment by allella** [comment]
Collection, or something like it, might work.  I think "site" has both technical and real-world context and probably should be avoided.

**Comment by kognise** [comment]
> Collection, or something like it, might work. I think "site" has both technical and real-world context and probably should be avoided.

Agreed. Maybe "collection" or "community?"

**Comment by allella** [comment]
Collective is used a lot these days, maybe over-used.

**Comment by allella** [comment]
Community might do it for me.

**Comment by kognise** [comment]
Honestly, Collective seems pretty good, as overused as it may be... :thinking:

**Comment by allella** [comment]
I'd be good with either, at least as a starting point. I think that revised list has good context to the thing they are trying to describe, and avoids words that are vague or overlap between real-world and technical meanings.

**Comment by cameronsr** [comment]
Was in transit. Current context works as stated. 👍

**Comment by allella** [comment]
@Dusch4593 my understanding is this will be used by any free organization. Plus, I haven't run into a lot of FCC devs here, so not sure camp is practical. Though, it's a fun idea.

**Comment by Dusch4593** [comment]
@allella yeah I was shooting for memorability and recognition.

**Comment by allella** [comment]
@Dusch4593 the "Chapter" is the core object in the schema and we got that to match, so at least we have that going for us.

**Comment by trosel** [comment]
Hey, can someone clarify the usage of the term "chapter" for me?

Women Who Code is an _organization_ that has an NYC _chapter_. The NYC chapter has _events_.

So why does this product make it sound like Women Who Code is a _chapter_?

**Comment by allella** [comment]
@trosel 

Women Who Code is an organization. It would have its own "Women Who Code" instance of the "Chapter" application.  Chapter is the name of the application.

There are many Women Who Code groups around the country. These are often called "local chapters". 

Inside of the database schema we have a table / entity that holds each chapter.

New York City Chapter
Los Angeles Chapter
Greenville, SC Chapter

Each of these chapters would host their own local events and the users would RSVP to the events.

There has been confusion about the application we're building being called "Chapter" and one of the tables inside of the database schema also being called "chapter".  However, we previously called that table "groups", which seemed vague.

If we need to go back to "group" and/or change the name of something in the terminology to make it less confusing then please feel free to make suggestions.

**Comment by trosel** [comment]
@allella Thanks! That helps. I think the only confusion was with the name of the app being called Chapter.

So in terms of the app (and possible federation), "Women Who Code" is still called an organization, right?
