### ISSUE TITLE
Client CORS error: disallows reading the remote resource at http://localhost:5000

### ISSUE THREAD

**Issue by NorthDecoder** [freeCodeCamp/chapter#585]
### Describe the bug:

On a virtual machine in the cloud, my-versions:
```bash
Linux 5.3.7-301.fc31.x86_64

nvm: 0.35.1
node: v14.16.1
npm: 6.14.12

Docker version 19.03.5, build 633a0ea838
docker-compose version 1.24.1, build 4667896
```

At 2 parents 99648a3 + b6f2a3b commit c0f73f00bef3545a6b56c5f5f6ebfa4313d06e20
run `docker-compose up` and then visited the client to see:

![client-cors-error](https://user-images.githubusercontent.com/9598008/116012812-b94d2f00-a5e1-11eb-943a-4d0f01af258f.PNG)

and the message in Chrome `Failed to load resource: net::ERR_CONNECTION_REFUSED`

### Tell us about your browser and operating system:
- Browser(s) name and version:
  - Firefox 88.0(64-bit)
  - MS Edge 90
  - Chrome Version 90.0.4430.85 (Official Build) (64-bit)
- Operating System: Windows 10 Pro version 2004

**Comment by ojeytonwilliams** [comment]
That's strange. Just to double-check, have you set `NEXT_PUBLIC_APOLLO_SERVER` to the url of your graphQL server? I.e. if the server's ip is `http://123.123.123.123` it would need to be `http://123.123.123.123:5000`.

**Comment by NorthDecoder** [comment]
Assuming I was just "following directions" in the *CONTRIBUTING.md* the answer would be no :laughing: , however I saw the hint in the docker-compose.yml in merge request #584 probably as you were typing the previous note and made a change to the *.env* file and that removed the CORS message.

It looks like adding some clarifying deployment notes to the documentation *CONTRIBUTING.md* file would be a way to close this issue.

**Comment by allella** [comment]
#584 has docs changes pending which Oliver believes will correct this CORS issue for similar remote Apollo server configurations. It will involved edits to CONTRIBUTING.md and .env.example.
