### ISSUE TITLE
Feature Dev - Landing Page

### ISSUE THREAD

**Issue by Abott1222** [freeCodeCamp/chapter#6]
As a user I would like to arrive at a fast loading page where I can login and see other meetups

User Story:
[ ] Implement pixel perfect match for web based on wireframe provided by UX tteam
[ ] Allow user to either sign up or login
[ ] Explore feature where one can search meetups based on location

**Comment by manAbl** [comment]
I would like to take this one when the wireframe is ready :)

**Comment by Utkarshbhimte** [comment]
Would love to chime in on this

**Comment by mesthabro** [comment]
I would love to help in optimizations (such as lazy-loading, pre-fetching, caching etc)

**Comment by QuincyLarson** [comment]
As I mentioned a moment ago on https://github.com/freeCodeCamp/chapter/issues/5 I think we should just use our GitHub repo for our project's landing page initially.
