### ISSUE TITLE
Geocoding functionality

### ISSUE THREAD

**Issue by shawnofthedev** [freeCodeCamp/chapter#60]
It would be a good idea to add in location to the project to facilitate ease of searching for users browsing for groups. This is not an exhaustive list just some quick ideas to get started with.

As a user:
- Have to ability to see groups filtered by a radius of the user's current location.
- Specify the location to filter on and use the same radius filter.
- Potentially display markers on a map or list the groups within the filter radius.
- link to navigation on portable devices (optional)

As an organizer:
- As the event's address is entered, geocode the address and store the coordinates.

Postgresql does support geospatial datatypes [here](https://www.postgresql.org/docs/12/datatype-geometric.html).

**Comment by allella** [comment]
@shawnofthedev could you share this feature idea in #1 and close this to-do since it's probably not going to be an MVP item?

**Comment by cmenedes** [comment]
Would like to help with building out this functionality when the time comes (I work with GIS)
