### ISSUE TITLE
Use passwordless for auth

### ISSUE THREAD

**Issue by nhsz** [freeCodeCamp/chapter#64]
We can simplify and smooth the auth system a lot by using something like [passwordless](https://github.com/florianheinemann/passwordless), any thoughts on this?

**Comment by kognise** [comment]
Would you mind keeping this to #40

**Comment by nhsz** [comment]
Sure

**Comment by francocorreasosa** [comment]
Closing in favor of comment in https://github.com/freeCodeCamp/chapter/issues/40#issuecomment-542864260
