### ISSUE TITLE
What SEO Requirements and Schema types are needed for events and pages ?

### ISSUE THREAD

**Issue by SharedMocha** [freeCodeCamp/chapter#67]
An event should be visible when searching on Google or other search engines.
For this, we can add SEO compliant schemas to events such as -
https://schema.org/Event. Apart from this what are other needed SEO requirements ?

**Comment by allella** [comment]
Not sure where to link this into the conversation right now, but I can :+1: the schema.org/Event idea.

**Comment by ceciliaconsta3** [comment]
A few things I can think of from the top of my head:
- Sitemap.xml, could setup Google Search console and formally submit it
- As mentioned, Schema structured JSON for Events and Breadcrumbs is a good start
- Making sure our code is semantic - h tags in hierarchal order, using navigation tags and plenty of lists with question headers so Google can generate proper Sitelinks
- Social and regular meta tags - not sure what our channels are/would be

**Comment by f0cus10** [comment]
Is this going to be part of the MVP?

**Comment by allella** [comment]
@f0cus10 the focus is still on the API at the moment, so we can figure this out once client development gets rolling and folks can see what data is available and if we have all the fields to include schema.org/Events markup

**Comment by allella** [comment]
FYI, schema.org came in in #72 and #75 so we're trying to have some parity with names in the database, so that should lend itself to easier rich snippets in the front end.

**Comment by GeniaT** [comment]
Some internal - external linking strategy would be great to discuss. The links we try to build would depend on the pages we want to make the most visible (the Chapter main page? A chapter / location?).

**Comment by allella** [comment]
I was thinking we'll need to keep an idea on the front-end routes to make sure the URLs are SEO-friendly.

Meetup basic structure looks like
- https://www.meetup.com/Code-for-Greenville/
- https://www.meetup.com/Code-for-Greenville/events/
- https://www.meetup.com/Code-for-Greenville/events/mcrjcqyzpbhb/

I have a feeling the devs will prefer a base like

/chapter/code-for-greenville/
  or
/c/code-for-greenville/

to make matching routes easier, but that may not be an issue.

**Comment by allella** [comment]
@ceciliaconsta3  how about we re-open this issue and you lead us on it?

**Comment by allella** [comment]
Some of this was mentioned above, but here's a real quick list of SEO considerations off the top of mind:
- Title, meta description, and clean URLs are primary considerations.
- Proper use of heading tags and HTML 5 markup are strongly encouraged.
- Using alt tags on images
- Using rel='nofollow' if there's any user-generated content which could be used to spam link
- Using only https://, which requires SSL certificates
- The site should be mobile first and I believe we're using Material UI, so hopefully that handles the need for a responsive site
- Consider if there's any places canonical tags or 301 redirects would be needed to prevent duplicate content 
- Consider if/how a robots.txt is useful for an _instance_ of Chapter

I'm not sure Google has updated it lately, but the [Google SEO PDF is always a simple best practices guide](https://static.googleusercontent.com/media/www.google.com/en/us/webmasters/docs/search-engine-optimization-starter-guide.pdf).

https://jsonld.com/event/
https://developers.google.com/search/docs/guides/intro-structured-data
https://schema.org/Event
