### ISSUE TITLE
Feature Dev - Personalized Page

### ISSUE THREAD

**Issue by Abott1222** [freeCodeCamp/chapter#7]
As a user after logging in I would like the ability to see a customized feed based on my interests, and past meetup history

User Stories
[ ] Pixel perfect landing page based on ux wireframes
[ ] Create section to view events that I am attending or groups that I am a part of
[ ] Create section to explore groups related to my interests by querying recommendation microservice

**Comment by Critchkn** [comment]
I'd Like to work on this when the wireframes are ready

**Comment by allella** [comment]
@Critchkn there is now a broader #114 talking about mockups for an MVP, so feel free to jump in there.

**Comment by allella** [comment]
@chrismgonzalez I think this is another user story that could be merged into #84
