### ISSUE TITLE
Add category to Chapters Table schema

### ISSUE THREAD

**Issue by xarielx** [freeCodeCamp/chapter#71]
This will make it easier for a user to filter the _chapters_ by interests, i.e. sports, events. Since the current schema has description and details, a more general “category” will make it easier to find the right  _chapter_. If the _chapter_ wants to be a private one, a private option will be added and won’t be able to be found by filtering by category. 

Solution: Add category to existing _chapter_ table schema.

**Comment by allella** [comment]
A forthcoming pull request will rename "group(s)" to "chapter(s)", but the point is the same.  @nik-john and/or folks on #46 and #17 should be able to address.

**Comment by rodmsmendes** [comment]
Hi @allella, do we have a PR renaming the table "groups" to "chapters"? Also, I think we should update the terminology on docs.

**Comment by allella** [comment]
@rodmsmendes yes, #46 includes the rename @nik-john 's last comment there was he needed to fix some things, so that's a big pending pull request right now.

**Comment by xarielx** [comment]
@rodmsmendes that’s why I opened this issue. I did not see that in modifications of the sql or documentation file, I’m glad your check agrees with mine.

**Comment by allella** [comment]
@nik-john @francocorreasosa are you guys able to answer / resolve this one in the course of #46?

**Comment by f0cus10** [comment]
Seems like there's multiple issues open regarding the DB schema. Issues #54 seems to be a version of this issue as well. PR #70 also seems to be reasonably related to this, including replacement of *groups* with *Chapters*

**Comment by nik-john** [comment]
@allella @xarielx I am afraid that wasn't in my list by I have gone ahead and made that change now. @xarielx Please feel free to commit to that PR with your change

**Comment by rodmsmendes** [comment]
@nik-john @allella @xarielx I think the PR #46  should be merged asap. I mean, that's a first step towards the API implementation and naturally, it will raise a lot of questions and suggestions. But if we keep modifying the PR #46  it will require more revision, and we will be stuck in a loop. So, my opinion is that we should not modify the PR anymore, merge it and then create new issues.

**Comment by xarielx** [comment]
@nik-john Understood, on it.

**Comment by allella** [comment]
#46 was merged, so I suspect someone can create a PR for this now.  I'm helping more with docs and cat herding, so I'll defer to someone more familiar with the stack.
