### ISSUE TITLE
User Should be able to select a chapter while creating the event

### ISSUE THREAD

**Issue by Ravichandra-C** [freeCodeCamp/chapter#743]
### Describe the bug:

Events are always created for only one chapter. 

User should be able to select the chapter while creating an Event.

**Comment by allella** [comment]
Using the following [terminology](https://github.com/freeCodeCamp/chapter/#terminology), here's how permissions are likely to work within a single instance of **Chapter**.

The notable roles are _owner_ , _administrator_ , and _organizer_

The _owner_ will be the "root" _user_ and the first account created in the system. The _owner_ may then define 1 or more _administrators_ .

For example, when the freeCodeCamp _organization_ creates an _instance_ of the **Chapter** project they may have Oliver as the _owner_ .

Oliver may then define _administrators_ for each continent or region (or however they see fit).

The _administrators_ would be able to manage all _chapters_ , and the _events_ for each _chapter_ , within their region. They would likely setup _organizers_ to help manage their local _chapter_ and its _events_ .

The permissions for an _organizer_ within an _instance_ of **Chapter** will depend on which _chapters_ the _administrator_ has granted them access to manage.

An _organizer_ may be able to add or edit _events_ for 1 or more _chapters_ based on their _roles_ as defined in the user_chapter_roles table.

For instance, if each freeCodeCamp city only had 1 _organizer_ , then each _organizer_ would only be able to add and edit _events_ for their local _chapter_ .

Other _organizations_ may decide to have multiple _organizers_ for a single _chapter_ .

Or, there may be _organizations_ which have an _organizer_ that manages multiple _chapters_ within an _instance_ .

This was also [posted in the chat](https://chat.freecodecamp.org/channel/chapter?msg=oDtRGBg6ygPpHZJDz).

**Comment by gikf** [comment]
As of #927 new events are created from chapter dashboard, using chapter id from url.

**Comment by ojeytonwilliams** [comment]
Closing in favour of https://github.com/freeCodeCamp/chapter/issues/1215 which better reflects the current state of the app.
