### ISSUE TITLE
Determine which inputs isRequired for New Event

### ISSUE THREAD

**Issue by paulywill** [freeCodeCamp/chapter#767]
As mentioned in #766, the current setup is to make every input for the new Event `isRequired`.

Without re-inventing the wheel, is there a way to pass required keys to the input fields while still utilizing the [Input component](https://github.com/freeCodeCamp/chapter/blob/main/client/src/components/Form/Input.tsx) already there? 

I suspect the following:

```
  Input as ChakraInput,
  InputProps as ChakraInputProps,
```

This will help with making future forms and dashboards on the `isRequired` inputs.

**Comment by gikf** [comment]
Issue appears to be no longer relevant. Required fields in the event form were changed couple times since the issue was created.

If you think we're wrong in closing this issue, please request for it to be reopened and add further clarification.
