### ISSUE TITLE
Getting started: Docker compose up fails

### ISSUE THREAD

**Issue by akhilmhdh** [freeCodeCamp/chapter#778]
### Describe the bug:

 Hey there. I was going through contributing guideline and was trying to setup locally. 
 
 I tried docker compose up just to see the project current state first. But it fails due to an import unresolved error.
 
## Output of my terminal

```bash
 > [5/5] RUN npm run build:                                                                                                             
#7 0.927                                                                                                                                
#7 0.927 > chapter-client@1.0.0 build                                                                                                   
#7 0.927 > next build                                                                                                                   
#7 0.927                                                                                                                                
#7 2.207 Attention: Next.js now collects completely anonymous telemetry regarding usage.
#7 2.208 This information is used to shape Next.js' roadmap and prioritize features.
#7 2.208 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
#7 2.208 https://nextjs.org/telemetry
#7 2.208 
#7 2.242 Browserslist: caniuse-lite is outdated. Please run:
#7 2.242 npx browserslist@latest --update-db
#7 2.242 
#7 2.242 Why you should do it regularly:
#7 2.242 https://github.com/browserslist/browserslist#browsers-data-updating
#7 2.281 info  - Checking validity of types...
#7 25.71 info  - Creating an optimized production build...
#7 25.86 warn  - Disabled SWC as replacement for Babel because of custom Babel configuration "babel.config.js" https://nextjs.org/docs/messages/swc-disabled
#7 26.73 Browserslist: caniuse-lite is outdated. Please run:
#7 26.73 npx browserslist@latest --update-db
#7 26.73 
#7 26.73 Why you should do it regularly:
#7 26.73 https://github.com/browserslist/browserslist#browsers-data-updating
#7 27.65 info  - Using external babel configuration from /usr/chapter/client/babel.config.js
#7 71.89 Failed to compile.
#7 71.89 
#7 71.89 ./node_modules/@chakra-ui/checkbox/dist/cjs/checkbox-icon.js
#7 71.89 Module not found: Can't resolve 'framer-motion' in '/usr/chapter/client/node_modules/@chakra-ui/checkbox/dist/cjs'
#7 71.89 
#7 71.89 Import trace for requested module:
#7 71.89 ./node_modules/@chakra-ui/checkbox/dist/cjs/checkbox.js
#7 71.89 ./node_modules/@chakra-ui/checkbox/dist/cjs/index.js
#7 71.89 ./node_modules/@chakra-ui/react/dist/cjs/index.js
#7 71.89 ./node_modules/chakra-data-table/dist/chakra-data-table.cjs.production.min.js
#7 71.89 ./node_modules/chakra-data-table/dist/index.js
#7 71.89 ./src/modules/dashboard/Chapters/pages/ChaptersPage.tsx
#7 71.89 ./src/modules/dashboard/Chapters/index.ts
#7 71.89 ./src/pages/dashboard/chapters/index.tsx
#7 71.89 
#7 71.89 ./node_modules/@chakra-ui/checkbox/dist/esm/checkbox-icon.js
#7 71.89 Module not found: Can't resolve 'framer-motion' in '/usr/chapter/client/node_modules/@chakra-ui/checkbox/dist/esm'
#7 71.89 
#7 71.89 Import trace for requested module:
#7 71.89 ./node_modules/@chakra-ui/checkbox/dist/esm/checkbox.js
#7 71.89 ./node_modules/@chakra-ui/checkbox/dist/esm/index.js
#7 71.89 ./node_modules/@chakra-ui/react/dist/esm/index.js
#7 71.89 ./src/pages/_app.tsx
#7 71.89 
#7 71.89 ./node_modules/@chakra-ui/menu/dist/cjs/menu.js
#7 71.89 Module not found: Can't resolve 'framer-motion' in '/usr/chapter/client/node_modules/@chakra-ui/menu/dist/cjs'
#7 71.89 
#7 71.89 Import trace for requested module:
#7 71.89 ./node_modules/@chakra-ui/menu/dist/cjs/index.js
#7 71.89 ./node_modules/@chakra-ui/react/dist/cjs/index.js
#7 71.89 ./node_modules/chakra-data-table/dist/chakra-data-table.cjs.production.min.js
#7 71.89 ./node_modules/chakra-data-table/dist/index.js
#7 71.89 ./src/modules/dashboard/Chapters/pages/ChaptersPage.tsx
#7 71.89 ./src/modules/dashboard/Chapters/index.ts
#7 71.89 ./src/pages/dashboard/chapters/index.tsx
#7 71.89 
#7 71.89 ./node_modules/@chakra-ui/menu/dist/esm/menu.js
#7 71.89 Module not found: Can't resolve 'framer-motion' in '/usr/chapter/client/node_modules/@chakra-ui/menu/dist/esm'
#7 71.89 
#7 71.89 Import trace for requested module:
#7 71.89 ./node_modules/@chakra-ui/menu/dist/esm/index.js
#7 71.89 ./node_modules/@chakra-ui/react/dist/esm/index.js
#7 71.89 ./src/pages/_app.tsx
#7 71.89 
#7 71.89 ./node_modules/@chakra-ui/modal/dist/cjs/modal-transition.js
#7 71.89 Module not found: Can't resolve 'framer-motion' in '/usr/chapter/client/node_modules/@chakra-ui/modal/dist/cjs'
#7 71.89 
#7 71.89 Import trace for requested module:
#7 71.89 ./node_modules/@chakra-ui/modal/dist/cjs/modal.js
#7 71.89 ./node_modules/@chakra-ui/modal/dist/cjs/index.js
#7 71.89 ./node_modules/@chakra-ui/react/dist/cjs/index.js
#7 71.89 ./node_modules/chakra-data-table/dist/chakra-data-table.cjs.production.min.js
#7 71.89 ./node_modules/chakra-data-table/dist/index.js
#7 71.89 ./src/modules/dashboard/Chapters/pages/ChaptersPage.tsx
#7 71.89 ./src/modules/dashboard/Chapters/index.ts
#7 71.89 ./src/pages/dashboard/chapters/index.tsx
#7 71.89 
#7 71.89 
#7 71.89 > Build failed because of webpack errors
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c npm run build]: exit code: 1
```

So i just tried to find out the error myself. I have used chakra before an i think it needs framer motion as dependency. Found out that it missing in client package.json and that why build fails due to module not found.

### Tell us about your browser and operating system:
- Browser(s) name and version: NA
- Operating System: Mac os

**Comment by ojeytonwilliams** [comment]
Hi @akhilmhdh I couldn't reproduce this locally, I'm afraid.  Could you try `docker-compose build --no-cache` first, then `docker-compose up` if that doesn't error out?

You're quite right about `framer-motion`, but since npm 7, peer dependencies get installed by default. That should not be the problem unless something really bizarre is happening.

**Comment by akhilmhdh** [comment]
@ojeytonwilliams Client still fails. I think its because framer motion is a dev dependency and not peer. I just checked chakra ui codebase

**Comment by allella** [comment]
@akhilmhdh I get the error if I try to _npm i_ with an older npm 6 version.

I used [nvm](https://github.com/nvm-sh/nvm#install--update-script) to switch to node 16 and npm 8 and it worked fine.

**Comment by ojeytonwilliams** [comment]
I'm at a bit of a loss, I'm afraid.  Since it's a dev dependency, it should definitely be installed.  Also, it should be building on step 5/7 not 5/5, so I don't quite understand that either.

For what it's worth, I purged my npm cache, but it made no difference.

**Comment by akhilmhdh** [comment]
@allella But its inside a docker container right.  And inside that its using npm8 and node 16, not sure how my local one gets influenced on that.


I added framer and now it builds fine

**Comment by allella** [comment]
@akhilmhdh  I'm not sure why, but it is necessary to run _npm i_ locally before running Docker and the prerequisites for that step list Node 16 and npm 8.

![image](https://user-images.githubusercontent.com/1777776/140546443-d0885add-9e06-4376-bb6a-d3880d881a96.png)


[Step 1 of Running the Application](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md#running-the-application) applies to both "Manual" and "Docker" mode.  Oliver may have a reason why that's necessary, but that's how it's been for awhile now.

**Comment by akhilmhdh** [comment]
@allella Yup saw that. I thought for local development. Still a bit confused on how it influence on dockerized one. 

The update was build was success and the image compose worked well only issue is I was still not able to access 3000 anything. WIll be doing like this and will update you

**Comment by ojeytonwilliams** [comment]
It's not necessary to build the container, but `npm i` triggers a script that sets a few things up that help with development (it adds an upstream remote, installs dev dependencies which don't run in Docker, etc. etc.)

That said, @akhilmhdh is correct: the container *should* not care about this, since it pulls its own node image.

> I was still not able to access 3000 anything

Nothing at all? Could you share the `docker-compose up` logs?

**Comment by akhilmhdh** [comment]
@ojeytonwilliams  @allella  It was my mistake. My bad.

The issue was I actually installed at first with `npm i` the only issue as @allella  told I was not using node 16. So the issue was package-lock got changed and that was fed into the docker container. That's why I think it was failing.

Second, no response. It was nothing. Due to all logs I missed the part nextjs is compiling. As it was first compilation it surely took some time. I got it started.

Now my only issue is stuck on `relation not found`. I think it because in DB its not created yet. So i think as the doc says there are commands to reset the db etc. But those commands are in root package.json. So should i manually do it?

**Comment by ojeytonwilliams** [comment]
Hey @akhilmhdh no worries.  If you've got it to behave itself, it's all good.

>  But those commands are in root package.json. So should i manually do it?

This is the command you need:
https://github.com/freeCodeCamp/chapter/blob/087a75fdd5a5377baaec646a42c0f26596de302c/package.json#L20

If you run `npm run db:reset` from that directory it should work.

**Comment by akhilmhdh** [comment]
![Screenshot 2021-11-05 at 11 18 54 PM](https://user-images.githubusercontent.com/31166322/140555709-3a521dda-085f-4202-8268-fc2589eabd01.png)

Yehhh.... Cheers 🥂 Its working fine now.

Closing this issue as it resolved. @ojeytonwilliams I would love to work on any part of this, backend or frontend. You have anywhere that can point me

**Comment by allella** [comment]
@ojeytonwilliams could we move Step 1 with the npm i under the Manual mode only to try and avoid some issues with people who are just trying to run Docker?

**Comment by ojeytonwilliams** [comment]
The best thing you can do is take a look at the outstanding [MVP issues](https://github.com/freeCodeCamp/chapter/issues?q=is%3Aopen+is%3Aissue+label%3AMVP) or the [project board](https://github.com/freeCodeCamp/chapter/projects/1) and see what you'd like to work on.  Those are our top priorities for the foreseeable future.

If you need any more context for a particular issue, please ask on that issue and I'll see if I can help.  For more general questions, chat's the best place.

Oh, and we have an [open PR](https://github.com/freeCodeCamp/chapter/pull/726) for https://github.com/freeCodeCamp/chapter/issues/96, but the rest are fair game.

Finally, we're in the middle of a fairly major rewrite of the database schema https://chat.freecodecamp.org/channel/chapter?msg=jpZYYzzDdXxL2R5ZN, so that's worth keeping in mind if you're poking around in the backend.

**Comment by ojeytonwilliams** [comment]
> could we move Step 1 with the npm i under the Manual mode only to try and avoid some issues with people who are just trying to run Docker?

We can try that, sure.  It does mean that people will have to set up their own remotes and so on, but it might save a little pain when people want to get going quickly.
