### ISSUE TITLE
As a user, I will receive an email when my RSVP is confirmed

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/chapter#782]
Organisers can confirm the RSVPs of members who are on the waitlist.  When they do this, the user should be notified by email that they can attend the event.

This should not require any UI changes, just a new notification triggered by confirmation.

**Comment by allella** [comment]
I don't recall if waitlist was an MVP feature. It was added into the database, but if it's complicated we can leave the fields there for future use and add close the issue and add it to the Roadmap.

It's up to you if you think it's going to prolong the MVP.
https://github.com/freeCodeCamp/chapter/pull/27

**Comment by ojeytonwilliams** [comment]
It should not be overly tricky to implement, since we already have similar functionality for venue changes.  So, it shouldn't create much delay.

**Comment by Jagrutiti** [comment]
Hi, @ojeytonwilliams 

I would like to work on this issue. 

I didn't exactly understand what is required to be done. Could you please go into more detail.

Thanks

**Comment by allella** [comment]
@Jagrutiti 

#909 has the most recent work on sending emails.  That's not been merged in, but you might take a look at what @gikf was doing on that PR related to sending emails using the pattern they've been working out on that PR.

**Comment by Ismailtlem** [comment]
Hi @Jagrutiti 

Did you start working on that ?

**Comment by Jagrutiti** [comment]
Hey @Ismailtlem 

I am not working on this one. Feel free to take it up.

**Comment by Ismailtlem** [comment]
Hi,

- How can we link an event to a chapter on the UI ?
- Where do we specify organizers on an event ?
- Can we register to the app by an email other than foo@bar.com

**Comment by Nirajn2311** [comment]
Hi @Ismailtlem , have you started working on this?

**Comment by Ismailtlem** [comment]
Hi, I started working on it, I am just stuck a bit on sending the email part. I made the UI part. I will make a draft PR asap and we can take it from there

**Comment by Ismailtlem** [comment]
Should we close this ?

**Comment by allella** [comment]
@ojeytonwilliams is there anything more to do on this one since #1065 was merged?

**Comment by ojeytonwilliams** [comment]
I don't believe so, no, @Ismailtlem's PR looks to have covered it. We can tick off another MVP issue :rocket:
