### ISSUE TITLE
RSVP should track status with a single column

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/chapter#783]
Since a user can only be in a single state for a given event, the RSVP model should reflect this.  A user can either be invited, going, canceled or on the wait list and these states are mutually exclusive.  Since they can only be in one state, the model should represent this as a _status_ column, with an enum type.

In addition, to implement https://github.com/freeCodeCamp/chapter/issues/95 we will need a way of tracking how many users *rejected* an invite, so we should add an _invitee_ column that will just reflect if a user was asked to come.

**Comment by ojeytonwilliams** [comment]
More discussion here: https://github.com/freeCodeCamp/chapter/issues/822#issuecomment-982813545

**Comment by gikf** [comment]
Completed as a part of #965
