### ISSUE TITLE
Missing link to chapter users dashboard 

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/chapter#787]
There should be a link to 

dashboard/chapters/[id]/users
from 
dashboard/chapters/[id]/

**Comment by bappyasif** [comment]
both of these files are now empty, except 'import/export', and exports are not yet implemented!!

by missing link do you mean importing `ChapterPage` from `dashboard/chapter/[id]`?! thanks....

**Comment by ojeytonwilliams** [comment]
Hey @bappyasif the issue is that the pages exist, but there are no links from elsewhere in the site.  For instance, you can get to the dashboard by clicking on Dashboard:

![image](https://user-images.githubusercontent.com/15801806/142652411-527d8cb4-b11b-4b9d-9eab-7d7312c8e6f0.png)

and you can get to the users dashboard by going to `/dashboard/chapters/1/users` (for example).

There isn't anything to click on to take you to that page, though.  That's what's missing.

**Comment by bappyasif** [comment]
ahh, so that's more of a 'routing' fix?!

**Comment by Ravichandra-C** [comment]
@ojeytonwilliams , @allella , Do we really need a link form "dashboard/chapters/1" page to  "dashboard/chapters/1/users" page?

Can we just show it as an accordion in **dashboard/chapters/1** page itself like the screenshot below?

![image](https://user-images.githubusercontent.com/17808008/143782847-9aa7024d-58e6-4fd8-89aa-db7760e0086c.png)

**Comment by ojeytonwilliams** [comment]
@Ravichandra-C We're definitely going to need to keep refining the UI, so it's not worth investing tons of time making this look perfect.

So, any approach that gives admins a way to get to this information from the dashboard is fine with me.

**Comment by bappyasif** [comment]
@Ravichandra-C i would like to help with this issue, let me know how?! thanks :)

feel free to dm me!! looking forward to it!!

**Comment by ojeytonwilliams** [comment]
Hey @bappyasif there was not a great deal to do for this one - it was intended to be a relatively gentle introduction to the Chapter code base.  You can take a look at Ravi's PR, if you'd like to understand what involved.
