### ISSUE TITLE
Event feed should contain a paginated list of events

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/chapter#788]
/events should have the upcoming events feed.  This should be the same as the landing page, but more events should be visible by default.

In order to show the pagination, the db generator will need to generate more events.

**Comment by AmrMonier** [comment]
i can see this issue already have Merged PR so can you please close it ? @ojeytonwilliams

**Comment by gikf** [comment]
Hey @AmrMonier,

there's related PR closed, but pagination of the events is still to be done.

Happy contributing.

**Comment by Johnny01232003** [comment]
I am working on this issue.

**Comment by hisnameispum** [comment]
I'll work on this issue.
