### ISSUE TITLE
Remove Invite User button from users dashboard

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/chapter#789]
As @Zeko369 mentioned in https://github.com/freeCodeCamp/chapter/issues/605 we need to implement the admin/owner workflows so that users can be given appropriate permissions.

However, the users dashboard, e.g. http://localhost:3000/dashboard/chapters/1/users, has an Invite user button which I should never have put there.  This should be removed and, ideally, we should add a test to make sure this page doesn't get created. Reason being, this is an invitation to spam people and that's not something we should encourage.  If someone wants to email people who are not currently members of a Chapter, they can do that, but not through our app.

So, concretely:

- [ ] The Invite user button should be removed from `/dashboard/chapters/[id]/users`
- [ ] cypress/integration/dashboard/chapters/users.js should check that `/dashboard/chapters/1/users/new` is a 404 page

It's a bit weird to test for the absence of a /new page, but it serves as a reminder not to create new users via the app.

Something like
```js
  it('should not be possible to create users', () => {
    cy.visit('/dashboard/chapters/1/users/new', { failOnStatusCode: false });
    cy.contains('This page could not be found');
  });
 ```

should do the trick.

**Comment by Jyoti28Dhikale** [comment]
can you assign me this issue?

**Comment by ojeytonwilliams** [comment]
Hi @Jyoti28Dhikale. We typically don't assign issues, except to long term contributors. You are very welcome to work on this, though, and it looks like no-one else has taken it on yet.

**Comment by bappyasif** [comment]
this seems like a doable task as a starter, thanks for referring it @allella 

@Jyoti28Dhikale would you like to group up about this and see this issue through?!
