### ISSUE TITLE
Tags rework

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/chapter#790]
As @Zeko369 highlighted in https://github.com/freeCodeCamp/chapter/issues/605 we need to re-mplement event tags.  

Tags should be joined to events with a many to many relationship.  To do this, we need two tables: a _tags_ table and an _event_tags_ table that joins them to specific events.  All we need for the tags is to have a 'name' column and then _event_tags_ would be a junction table like _event_sponsors_.  

For reference https://dbdiagram.io/d/617ae3f8fa17df5ea673e3ea is the current database diagram we're working towards and [server/src/models/EventSponsor](https://github.com/freeCodeCamp/chapter/blob/7124ad9760a551ed52cf6f51967c9be394e93c18/server/src/models/EventSponsor.ts) is a good template for the model.  However, as shown in the database diagram, we're moving away from having an _id_ for every table, but that's a work in progress.

Once most of the database rework is done, I think this would be a good first issue,

**Comment by moT01** [comment]
I think I'm going to try and tackle this one.
