### ISSUE TITLE
Event invitations should take you directly to confirm/cancel

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/chapter#796]
Right now, if I receive an invitation to an event, it has two links: "Event details" and "Cancel your RSVP".  These both link to the event page.

Instead, it would be a nicer user experience if, the first text was "RSVP to event" and immediately opened the confirm modal (rather than requiring the user to find and click on the RSVP button).  The same should be true for the cancel link.

**Comment by Ravichandra-C** [comment]
@ojeytonwilliams ,Could you please let me know how we can implement this?

Can we append a query parameters or url parameter to the link that we are sending in the email, and on the client side if we have that parameter in the URL ,we trigger the click event on the rsvp button. Is that ok?

**Comment by ojeytonwilliams** [comment]
@Ravichandra-C sure, a query parameter sounds like the way to go.

If that's there then we can trigger the confirm dialog.

**Comment by Ravichandra-C** [comment]
@ojeytonwilliams @allella 

Below is the functionality I've implemented.

1. If user is already logged into chapter and he did not rsvp to the event ,then when he clicks the link in the email , He will be shown the confirm popup.
2. if user is not logged in to the chapter, then he will not be shown the confirm popup.
3. if user is logged in and he has already rsvp'd to the event, then he will not be shown any pop up.

Could you please let me know if that is ok?

Also on the third point, Do we have to show the cancel rsvp popup if the user has already rsvp'd,?

**Comment by ojeytonwilliams** [comment]
Hey @Ravichandra-C I like what you've done in #821 it's way better than having to click on the RSVP button.

We can build on that in a couple of ways

1. Create a cancel link that pops up the cancel confirmation
2. Ask the user to log in and then trigger the confirmation(s)

These are definitely Nice To Haves, though.  We don't need to worry about them for the MVP.

**Comment by ojeytonwilliams** [comment]
https://github.com/freeCodeCamp/chapter/pull/1696 implemented cancellation (subject to user confirmation) if they follow the email link and have already RSVPed.

All that remains is the case where users are not logged in.  Since we send them away from the site to log in, we have to keep track of their state somehow.

Looking at https://auth0.com/blog/complete-guide-to-react-user-authentication/ we should be able to make use of `returnTo`. If we send them back to the event page with `emaillink=true` included in the redirect, that might be enough.

**Comment by gikf** [comment]
Handling logged out users was added in #2084. In the meantime, among other changes, were:
- Auth0 login uses modal.
- Invite link can be only used to rsvp. 

As such this appears to be completed.

For any further adjustments creating new issue would be more convenient.
