### ISSUE TITLE
Using Fastify instead of Express

### ISSUE THREAD

**Issue by mandaputtra** [freeCodeCamp/chapter#80]
Why? this project aims to be a replacement for meetup.com, that's mean the target arent just big/small group of developers. Fastify is mature now and it got express like syntax. Since the backend project would be an HTTP API why not choose the fastest mature framework?

### Fastify
Benefit:
- The learning curve from express arent that high
- Speed improvement on HTTP request
- There are [oauth2](https://github.com/fastify/fastify-oauth2) module too now

Cons:
- If you plan to use auth library like passport.js it cant work with Fastify.
- If you plan to use WebSocket Socket.io aren't good choice it sometimes [break](https://github.com/socketio/socket.io/issues/1602) with Fastify

on auth, I usually use [oauth2](https://github.com/fastify/fastify-oauth2) module on WebSockets I can help develop with [ws](https://www.npmjs.com/package/ws),  [primus](https://www.npmjs.com/package/primus), or [faye](https://www.npmjs.com/package/faye) module but I don't see any use case on WebSocket with this project.

### Express

Benefit:
- Many people already know, so many resources when encounter an error
- So many plugins! :smile: 

Cons:
- Much slower than Fastify
- (I don't see any cons of using express)

That's it!

**Comment by mandaputtra** [comment]
just found this [discussion](https://github.com/freeCodeCamp/chapter/issues/2) already closed so. yeah using express!

**Comment by OgdenMorroww-cpu** [comment]
Express is still the best
