### ISSUE TITLE
Chapter and Venue forms need updating, including validation and placeholders 

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/chapter#800]
They currently look like this:
![image](https://user-images.githubusercontent.com/15801806/141799909-86cf0987-c690-4574-b5e5-6929c0e1f401.png)

while the Event form is more polished:
![image](https://user-images.githubusercontent.com/15801806/141800075-01600995-f797-4e8c-a5cc-eebb7f8417d7.png)

The look and feel should be consistent, with the Event form being the template for the other two.

**Comment by Ravichandra-C** [comment]
@ojeytonwilliams,Should I start working on it?

**Comment by Ravichandra-C** [comment]
@ojeytonwilliams @allella , I was looking into this and I noticed the field **Details**.

What data should administrator enter in this field while creating the chapter?

 I'm trying to write a meaningful placeholder for this field, But I could not understand the purpose of this field.

Could you please let me know?

**Comment by ojeytonwilliams** [comment]
> Can I start working on it?

Absolutely.  I'll assign you.

> I'm trying to write a meaningful placeholder for this field, But I could not understand the purpose of this field.

Neither can I, to be honest.  Unless Jim knows of a reason to keep it, we can just get rid of it.

**Comment by allella** [comment]
@Ravichandra-C yes, I'd say you can remove the "Details" field.  

Description is part of the schema, but not details and I'm not aware of a conversation about adding a Details field.
