### ISSUE TITLE
As a user, I can select "maybe" when I RSVP to an event.

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/chapter#822]
### The proposal

Instead of a user being offered the choice to attend an event or not, there should be a third option: "maybe".  This would allow undecided users to pick this instead of going with "yes" and just not appearing.  Event organisers would benefit from better estimates of how many people are likely to turn up.  Also, if we track attendance, https://github.com/freeCodeCamp/chapter/issues/264, then this should improve our statistics.

### Alternatives

Stick with the current options.  This has the benefit of simplicity.

### Implementation details

From a database perspective, this would be basically the same, if we go with https://github.com/freeCodeCamp/chapter/issues/783 then all that would be required is an extra enum value or an extra row in the _rsvp_status_ table.

The UX would be, in the first draft, pretty much unchanged: a "maybe" would be treated similarly to a "yes" or "on waitlist" as far as notifications would go.  We could alter the text slightly, but we wouldn't need to change much.

**Comment by allella** [comment]
The _events.capacity_ and waitlist implications may add more than we want for MVP.

Do we have waitlist accounted for in the [proposed schema](https://dbdiagram.io/d/617ae3f8fa17df5ea673e3ea)? It seems Fran implemented waitlisting on the old schema and UI, but I'm not seeing where that's represented unless _rsvp.name_ is going to store a waitlist status.

Perhaps post-MVP the _organizer_ would have the option to disable the "Maybe" option, per _chapter_ or even per _event_, and they may also want to configure if a "maybe" counts towards a "Yes", impacting the maximum capacity, or else applying to any waitlist.

**Comment by ojeytonwilliams** [comment]
> The events.capacity and waitlist implications may add more than we want for MVP.

True.  I think this is relatively low priority

> Do we have waitlist accounted for in the proposed schema? It seems Fran implemented waitlisting on the old schema and UI, but I'm not seeing where that's represented unless rsvp.name is going to store a waitlist status.

No, that definitely needs fleshing out regardless of whether or not we include "maybe".  I don't *think* rsvp.name was intended to do that @moT01 do you remember?

> Perhaps post-MVP the organizer would have the option to disable the "Maybe" option, per chapter or even per event, and they may also want to configure if a "maybe" counts towards a "Yes", impacting the maximum capacity, or else applying to any waitlist.

That sounds good, but definitely post-MVP

**Comment by moT01** [comment]
That area of the diagram is not entirely fleshed out to include that. What I can say to try and clarify, is that the `event_users` table in the diagram I made is basically the same as, or a replacement to, our current `rsvps` table. I think `event_users` is more appropriate, it ties all users of an event to that event. We could add the necessary columns there (maybe `on_waiting` or `waiting`, `cancelled`, and whatever else). We don't have to change the name, but I do think it's better. The `rsvps` table in the diagram was intended to just have a few names, "Yes", "No", "Maybe". Not sure if we need a table for just that or maybe use the enum type. I didn't have the exact values in mind for that table or type, but whatever we want could be added.

**Comment by ojeytonwilliams** [comment]
@moT01 what do you think about having the 'state' (on waiting list, maybe, canceled etc) being an enum or table of its own (with a foreign key connecting that to `event_users`)?

**Comment by moT01** [comment]
table: https://stackoverflow.com/questions/362044/mysql-enum-type-vs-join-tables

**Comment by ojeytonwilliams** [comment]
Yeah, I know enums are a bit contentious.  They're definitely not a requirement, but I think they're worth considering since they play nicely with TypeScript.

**Comment by allella** [comment]
@ojeytonwilliams I've tagged this with Roadmap.  Shall we close it like the others on the Roadmap label and come back to it post-MVP.

If we want to add the "maybe" option now, then perhaps a more simple issue just for adding it to the schema and then this issue will be a placeholder on the roadmap for implementing the logic mentioned above?

**Comment by ojeytonwilliams** [comment]
@allella sounds good.  We can definitely design the schema with this in mind, so, yeah, let's stick with that for now.
