### ISSUE TITLE
MVP user stories

### ISSUE THREAD

**Issue by chrismgonzalez** [freeCodeCamp/chapter#83]
### Discuss your ideas or share your views: 

This issue has been created to house the desired MVP user stories.  Please think big picture items as we are trying to roll out an MVP very quickly.  There are so many great ideas that the community has voiced - let's make it easy to isolate the ones that we deem pertinent to the initial release of the app.

I've listed the ones detailed in the README below, as they seem like a good start.

## As a future participant

- [ ] I can use a search box on the landing page to input a city, state, or country name and it will autocomplete. I can click one of those locations.
- [ ] When I click one of those locations, I can see the "show view" for that event's group, with details about the upcoming event, along with a button to RSVP.
- [ ] I can click the "RSVP" button. When I do, I will be prompted to sign in. Then I will receive an email with a ticket and add me to the public list of event attendees.
- [ ] I can cancel the "RSVP".
- [ ] I will receive a second email the day before the event to remind me. 
- [ ] After the event, I will automatically get emails notifying me of subsequent events. 

### As an organizer:

- [ ] I can create a chapter.
- [ ] I can edit details about the chapter, including a Slack/Discord/Facebook/WeChat/WhatsApp link participants can join to discuss and coordinate events.
- [ ] I can add a chapter or organization logo.
- [ ] I can create events, and set their location and capacity.
- [ ] I can view the RSVP count
- [ ] I can cancel events.
- [ ] I can email the entire list of participants.
- [ ] I can ban a participant whom I believe is toxic or who has previously broken my organization's code of conduct.
- [ ] I can add a venue sponsor to the event with a link to their website as a way of thanking them for hosting.
- [ ] I can add a food sponsor to the event with a link to their website as a way of thanking them for food.
- [ ] I can see how many times a participant has come to the event as well as their attendance rate
- [ ] I can check-in attendees on the event registration desk with their email_id or chapter_id

**Comment by rodmsmendes** [comment]
Hi @chrismgonzalez , there was a change in terminology. "groups" are now called "chapters". The master branch reflects this terminology, both in API and in DB. Let's keep docs and issues consistent. Thanks!

**Comment by klodha** [comment]
@chrismgonzalez I would like to suggest a QR code generation feature to replace paper badges and passes (foods, goodies etc). At venue, crew can scan them to mark attendance. Those codes can be sent over email to participant whenever they enroll, thus not only saving papers but also time to print, collect etc.

**Comment by rodmsmendes** [comment]
Hi @klodha! Good suggestion. Please, move your comment to #84. It's a specific issue for feature suggestions.

**Comment by chrismgonzalez** [comment]
@rodmsmendes I've changed the syntax to reflect the use of chapter.

**Comment by chrismgonzalez** [comment]
@ceciliaconsta3 That one looks like a good one to add to #84

**Comment by jordanchristie** [comment]
I'd like to suggest two stories, 1. User can cancel an RSVP and  2. User (or Organizer) can view an event's RSVP count.

**Comment by xarielx** [comment]
As an Organizer, I can set my Chapter to "Private" giving access by invite only.

**Comment by chrismgonzalez** [comment]
@jordanchristie & @xarielx Great suggestions here!

**Comment by bernhard-hofmann** [comment]
I don't think private events are necessary for an MVP.

I also don't think organisers/organizers need to see user stats in an MVP. We might want to store user attendance in the database for the MVP, but being able to see that as an organiser is not an MVP feature IMO.

I'd suggest simply being able to add more than one sponsor per event rather than a specific food sponsor and another sponsor.

Wait lists were discussed as an MVP feature in issue #27. Quincy's [comment on the topic](https://github.com/freeCodeCamp/chapter/pull/27#issuecomment-542226749) was:
> ... So yes - I think we can include them.

**Comment by QuincyLarson** [comment]
Since we now have individual GitHub issues for each of our MVP user stories (based off of @chrismgonzalez's list above) I am going to close this issue.

**Comment by allella** [comment]
For any additional suggestions for MVP or post-MVP user stories please create a new issue.  From there we can either:

-  convert it to an MVP issue and add it to the [Project board](https://github.com/freeCodeCamp/chapter/projects/1)
- identify the suggestion as post-MVP, collect comments on the issue, close it, and link it from #84
