### ISSUE TITLE
Discussion: standardize merge workflow

### ISSUE THREAD

**Issue by ScottBrenner** [freeCodeCamp/chapter#89]
## Problem

Without a standardized way of merging pull requests, [this repository's commit history a bit of a mess](https://github.com/freeCodeCamp/chapter/commits/master). 

-----

The "Add swagger json" pull request (https://github.com/freeCodeCamp/chapter/pull/46) implements a single feature (👍 ) but was merged as five identically-described commits (👎):
![image](https://user-images.githubusercontent.com/416477/67116226-dacf8e00-f194-11e9-8c11-8f37f6a479d6.png)
Looking at this history, I have no idea what was implemented here. The commits should have been squashed into a single commit like "Add swagger json (#46)".

> [Work-in-progress commits are helpful when working on a feature branch, but they aren’t necessarily important to retain in the Git history. If you squash these commits into one commit while merging to the default branch, you can retain the original changes with a clear Git history.](https://help.github.com/en/articles/about-pull-request-merges#squash-and-merge-your-pull-request-commits)

## Solution

[Enforce "squash merging" for pull requests](https://help.github.com/en/articles/configuring-commit-squashing-for-pull-requests)

-----

For commits to the `master` branch, I only care about what features were implemented - and not the commits it took to get there. This will make the commit history much cleaner, and greatly simplify the rollback/revert process.

## Proposal

Simply asking people to squash pull requests may not be sufficient, we should disable "merge commits" and "rebase merging" in the repository's settings page - requiring all commits to the master branch be squashed.

**Comment by chrismgonzalez** [comment]
I'm down for the cleanliness!  Thanks for your input!

**Comment by vkWeb** [comment]
@ScottBrenner Thank you so much for the detailed view on this. Your solution looks good to me and other people out there on discord. So our mods will squash and merge PRs from now. We don't need to disable other merging options. Our mods will be careful while merging PRs. 

@allella This issue can be closed.

**Comment by ScottBrenner** [comment]
Appreciate the quick response here! 👍
