### ISSUE TITLE
As an organizer I can see how many times a participant has come to my chapter's events as well as their attendance rate.

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/chapter#95]

**Comment by ojeytonwilliams** [comment]
What do we want the attendance rate to be?  Is it going to be the percentage of invitees that actually attend?  If so, we need to track if a member was invited. Then attendance rate would be "percentage of invited users that confirmed attendance".

While we could allow organizers to mark attendance, I don't think that's worth putting in the MVP.  Instead I recommend using what the member says they will do in the calculation.

Finally, what do we want for non-invite-only events?  Attendance rate would have to be different, in that case.  I'm not sure it makes sense unless organizers can mark attendance (again, probably not an MVP thing).

**Comment by allella** [comment]
I don't recall the source of this issue.  I don't consider this an MVP feature so I'd vote to close and tag with "Roadmap" and deal with it after MVP.

It appears Quincy created this issue and I'm not sure if it was something he felt was needed or something from a meeting or split off from another issue that was closed and roadmapped.

**Comment by ojeytonwilliams** [comment]
I'm fine with this being a post MVP feature.  Do we need to close it, though?

**Comment by allella** [comment]
@ojeytonwilliams Quincy was the one closing them with Roadmap during previous meetings as a way to filter out noise but still be able to find them for post-MVP.  I think it's a decent pattern as long as we Roadmap tag them, but I'm open to other suggestions.

**Comment by ojeytonwilliams** [comment]
No, that's fine.  Let's just stick with that pattern.  Should all the Roadmap issues be closed, then?
