### ISSUE TITLE
As an organizer I can add a venue sponsor to the event with a link to their website as a way of thanking them for hosting.

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/chapter#97]

**Comment by joelrozen** [comment]
✋ I'll take this

**Comment by vkWeb** [comment]
@joelrozen Amazing!

**Comment by joelrozen** [comment]
Just noticed another issue #96 - this covers that as well as allows to add any type of sponsor.
I have copied the enumeration of sponsor types from the API docs (FOOD, BEVERAGE, OTHER), so might need to update the backend if it's also to accept "VENUE" specifically.

**Comment by YelloFam** [comment]
> Just noticed another issue #96 - this covers that as well as allows to add any type of sponsor.
> I have copied the enumeration of sponsor types from the API docs (FOOD, BEVERAGE, OTHER), so might need to update the backend if it's also to accept "VENUE" specifically.

How about group sponsors with levels like Platinum / Golden / Silver / Bronze...?

**Comment by joelrozen** [comment]
> How about group sponsors with levels like Platinum / Golden / Silver / Bronze...?

+1 for future but possibly not the MVP.

Perhaps the product roadmap could include allowing organisations to add custom sponsor types on a per event basis though instead of predefined levels.
