### ISSUE TITLE
Automate the Updating of Copyright Years to Match the Current Year

### ISSUE THREAD

**Issue by antonio-erick** [freeCodeCamp/chapter#978]

**Comment by allella** [comment]
@ojeytonwilliams would it be better to remove the year so we don't have to keep this sort of thing updated every year?

**Comment by allella** [comment]
Alright, if that's the case, then I guess we'd want to also update the License file every year?

https://github.com/freeCodeCamp/chapter/blob/main/LICENSE

**Comment by Sboonny** [comment]
hey, is it okay if I add `<script>document.write(new Date().getFullYear())</script>` or something alike to make it automatic yearly update?

**Comment by allella** [comment]
This is an old post, but it seems script tags were not allowed in Markdown .md files as of the time of this answer
https://stackoverflow.com/questions/21340803/embed-javascript-in-github-readme-md

**Comment by allella** [comment]
@Sboonny if you create a list of our .md pages which have a copyright then we can at least create a reminder for it. Or, perhaps there's a GitHub bot out there that will create a PR automatically every year.

**Comment by Sboonny** [comment]
this is helpful, I didn't know that.

> This is an old post, but it seems script tags were not allowed in Markdown .md files as of the time of this answer
https://stackoverflow.com/questions/21340803/embed-javascript-in-github-readme-md

I like this idea. I will start working on it

>if you create a list of our .md pages which have a copyright then we can at least create a reminder for it. Or, perhaps there's a GitHub bot out there that will create a PR automatically every year.

**Comment by Sboonny** [comment]
I am wondering how do I create a list of .md pages.

I thought, I need to create something like [intro.json](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/i18n/locales/english/intro.json), but if I create them while the [raw README.md](https://raw.githubusercontent.com/freeCodeCamp/chapter/main/README.md) looks like this, I will do it but I may need to visit my therapy earlier than intended. 😅

so I hoping there is a different way of listing. and if we do need it as `.json`. is it okay if I scrape it instead of writing it manually

**Comment by allella** [comment]
@Sboonny I would suggest posting a bullet list of file names here and I'll figure out a way to set a reminder.

**Comment by Sboonny** [comment]
sure, sorry I want to help more than this.

  - [CODE_OF_CONDUCT.md](https://github.com/freeCodeCamp/chapter/blob/main/CODE_OF_CONDUCT.md)
  - [CONTRIBUTING.md](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md) 
  - [README.md](https://github.com/freeCodeCamp/chapter/blob/main/README.md) 
  - [LICENSE](https://github.com/freeCodeCamp/chapter/blob/main/LICENSE)

**Comment by allella** [comment]
@ojeytonwilliams would something like this GitHub action be practical for @Sboonny to research for automatically updating copyright dates?

https://github.com/marketplace/actions/update-license-copyright-year-s

**Comment by ojeytonwilliams** [comment]
@allella @Sboonny yep, that seems reasonable to me.

**Comment by Sboonny** [comment]
hey I tried to create `./.github/workflows/update-copyright-years-in-license-file.yml` in my branch, which lead to this error

> ! [remote rejected] docs/update-licence-yearly -> docs/update-licence-yearly (refusing to allow an OAuth App to create or update workflow `.github/workflows/update-copyright-license.yml` without `workflow` scope)

I checked [The scope docs](https://docs.github.com/en/developers/apps/building-oauth-apps/scopes-for-oauth-apps) and [github secret docs](https://docs.github.com/en/actions/security-guides/encrypted-secrets) which 
made me think, I don't have access to create a yml file. 

it doesn't matter, I wanna tell you, that you guys are awesome and thanks for your patience. ♥

**Comment by allella** [comment]
@ojeytonwilliams setup the GitHub actions, so he may have suggestions on that error.

**Comment by ojeytonwilliams** [comment]
I'm not sure why that particular workflow would cause any problems.  I created https://github.com/ojeytonwilliams/chapter/tree/chore/add-license-update-action on my fork without any problems.

@Sboonny did you try to create the branch on https://github.com/freeCodeCamp/chapter, by any chance?  If that's the case, it's probably just a permissions issue and you'll be able to create it on your fork.

**Comment by ojeytonwilliams** [comment]
Ah, are you using a PAT to push your code?  If that's the case, it may not have sufficient permissions to push these changes.

I can't think of anything else, sorry!  So, if that doesn't work, I'll just do it myself and add you as a co-author.

**Comment by Sboonny** [comment]
> I can't think of anything else, sorry! So, if that doesn't work, I'll just do it myself

you have already done most of the work. I am totally okay with you pushing it ahead.👍

> Ah, are you using a PAT to push your code?

yes, I am using [PAT](https://www.techtarget.com/searchnetworking/definition/Port-Address-Translation-PAT), which is interesting that I didn't know about.

**Comment by ojeytonwilliams** [comment]
Sorry, @Sboonny I don't know why I used the jargon - what I meant was a GitHub [Personal Access Token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token)

**Comment by Sboonny** [comment]
oh that what scope about. I made secert with these scopes

![image](https://user-images.githubusercontent.com/88248797/166289307-077b555a-3662-4670-99a3-0d22d1852127.png)

update the secret in the fork 
![image](https://user-images.githubusercontent.com/88248797/166289390-d73b90d9-1e82-40bc-a572-9f0071c3f00e.png)

and tried again got the same error.

then I tried with every scope avaliable, updated it, made a new workspace. and the issue presisted.

btw looking at the top picture which is correct.

```yaml
with:
          token: ${{ UPDATE_LICENSE }} 
``` 
or

```yaml
with:
          token: ${{ secerts_UPDATE_LICENSE }} 
```

while neither worked, not even `token: ${{ secerts_GITHUB_TOKEN }}

**Comment by gikf** [comment]
The access token, having workflow _permission_ is to be used in your git configuration, to allow pushing  change on your fork.

Token in the workflow is unrelated.

**Comment by Sboonny** [comment]
I couldn't use [gitpod](https://github.com/gitpod-io/gitpod/issues/7699) from the start.

 well, this doesn't matter anymore. whenever I clone or pull something to my laptop it doesn't ask for username or password. so I can't do this step 
```
$ git clone https://github.com/username/repo.git
Username: your_username
Password: your_token
```
![image](https://user-images.githubusercontent.com/88248797/166326583-a3928a42-44ab-4b28-8069-fe1e470af527.png)

is the hint useful? I looked [core.fsmonitor](https://git-scm.com/docs/git-config) in the docs and couldn't understand much😓

oh and that what comes when I run `git config -l`

```
chapter>git config -l
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=D:/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
core.usebuiltinfsmonitor=true
pull.rebase=false
credential.helper=manager-core
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
core.editor="D:\Microsoft VS Code Insiders\bin\code-insiders" --wait
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
user.name=Sboonny
user.email=88248797+Sboonny@users.noreply.github.com
credential.helper=cache
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/Sboonny/chapter.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.main.remote=origin
branch.main.merge=refs/heads/main
```

---

@ojeytonwilliams this is the first time I ping someone, please go ahead with the commit. I feel like, I have been looking at a rabbit hole, and it is only getting deeper.🤣😭

**Comment by allella** [comment]
@Sboonny is your environment running Git Bash?  We've had others with permissions issues with Git Bash. They are usually related to things on the Windows file system or symlinks, but the broader point is the Git Bash isn't the most solid option for Windows.

[Our Docs have more about using WSL with a Linux shell, like Ubuntu](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md#using-a-traditional-dev-environment), which can then allows for running an emulated Ubuntu environment as either a native Linux terminal, or else as a tab inside of Windows Terminal.

**Comment by allella** [comment]
A Linux terminal / shell would also allow for using SSH key authentication to GitHub, which is the more common alternative to username and password, or tokens.

Nothing I've seen points directly to Linux and SSH key auth being a definite fix for your issue, but those are sort of the default and usually the least likely to cause problems connecting to GitHub.

**Comment by Sboonny** [comment]
> Linux terminal / shell would also allow for using SSH key authentication to GitHub, which is the more common alternative to username and password, or tokens.

> Nothing I've seen points directly to Linux and SSH key auth being a definite fix for your issue, but those are sort of the default and usually the least likely to cause problems connecting to GitHub.

True🤔, I should try them out, hopefully more info will be found, I will try to give detailed update tomorrow morning 👍

**Comment by allella** [comment]
Ubuntu isn't the only Linux distribution that runs on top of WSL, but it's probably the most well-supported and a good place to start.

https://ubuntu.com/tutorials/install-ubuntu-on-wsl2-on-windows-10#1-overview
https://wiki.ubuntu.com/WSL

Also, Windows Terminal is not required, but after installing WSL and Ubuntu for Windows it is possible to open an Ubuntu terminal from within Windows Terminal if you prefer it. Windows Terminal allows you to run various shells, like PowerShell, cmd, Linux terminal / shells installed on top of WSL.

We've [had enough trouble with Git Bash](https://github.com/freeCodeCamp/chapter/issues?q=%22git+bash%22+) that we might consider marking it as "not recommended" in the docs if that ends up being the problem here.

**Comment by Sboonny** [comment]
sorry for the update delay. had issue with installing Ubuntu in windows. like this [issue](https://github.com/microsoft/WSL/issues/2872).

 I am planning to switch to linux system then give it try with linux.😅🐱‍💻

**Comment by ojeytonwilliams** [comment]
Re-opened since we have more files needing updates

**Comment by allella** [comment]
I've updated the comment near the top to show the list of file and process
https://github.com/freeCodeCamp/chapter/issues/978#issuecomment-1082036756
