### ISSUE TITLE
As an owner or Chapter admin I can ban a participant whom I believe is toxic or who has previously broken my organization's code of conduct.

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/chapter#98]
This needs UI and resolvers to handle the requests. The DB schema has _user_bans_ already, so a given user can be banned from a specific Chapter.

Until https://github.com/freeCodeCamp/chapter/pull/814 is in, we can make some progress by implementing the UI for banning users and a resolver to update the DB. After the auth PR is in, we'll need to consider if 'banned' becomes a role that denies you access or if we need to handle banned user access differently.

- [ ] As an owner I can ban anyone except other owners
- [ ] As an admin of a Chapter I can ban anyone in a Chapter except other admins
- [ ] As any other role, I cannot ban anyone

The main thing to check is that requests from unauthorised users fail, but it's also helpful to confirm that the UI reflects their role.

We will also need tests to confirm that banned users can no longer interact with Chapters they are banned from.

**Comment by ojeytonwilliams** [comment]
Once https://github.com/freeCodeCamp/chapter/pull/1069 goes in, authorisation will need to be modified to take account of ban status.

**Comment by ojeytonwilliams** [comment]
While not all resolvers are restricted by Authorized decorators, whenever they are restricted, ban status is automatically taken into account.

As a result, it doesn't seem necessary to track this any more.
